//go:build e2e

package e2e

// ios_layout_test.go — THE APPLE SELECTION IS PROVED BY A REAL BUILD.
//
// An Xcode target that compiles EVERY file under a synchronized folder will
// happily compile two environments' clients and then fail — or worse, succeed
// and ship the wrong address. The only authority on which one entered the app
// is the built bundle, so this runs `palbase link` through the binary, builds
// with `xcodebuild`, and reads the plist out of the `.app`.
//
//	export PALBASE_E2E_PROJECT=<ref>
//	go test -tags e2e -run TestIOSLayout ./tests/e2e/
//
// It needs `xcodegen` and a working Xcode. Both are preconditions, not optional
// paths: an unmet one fails the gate rather than skipping it green.

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// projectYAML is the consumer app, generated by xcodegen. The Palbase folder is
// a SYNCHRONIZED group — the shape that made this gate necessary: Xcode 16
// compiles every file underneath it, so the exclusion pattern is the only thing
// keeping the other environment's client out of the target.
const projectYAML = `name: E2EApp
options:
  bundleIdPrefix: studio.palbase.e2e
packages:
  Palbase:
    url: https://github.com/palgroup/palbackend-ios
    from: 0.59.0
targets:
  E2EApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: Palbase
        product: Palbe
    sources:
      - path: Sources
      - path: palbase/environments
    settings:
      base:
        PALBASE_ENV: $(PALBASE_ENV)
        EXCLUDED_SOURCE_FILE_NAMES: "*/palbase/environments/*/*"
        INCLUDED_SOURCE_FILE_NAMES: "*/palbase/environments/$(PALBASE_ENV)/*"
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: studio.palbase.e2e.app
`

// generateApp writes the xcodegen spec and generates the project.
//
// TWICE, AND THAT MIRRORS REALITY: a person has an Xcode project first, runs
// `palbase link` (which refuses a checkout without one), and only then adds
// `palbase/environments` to the target. xcodegen refuses a source path that
// does not exist yet, so the fixture follows the same order.
func generateApp(t *testing.T, dir, spec string) {
	t.Helper()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "project.yml"), []byte(spec), 0o644))
	run(t, dir, nil, "xcodegen", "generate")
}

// specWithoutPalbase is the app before it has been linked: no environments
// directory exists yet, so the target cannot reference one.
func specWithoutPalbase(spec string) string {
	return strings.ReplaceAll(spec, "      - path: palbase/environments\n", "")
}

// e2eCheckout makes a checkout whose directory NAME is the local stack's group.
//
// `groupOf` falls back to the base name when a target carries no project field
// and `LookupLocalStack` reads the machine-wide registry by that group (D-009),
// so an app checkout carries a `local` environment only when it shares the name
// of the checkout that started one.
func e2eCheckout(t *testing.T) string {
	t.Helper()
	group := strings.TrimSpace(os.Getenv("PALBASE_E2E_LOCAL_GROUP"))
	if group == "" {
		t.Fatal("PALBASE_E2E_LOCAL_GROUP is required: name the checkout whose `palbase start` " +
			"registered the local stack — this gate needs two environments")
	}
	dir := filepath.Join(t.TempDir(), group)
	require.NoError(t, os.MkdirAll(dir, 0o755))
	return dir
}

func TestIOSLayoutSelectsOneEnvironment(t *testing.T) {
	ref := strings.TrimSpace(os.Getenv("PALBASE_E2E_PROJECT"))
	if ref == "" {
		t.Fatal("PALBASE_E2E_PROJECT is required: this gate measures a real link against a real project")
	}
	requireTool(t, "xcodegen")
	requireTool(t, "xcodebuild")

	bin := palbaseBinary(t)
	dir := e2eCheckout(t)

	require.NoError(t, os.MkdirAll(filepath.Join(dir, "Sources"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "Sources", "App.swift"),
		[]byte("import Foundation\n@main struct App { static func main() {} }\n"), 0o644))
	generateApp(t, dir, specWithoutPalbase(projectYAML))

	// THE SDK IS RESOLVED FIRST. `link` compiles the generator out of the
	// palbackend-ios checkout SwiftPM resolved, and refuses when there is none
	// — the same refusal a person gets before their first build.
	run(t, dir, nil, "xcodebuild", "-project", "E2EApp.xcodeproj", "-resolvePackageDependencies")

	// THE REAL LINK, through the binary, into a checkout that really has an
	// Xcode project — the precondition `link` refuses without.
	run(t, dir, nil, bin, "link", ref, "--platform", "ios")

	// …and now the environments exist, so the target can take them.
	generateApp(t, dir, projectYAML)

	envs := environmentsIn(t, dir)
	require.GreaterOrEqual(t, len(envs), 2,
		"this checkout carries one environment (%v); the selection gate needs two, or it "+
			"cannot tell a working selector from a constant", envs)

	// BOTH DIRECTIONS. One is not a measurement.
	for _, selected := range envs {
		derived := filepath.Join(t.TempDir(), selected)
		run(t, dir, nil, "xcodebuild",
			"-project", "E2EApp.xcodeproj", "-scheme", "E2EApp",
			"-sdk", "iphonesimulator", "-derivedDataPath", derived,
			// arm64 ONLY: the SDK ships an arm64 xcframework, and an x86_64 slice
			// the simulator build would otherwise ask for does not exist.
			"PALBASE_ENV="+selected, "ARCHS=arm64", "ONLY_ACTIVE_ARCH=NO",
			"CODE_SIGNING_ALLOWED=NO", "build")

		app := findApp(t, derived)

		// EXACTLY ONE plist in the bundle (NFR-003). Two environments' plists
		// both entering the app is the failure this pattern exists to stop, and
		// it does not announce itself — the app just reads whichever won.
		plists := findAll(t, app, "Palbase-Info.plist")
		require.Len(t, plists, 1, "the bundle carries %d Palbase-Info.plist: %v", len(plists), plists)

		// WHICH ENVIRONMENT IS IN THE APP. The flat plist carries no name — the
		// identity IS which plist got bundled — so the measurable distinguisher
		// is the address, read out of the built bundle and compared with what
		// the link wrote for that environment.
		got := strings.TrimSpace(run(t, dir, nil, "plutil", "-extract", "ios.base_url", "raw", plists[0]))
		want := readMarker(t, filepath.Join(dir, "palbase", "environments", selected, "ios-config.json"))
		require.Equal(t, want, got, "the built app points at %q while %s was selected", got, selected)

		// AND IT IS NOT THE OTHER ONE. Equality alone would pass if two
		// environments shared an address.
		for _, other := range envs {
			if other == selected {
				continue
			}
			require.NotEqual(t, readMarker(t, filepath.Join(dir, "palbase", "environments", other, "ios-config.json")), got,
				"the app built for %s points at %s", selected, other)
		}
	}
}

// TestIOSLayoutExclusionIsLoadBearing is the NEGATIVE CONTROL: remove the
// exclusion and the build must FAIL. A gate that has never seen its own failure
// reports "clean" on every run, including the runs where it is doing nothing.
func TestIOSLayoutExclusionIsLoadBearing(t *testing.T) {
	ref := strings.TrimSpace(os.Getenv("PALBASE_E2E_PROJECT"))
	if ref == "" {
		t.Fatal("PALBASE_E2E_PROJECT is required")
	}
	requireTool(t, "xcodegen")
	requireTool(t, "xcodebuild")

	bin := palbaseBinary(t)
	dir := e2eCheckout(t)
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "Sources"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "Sources", "App.swift"),
		[]byte("import Foundation\n@main struct App { static func main() {} }\n"), 0o644))

	// The same project WITHOUT the two selection lines.
	withoutExclusion := strings.ReplaceAll(projectYAML,
		"        EXCLUDED_SOURCE_FILE_NAMES: \"*/palbase/environments/*/*\"\n"+
			"        INCLUDED_SOURCE_FILE_NAMES: \"*/palbase/environments/$(PALBASE_ENV)/*\"\n", "")
	require.NotEqual(t, projectYAML, withoutExclusion, "the fixture's selection lines were not removed")
	generateApp(t, dir, specWithoutPalbase(withoutExclusion))
	run(t, dir, nil, "xcodebuild", "-project", "E2EApp.xcodeproj", "-resolvePackageDependencies")
	run(t, dir, nil, bin, "link", ref, "--platform", "ios")
	generateApp(t, dir, withoutExclusion)

	envs := environmentsIn(t, dir)
	require.GreaterOrEqual(t, len(envs), 2, "the negative control needs two environments, got %v", envs)

	cmd := exec.Command("xcodebuild", "-project", "E2EApp.xcodeproj", "-scheme", "E2EApp",
		"-sdk", "iphonesimulator", "-derivedDataPath", t.TempDir(),
		"PALBASE_ENV="+envs[0], "ARCHS=arm64", "ONLY_ACTIVE_ARCH=NO",
		"CODE_SIGNING_ALLOWED=NO", "build")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.Error(t, err, "two environments compiled into one target and the build SUCCEEDED:\n%s", out)
	require.True(t,
		strings.Contains(string(out), "Multiple commands produce") || strings.Contains(string(out), "used twice"),
		"the build failed for some other reason:\n%s", out)
}

func requireTool(t *testing.T, name string) {
	t.Helper()
	_, err := exec.LookPath(name)
	require.NoErrorf(t, err, "%s is required for this gate", name)
}

// environmentsIn lists the environment directories a link wrote.
func environmentsIn(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(dir, "palbase", "environments"))
	require.NoError(t, err, "the link wrote no environments")
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, e.Name())
		}
	}
	return out
}

// findApp returns the single .app the build produced.
func findApp(t *testing.T, derived string) string {
	t.Helper()
	apps := findAll(t, derived, "E2EApp.app")
	require.NotEmpty(t, apps, "no .app under %s", derived)
	return apps[0]
}

// findAll walks a tree for entries with an exact base name.
func findAll(t *testing.T, root, base string) []string {
	t.Helper()
	var out []string
	require.NoError(t, filepath.Walk(root, func(p string, _ os.FileInfo, err error) error {
		if err != nil {
			return nil // an unreadable corner of DerivedData is not this test's business
		}
		if filepath.Base(p) == base {
			out = append(out, p)
		}
		return nil
	}))
	return out
}
