package backend

// app_environments.go — an app holds EVERY environment, and the build picks one.
//
// The old model was one environment at a time: `palbase ios use staging`
// overwrote the config, so the app in your hands was whichever environment
// somebody linked last. Two consequences, both of which happened. A developer
// running against staging could not glance at production without re-linking and
// re-generating; and a TestFlight build could carry a staging address because a
// `use` ran before the archive.
//
// So the link downloads them all, the plist carries them all, and the BUILD
// CONFIGURATION decides. That is the one place in an Xcode project where a
// decision is already made per-build and cannot be forgotten at run time: Debug
// builds `local`, a TestFlight scheme builds `staging`, Release builds `main`.
//
// Each environment gets its own generated client, because environments serve
// different contracts — dev is usually ahead — and a client merged across them
// would compile calls that do not exist where the app is pointed. The xcconfig
// excludes the others, so exactly one is in the build.

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// appEnvironment is one environment as an app needs it.
type appEnvironment struct {
	AppID   string          `json:"app_id"`
	BaseURL string          `json:"base_url"`
	APIKey  string          `json:"api_key"`
	OAuth   json.RawMessage `json:"oauth,omitempty"`
}

// appEnvironments is what the CLI writes and the generator reads.
type appEnvironments struct {
	// Default is the environment a build with no PALBASE_ENV setting gets. It
	// is the safe one — production — because a build that forgot to say which
	// environment it wanted must not silently talk to a developer's laptop.
	Default      string                    `json:"default_environment"`
	Environments map[string]appEnvironment `json:"environments"`
}

// localEnvName is the environment every app checkout gets for free: the stack
// running on this machine.
const localEnvName = "local"

// generatedDir is where the per-environment clients live, committed.
const generatedDir = "Palbase/Generated"

func (a appEnvironments) names() []string {
	out := make([]string, 0, len(a.Environments))
	for name := range a.Environments {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// writeAppEnvironments records every environment for one platform.
func writeAppEnvironments(platform string, envs appEnvironments) (string, error) {
	dir := filepath.Join(nativeArtifactsDir, platform)
	if platform == "web" {
		dir = webArtifactsDir
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	blob, err := json.MarshalIndent(envs, "", "  ")
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "palbase-config.json")
	if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// specPath is where one environment's contract is committed.
func specPath(env string) string {
	return filepath.Join(nativeArtifactsDir, "openapi", env+".json")
}

// writeXcconfigs writes one build configuration per environment.
//
// Two settings each, and both are load-bearing. PALBASE_ENV names the
// environment and reaches the app through its Info.plist, which is where the SDK
// reads it — a build setting alone would be invisible at run time. The exclusion
// list keeps the OTHER environments' generated clients out of the compile, so
// "which endpoints exist" is decided by the same configuration that decides
// which address they are called at.
func writeXcconfigs(root string, envs appEnvironments, w io.Writer) error {
	dir := filepath.Join(root, "Palbase", "Config")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	names := envs.names()
	for _, name := range names {
		var excluded []string
		for _, other := range names {
			if other != name {
				excluded = append(excluded, fmt.Sprintf("*/%s/%s/*", filepath.Base(generatedDir), other))
			}
		}
		body := fmt.Sprintf(`// GENERATED by palbase link — do not edit.
//
// Build with this configuration and the app talks to the %q environment: the SDK
// reads PALBASE_ENV from the Info.plist, and only this environment's generated
// client is compiled.

PALBASE_ENV = %s
INFOPLIST_KEY_PALBASE_ENV = $(PALBASE_ENV)
EXCLUDED_SOURCE_FILE_NAMES = $(inherited) %s
`, name, name, strings.Join(excluded, " "))

		path := filepath.Join(dir, xcconfigName(name))
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(w, "wrote %s\n", path)
	}
	return nil
}

// xcconfigName is the file an Xcode configuration points at. Capitalised because
// that is how build configurations are named in every Xcode project ever
// created, and a file called `local.xcconfig` next to a configuration called
// `Local` reads as a different thing.
func xcconfigName(env string) string {
	if env == "" {
		return "Palbase.xcconfig"
	}
	return strings.ToUpper(env[:1]) + env[1:] + ".xcconfig"
}

// reportContractDrift says which endpoints one environment has and another does
// not.
//
// This is the question an app developer actually asks — "can I build this
// feature against production yet?" — and the answer is otherwise a compile error
// in a configuration they were not building at the time.
func reportContractDrift(specs map[string][]byte, w io.Writer) {
	if len(specs) < 2 {
		return
	}
	routes := map[string]map[string]bool{}
	for env, spec := range specs {
		routes[env] = pathsOf(spec)
	}

	names := make([]string, 0, len(routes))
	for env := range routes {
		names = append(names, env)
	}
	sort.Strings(names)

	// Compared against the DEFAULT environment rather than pairwise: production
	// is the baseline everything is eventually held to, and n² lines of
	// difference is a report nobody reads.
	base := names[0]
	if _, ok := routes[localEnvName]; ok && len(names) > 1 {
		// …unless one of them is the local stack, in which case the interesting
		// question is what the developer has that the deployed ones do not.
		for _, n := range names {
			if n != localEnvName {
				base = n
				break
			}
		}
	}

	for _, env := range names {
		if env == base {
			continue
		}
		var only, missing []string
		for path := range routes[env] {
			if !routes[base][path] {
				only = append(only, path)
			}
		}
		for path := range routes[base] {
			if !routes[env][path] {
				missing = append(missing, path)
			}
		}
		if len(only) == 0 && len(missing) == 0 {
			continue
		}
		sort.Strings(only)
		sort.Strings(missing)
		fmt.Fprintf(w, "\n%s and %s serve different contracts:\n", env, base)
		for _, path := range only {
			fmt.Fprintf(w, "  only in %s:  %s\n", env, path)
		}
		for _, path := range missing {
			fmt.Fprintf(w, "  not in %s:   %s\n", env, path)
		}
	}
}

// pathsOf reads an OpenAPI document's operations as "METHOD /path" strings.
func pathsOf(spec []byte) map[string]bool {
	var doc struct {
		Paths map[string]map[string]json.RawMessage `json:"paths"`
	}
	out := map[string]bool{}
	if json.Unmarshal(spec, &doc) != nil {
		return out
	}
	for path, methods := range doc.Paths {
		for method := range methods {
			switch strings.ToLower(method) {
			case "get", "post", "put", "patch", "delete", "query":
				out[strings.ToUpper(method)+" "+path] = true
			}
		}
	}
	return out
}

// gatherEnvironments collects every environment this app can be built against:
// the linked project, and the stack running on this machine.
//
// The local one is added WITHOUT a key when the stack is not up, rather than
// left out: an app whose Local configuration disappears because a container was
// stopped is an app that stops compiling for a reason nobody connects to the
// container. The entry says what to run instead.
func gatherEnvironments(ctx context.Context, target Target, key string, w io.Writer) (appEnvironments, map[string][]byte, error) {
	envs := appEnvironments{
		Default:      defaultEnvName(target),
		Environments: map[string]appEnvironment{},
	}
	specs := map[string][]byte{}

	primary := defaultEnvName(target)
	envs.Environments[primary] = appEnvironment{
		AppID:   projectAppID,
		BaseURL: target.URL,
		APIKey:  key,
	}
	cred, _, err := Credential(target.URL)
	if err != nil {
		return appEnvironments{}, nil, err
	}
	spec, err := fetchStackSpec(ctx, target, cred)
	if err != nil {
		return appEnvironments{}, nil, err
	}
	if err := writeSpec(primary, spec); err != nil {
		return appEnvironments{}, nil, err
	}
	specs[primary] = spec

	// The stack on this machine, when there is one and it is not already the
	// target.
	localURL := LookupLocalStack(groupOf(target))
	if localURL == "" || localURL == target.URL {
		return envs, specs, nil
	}

	localTarget := Target{URL: localURL, Local: true}
	localCred, _, credErr := Credential(localURL)
	if credErr != nil {
		envs.Environments[localEnvName] = appEnvironment{AppID: projectAppID, BaseURL: localURL}
		fmt.Fprintf(w, "local: %s is registered but this machine holds no credential for it — `palbase start`\n", localURL)
		return envs, specs, nil
	}
	localKey, keyErr := projectPublishableKey(ctx, localTarget)
	if keyErr != nil {
		// FR-057: the entry is written keyless, and the sequence that fills it
		// is named. A missing entry would be a build configuration that vanishes.
		envs.Environments[localEnvName] = appEnvironment{AppID: projectAppID, BaseURL: localURL}
		fmt.Fprintf(w, "local: %s did not answer — run `palbase start`, then `palbase spec` to fill it in\n", localURL)
		return envs, specs, nil
	}
	envs.Environments[localEnvName] = appEnvironment{
		AppID:   projectAppID,
		BaseURL: localURL,
		APIKey:  localKey,
	}
	if localSpec, err := fetchStackSpec(ctx, localTarget, localCred); err == nil {
		if err := writeSpec(localEnvName, localSpec); err != nil {
			return appEnvironments{}, nil, err
		}
		specs[localEnvName] = localSpec
	}
	return envs, specs, nil
}

// defaultEnvName is what the linked target's environment is called. A cloud
// project names it; a project you run yourself is its own single environment,
// and `main` is what every other surface calls that one.
func defaultEnvName(target Target) string {
	if target.Env != "" {
		return target.Env
	}
	return "main"
}

// groupOf is the project group a target belongs to, for finding its local stack
// in the machine register.
func groupOf(target Target) string {
	if target.Project != "" {
		return target.Project
	}
	root, err := os.Getwd()
	if err != nil {
		return ""
	}
	return filepath.Base(root)
}

func writeSpec(env string, spec []byte) error {
	path := specPath(env)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, spec, 0o644)
}

// generateForEnvironments emits one client per environment, and one plist for
// all of them.
func generateForEnvironments(ctx context.Context, envs appEnvironments, w io.Writer) error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	tool, err := ensureSwiftgenTool(root, w)
	if err != nil {
		// An app checkout without the SDK package resolved yet — the genuine
		// first link. Nothing generated, nothing stale to delete.
		fmt.Fprintf(w, "%v\n", err)
		return nil
	}

	for _, env := range envs.names() {
		spec := specPath(env)
		if !isRegularFile(spec) {
			continue
		}
		outDir := filepath.Join(root, generatedDir, env)
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}
		out := filepath.Join(outDir, "PalbaseGenerated.swift")
		cmd := exec.CommandContext(ctx, tool, "--openapi", spec, "--out-swift", out)
		cmd.Stderr = w
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("palbase-swiftgen (%s): %w", env, err)
		}
		fmt.Fprintf(w, "✓ wrote %s\n", out)
	}

	// One plist, every environment. The SDK reads PALBASE_ENV at boot and picks.
	plist := filepath.Join(root, generatedDir, "Palbase-Info.plist")
	args := []string{"--out-plist", plist}
	for _, platform := range []string{"ios", "macos"} {
		cfg := filepath.Join(nativeArtifactsDir, platform, "palbase-config.json")
		if isRegularFile(cfg) {
			args = append(args, "--"+platform+"-config", cfg)
		}
	}
	if len(args) == 2 {
		return nil // no Apple slot in this checkout
	}
	cmd := exec.CommandContext(ctx, tool, args...)
	cmd.Stderr = w
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("palbase-swiftgen (plist): %w", err)
	}
	fmt.Fprintf(w, "✓ wrote %s\n", plist)
	return nil
}

// readAppEnvironments reads back what the link wrote for one platform.
func readAppEnvironments(platform string) (appEnvironments, error) {
	dir := filepath.Join(nativeArtifactsDir, platform)
	if platform == "web" {
		dir = webArtifactsDir
	}
	raw, err := os.ReadFile(filepath.Join(dir, "palbase-config.json"))
	if os.IsNotExist(err) {
		return appEnvironments{}, nil
	}
	if err != nil {
		return appEnvironments{}, err
	}
	var envs appEnvironments
	if err := json.Unmarshal(raw, &envs); err != nil {
		return appEnvironments{}, fmt.Errorf("read the app's environments: %w", err)
	}
	return envs, nil
}
