package backend

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"
)

// `palbase build` GERÇEK BİR CHECKOUT'A TEK DOSYA YAZAR (FR-001, FR-005, FR-009,
// FR-018).
//
// Ölçülen şikâyet: backend kolu müşterinin checkout'una iki üretilmiş `.d.ts`
// (`palbase/palbase-env.d.ts` + kökte `palbase-stack.d.ts`) ve gizli bir
// `palbase/.gitattributes` bırakıyordu; ≤0.61.x'ten kalan `.palbase*` fosillerini
// ise HİÇBİR fiil toplamıyordu — kullanıcının diskinde 36 dizin / ~30 MB.
//
// Bu kapı parçaları değil ÜRETİM YOLUNU ölçer: `newBuildCmd`'in yaptığı gibi
// checkout'a girer ve `runBuild`'i çağırır. Proje CLI'ın kendi iskelesidir
// (`runInit`, paketlenmiş yerel SDK'dan), `node_modules`'ü gerçek bir `npm
// install`'dır ve git'e commit'lenmiştir; fosiller commit'ten SONRA, izlenmeyen
// hâlleriyle yerleştirilir. Karşılaştırma yol listesiyle değil İÇERİKLE yapılır:
// "yeni yol yok" demek yetmez, var olan bir dosyanın değiştirilmesi de FR-001
// ihlalidir.
//
// `node_modules` ve `.git` ölçülmez: biri paket yöneticisinin, öteki git'in
// alanı, ikisi de bu CLI'ın ürünü değil (`projectTree`'nin kuralı,
// generated_paths_test.go:144).
func TestBuildWritesExactlyOneFile(t *testing.T) {
	requiresRealToolchain(t)
	// ARAÇ YOKSA KIRMIZI, SESSİZ SKIP DEĞİL. Bu test FR-018'in tek kanıtı; araç
	// eksikken atlanan bir kanıt "kanıtlandı" diye okunur.
	for _, tool := range []string{"node", "npm", "npx", "bun", "git"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Fatalf("%s is not on PATH (%v) — TestBuildWritesExactlyOneFile runs `palbase build` end to end "+
				"on a real checkout and cannot be measured without it", tool, err)
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	dir := t.TempDir()
	tarball := packSDKForOneFileProof(t, ctx)

	// İSKELE, SONRA PAKETLENMİŞ BAYTLAR ÜSTÜNE — scaffold_typecheck_test.go:42-59
	// ile aynı sıra, aynı gerekçe: `runInit`'in ikinci kurulumu şablonun BİLDİRDİĞİ
	// sürümü registry'den çözer; soru ise BU SDK ile bu CLI'ın ne yazdığı.
	var initOut strings.Builder
	if err := runInit(ctx, dir, tarball, &initOut); err != nil {
		t.Fatalf("scaffold the checkout: %v\n%s", err, initOut.String())
	}
	install := exec.CommandContext(ctx, "npm", "install", "--no-audit", "--no-fund", tarball)
	install.Dir = dir
	if body, err := install.CombinedOutput(); err != nil {
		t.Fatalf("install the packed SDK over the scaffold: %v\n%s", err, body)
	}
	useTestParserCache(t)
	requireSingleFileRenderer(t, dir)

	// MAKİNE-YEREL DURUM geçici bir köke: build yığın adlarını orada ARAR
	// (FR-003) ve okuyabildiyse oraya YAZAR (FR-004). Geliştiricinin kendi
	// `~/.palbase`'i ne okunur ne yazılır, ve çalışan bir `palbase start` yığını
	// buraya sızmaz — `Resolve` önce yerel yığını sorar
	// (machine_state_test.go:45-47 ile aynı dikiş).
	prevHome := machineStateHome
	stateHome := t.TempDir()
	machineStateHome = func() (string, error) { return stateHome, nil }
	t.Cleanup(func() { machineStateHome = prevHome })

	commitFixtureCheckout(t, dir)

	// ≤0.61.x'in ve emekli yazıcıların bıraktıkları, İZLENMEYEN hâlleriyle.
	// Adlar SABİT DEĞİL LİTERAL: diskte duranlar eski sürümlerin yazdığı adlardır,
	// bir sabitin bugünkü değeri değil.
	fossils := map[string]string{
		".palbase/esm/controllers/controllers.js":                       "// GENERATED by a killed run\n",
		".palbase/project.json":                                         "{\"url\":\"https://stale.example\"}\n",
		".palbase-staged-controllers/modules/notes/notes.controller.ts": "// staged by 0.61.0\n",
		".palbase-build-controllers/modules/notes/notes.controller.ts":  "// left behind by a SIGKILL\n",
		".palbase-link-1344746409/.env.local":                           "PALBASE_API_KEY=stale\n",
		"palbase-stack.d.ts":                                            "declare module \"@palbase/backend/stack\" {}\nexport {};\n",
		"palbase/.gitattributes":                                        "** linguist-generated=true\n",
	}
	fossilRoots := []string{
		".palbase", ".palbase-staged-controllers", ".palbase-build-controllers",
		".palbase-link-1344746409", "palbase-stack.d.ts", "palbase/.gitattributes",
	}
	for rel, body := range fossils {
		mustWrite(t, dir, rel, body)
	}
	envFile := EnvTypesPath()

	before := checkoutDigests(t, dir)
	// NEGATİF KONTROL: ölçüm gizli girdileri ve fosilleri GÖREBİLİYOR mu, ve
	// beklenen tek dosya build'den ÖNCE yok mu? Göremeyen bir ölçüm her koşuda
	// "temiz" der.
	for _, root := range fossilRoots {
		if _, ok := before[root]; !ok {
			t.Fatalf("the snapshot cannot see the fossil %s — it would call any checkout clean", root)
		}
	}
	if _, ok := before[envFile]; ok {
		t.Fatalf("%s exists before the build, so its appearance would prove nothing", envFile)
	}

	// ÜRETİM YOLU: `newBuildCmd` çalışma dizinini okur ve onu verir.
	t.Chdir(dir)
	var out strings.Builder
	if err := runBuild(ctx, dir, &out); err != nil {
		t.Fatalf("palbase build: %v\n%s", err, out.String())
	}
	after := checkoutDigests(t, dir)

	var added, changed, removed []string
	for rel, sum := range after {
		prev, had := before[rel]
		switch {
		case !had:
			added = append(added, rel)
		case prev != sum:
			changed = append(changed, rel)
		}
	}
	for rel := range before {
		if _, ok := after[rel]; !ok {
			removed = append(removed, rel)
		}
	}
	sort.Strings(added)
	sort.Strings(changed)
	sort.Strings(removed)

	if len(added) != 1 || added[0] != envFile {
		t.Errorf("the build must add exactly one path, %s — it added %q\n%s", envFile, added, out.String())
	}
	if len(changed) > 0 {
		t.Errorf("the build changed files it does not own: %q\n%s", changed, out.String())
	}
	underFossil := func(rel string) bool {
		for _, root := range fossilRoots {
			if rel == root || strings.HasPrefix(rel, root+"/") {
				return true
			}
		}
		return false
	}
	gone := map[string]bool{}
	for _, rel := range removed {
		if !underFossil(rel) {
			t.Errorf("the build deleted %s, which no CLI ever wrote", rel)
		}
		gone[rel] = true
	}
	for _, root := range fossilRoots {
		if !gone[root] {
			t.Errorf("the fossil %s survived the build — nothing swept it (FR-009)", root)
		}
	}
	for rel := range after {
		for _, seg := range strings.Split(rel, "/") {
			if seg == ".palbase" || strings.HasPrefix(seg, ".palbase-") {
				t.Errorf("the checkout still carries %s after the build (FR-018)", rel)
				break
			}
		}
		if filepath.Base(rel) == "palbase-stack.d.ts" {
			t.Errorf("a second generated declaration file is in the checkout: %s", rel)
		}
	}

	raw, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(envFile)))
	if err != nil {
		t.Fatalf("read %s: %v\n%s", envFile, err, out.String())
	}
	body := string(raw)
	for _, block := range []string{`declare module "@palbase/backend/env"`, `declare module "@palbase/backend/stack"`} {
		if n := strings.Count(body, block); n != 1 {
			t.Errorf("%s carries %d × %s, want exactly one (FR-002)\n%s", envFile, n, block, body)
		}
	}
	if !strings.HasSuffix(strings.TrimRight(body, "\n"), "export {};") {
		t.Errorf("%s does not end with `export {};` — without it the file SHADOWS the package's types "+
			"instead of augmenting them (FR-005)\n%s", envFile, body)
	}
}

// packSDKForOneFileProof, packLocalSDK'nın (init_test.go:36) aynısıdır, tek
// farkla: kaynak yoksa ya da `npm pack` düşerse ATLAMAZ, adıyla düşer.
func packSDKForOneFileProof(t *testing.T, ctx context.Context) string {
	t.Helper()
	sdk := sdkSourceDir(t)
	if _, err := os.Stat(filepath.Join(sdk, "package.json")); err != nil {
		// SDK KAYNAĞI YANINDA DEĞİL — bu deponun CI'ında olan da budur
		// (`.github/workflows/ci.yml` yalnız CLI'ı checkout ediyor), yani burada
		// ölçülecek bir şey yok. ARAÇ eksikliğinden farklıdır ve yukarıda öyle
		// ayrılır: araç yoksa bu test adıyla DÜŞER. Paketleme DENENİP düşerse de
		// düşer (aşağıda) — atlanan tek hâl, paketlenecek kaynağın hiç olmaması.
		t.Skipf("the SDK source is not beside this checkout (%s): %v — FR-018 is measured against "+
			"the SDK this CLI builds with, and there is nothing here to pack", sdk, err)
	}
	dest := t.TempDir()
	cmd := exec.CommandContext(ctx, "npm", "pack", "--pack-destination", dest)
	cmd.Dir = sdk
	var stderr strings.Builder
	cmd.Stderr = &stderr
	body, err := cmd.Output()
	if err != nil {
		t.Fatalf("npm pack in %s: %v\n%s", sdk, err, stderr.String())
	}
	name := strings.TrimSpace(string(body))
	if i := strings.LastIndex(name, "\n"); i >= 0 {
		name = name[i+1:]
	}
	return filepath.Join(dest, name)
}

// requireSingleFileRenderer: paketlenen SDK tek dosyayı basabiliyor mu?
//
// `npm pack` `dist`'i OLDUĞU GİBİ paketler — SDK'nın package.json'ında prepack
// yok. `dist` birleşik renderer'dan eskiyse bu test CLI'ın bağlamasını değil
// SDK'nın derlenmemiş olmasını ölçerdi, ve kırmızısı yanlış yeri gösterirdi.
func requireSingleFileRenderer(t *testing.T, dir string) {
	t.Helper()
	probe := exec.Command("node", "-e", `process.stdout.write(require("@palbase/backend").makeEnvDts([]))`)
	probe.Dir = dir
	got, err := probe.CombinedOutput()
	if err != nil || !strings.Contains(string(got), `declare module "@palbase/backend/stack"`) {
		t.Fatalf("the @palbase/backend packed from %s renders no `@palbase/backend/stack` block (err: %v) — "+
			"its dist predates the single-file renderer; run `npm run build` there first. Measured "+
			"through it, this test would report the SDK's build rather than the CLI's wiring:\n%s",
			sdkSourceDir(t), err, got)
	}
}

// commitFixtureCheckout fikstürü gerçek bir git deposu yapar: süpürücü git'e
// "bu izleniyor mu" diye sorar (FR-010), ve soru ancak gerçek bir depoda bir
// şey ölçer. Kullanıcının global/sistem git yapılandırması (hook yolu,
// imzalama) fikstüre sızmaz; hiçbir global dosyaya yazılmaz.
func commitFixtureCheckout(t *testing.T, dir string) {
	t.Helper()
	for _, args := range [][]string{
		{"init", "-q"},
		{"add", "-A"},
		{"-c", "user.name=palbase-test", "-c", "user.email=test@palbase.invalid", "commit", "-q", "-m", "scaffold"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL="+os.DevNull, "GIT_CONFIG_NOSYSTEM=1")
		if body, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, body)
		}
	}
}

// checkoutDigests, projectTree'nin yol listesini her girdinin İÇERİĞİYLE
// döndürür: dizin "dir", sembolik bağ hedefiyle, dosya sha256 + izin bitleri.
func checkoutDigests(t *testing.T, dir string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, rel := range projectTree(t, dir) {
		p := filepath.Join(dir, rel)
		info, err := os.Lstat(p)
		if err != nil {
			t.Fatalf("stat %s: %v", rel, err)
		}
		key := filepath.ToSlash(rel)
		switch {
		case info.IsDir():
			out[key] = "dir"
		case info.Mode()&os.ModeSymlink != 0:
			target, _ := os.Readlink(p)
			out[key] = "link:" + target
		default:
			raw, err := os.ReadFile(p)
			if err != nil {
				t.Fatalf("read %s: %v", rel, err)
			}
			sum := sha256.Sum256(raw)
			out[key] = fmt.Sprintf("%s:%o", hex.EncodeToString(sum[:]), info.Mode().Perm())
		}
	}
	return out
}
