package backend

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// YARIDA KESİLEN BİR BUILD, PROJEDE ÜRÜN BIRAKIR — VE BİR SONRAKİ KOŞU ONU
// TOPLAMALI.
//
// `.palbase/{esm,jobs,hooks}` tek bir komut boyunca yaşar; dosyanın kendi yorumu
// söylüyor: "Nothing reads them across invocations, and leaving them behind is
// worse than litter". Temizlik `defer removeBundleOutput(dir)` ile yapılıyor
// (`plan.go`, `stack_push.go`) ve o defer SIGINT'te, SIGKILL'de, panikte KOŞMAZ.
// `.palbase-build-controllers` için ignore listesinin kendi gerekçesi bunu zaten
// itiraf ediyor: "removed on exit, LEFT BEHIND BY A SIGKILL".
//
// Aynı sınıf `link`'in hazırlık alanında canlıda ödendi: bir gün öncesinden
// kalmış bir kalıntı, içinde bir API anahtarıyla birlikte müşterinin deposunda
// duruyordu. Çare orada da buydu — sinyal yakalamak yetmez (SIGKILL
// yakalanamaz), her koşu BAŞTA eskiyi süpürmeli.
func TestReapRetiredArtifactsRemovesWhatAnOlderCLILeft(t *testing.T) {
	dir := t.TempDir()
	litter := []string{
		filepath.Join(dir, ".palbase", "esm", "controllers", "controllers.js"),
		filepath.Join(dir, ".palbase", "jobs", "manifest.json"),
		filepath.Join(dir, ".palbase", "hooks", "manifest.json"),
		filepath.Join(dir, stagedControllersDir, "a.ts"),
		filepath.Join(dir, deployStagingDir, "b.ts"),
		filepath.Join(dir, linkStagePrefix+"1344746409", ".env.local"),
	}
	for _, p := range litter {
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("stale\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	// `.palbase/project.json` ARTIK BURADA KORUNMUYOR. Süpürücü izlenmeyen
	// `.palbase`'i toptan siliyor (FR-010); korunan, git'in İZLEDİĞİ bir
	// sözleşme — o iddia `TestReapKeepsATrackedHiddenRootAndNamesIt`'te gerçek bir
	// git deposuyla ölçülüyor. Bu dizin bir depo değil, yani burada korunacak bir
	// şey de yok.

	reapRetiredArtifacts(dir)

	for _, p := range litter {
		if _, err := os.Stat(p); !os.IsNotExist(err) {
			t.Errorf("kalıntı süpürülmedi: %s", p)
		}
	}
}

// VE ÜRETİM YOLU ONU ÇAĞIRMALI. Test edilen ama çağrılmayan bir süpürücü, ölü
// koddur ve testi onu canlı gösterir.
//
// Gözlem noktası bilinçli: `*.module.ts` bulunmayan bir dizin, `buildStackArtifact`
// içinde HİÇBİR temizlik yapmadan erken dönüyor (`stack_bundle.go`, sources==0
// dalı). Yani bu yolda kalıntı ancak BAŞTAKİ süpürme sayesinde gidebilir.
func TestBuildSweepsBeforeItRefuses(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, ".palbase", "esm", "controllers", "controllers.js")
	if err := os.MkdirAll(filepath.Dir(stale), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(stale, []byte("// GENERATED by a killed run\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	_, _, err := buildStackArtifact(context.Background(), dir, t.TempDir(), &strings.Builder{})
	if err == nil {
		t.Fatal("modülsüz bir proje derlendi")
	}
	// NEGATİF KONTROL: beklediğimiz erken-red dalından döndüğümüzü doğrula,
	// yoksa test başka bir yolu ölçüyor olabilir.
	if !strings.Contains(err.Error(), "*.module.ts") {
		t.Fatalf("beklenen erken red değil: %v", err)
	}
	if _, statErr := os.Stat(stale); !os.IsNotExist(statErr) {
		t.Errorf("öldürülmüş bir koşunun bundle'ı duruyor: %s — bir sonraki push "+
			"onu gönderebilir", stale)
	}
}

// VE `link` DE SÜPÜRMEYİ ERKEN BİR REDDİN ÖNÜNE KOYMALI (FR-009).
//
// `link`in süpürmesi `newLinkStage`in içindeydi — platform doğrulamasının ve
// eski düzen kapısının ARKASINDA. O redlerden biriyle dönen her koşu, öldürülmüş
// bir koşunun `.palbase`ini checkout'ta bırakıyordu: süpürme tam da bir şeyin
// ters gittiği koşuda atlanıyordu.
//
// Gözlem noktası bilinçli: tanınmayan bir platform `runLink`in ilk
// doğrulamalarından biriyle, hiçbir ağ çağrısı yapmadan döner. Kalıntı bu yolda
// ancak BAŞTAKİ süpürme sayesinde gidebilir.
func TestSweepRunsBeforeLinksEarlyRefusals(t *testing.T) {
	inScratchCheckout(t)
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(dir, ".palbase", "esm", "controllers", "controllers.js")
	if err := os.MkdirAll(filepath.Dir(stale), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(stale, []byte("// GENERATED by a killed run\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	err = runLink(context.Background(),
		linkOpts{url: "https://unused.example", platforms: []string{"not-a-platform"}}, io.Discard)
	if err == nil {
		t.Fatal("tanınmayan bir platform link edildi")
	}
	// NEGATİF KONTROL: beklediğimiz erken red platform reddi. Eski düzen kapısı
	// ateşlendiyse izlenmeyen bir `.palbase` hâlâ reddediliyor demektir — o da
	// süpürmenin kapıdan SONRA koştuğunun başka bir yüzü.
	if strings.Contains(err.Error(), "retired layout") {
		t.Fatalf("izlenmeyen bir .palbase reddedildi, süpürülmedi: %v", err)
	}
	if !strings.Contains(err.Error(), "is not a platform this can link") {
		t.Fatalf("beklenen erken red değil: %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(dir, ".palbase")); !os.IsNotExist(statErr) {
		t.Errorf("öldürülmüş bir koşunun .palbase'i reddedilen link'ten sağ çıktı: %s", stale)
	}
}

// BAŞARILI BİR BUILD DE PROJEYE HİÇBİR ŞEY YAZMAMALI.
//
// Süpürme, öldürülmüş bir koşunun artığını topluyor — ama koşu SÜRERKEN ürünler
// hâlâ müşterinin projesinde duruyordu. Kullanıcının istediği bu değil: "defer
// değil, zaten hiç olmaması lazım".
//
// VE ÜRETİLDİKLERİ YERİN CHECKOUT OLMASI GEREKMİYOR. `push` onları tarball'a
// koyuyor (bulut ve self-host ayrımsız, ikisi de `BuildStackTarball`), ama tar
// onları geçici kökten de alabilir — müşterinin projesinde doğmalarının hiçbir
// sebebi yok.
func TestASuccessfulBuildWritesNoProductsIntoTheProject(t *testing.T) {
	requiresRealToolchain(t)
	dir := t.TempDir()
	buildableBackend(t, dir)

	// BUNDLE KÖKÜNÜ ÇAĞIRAN YARATIR VE ÖMRÜNE SAHİP OLUR: derleyicinin
	// müşterinin projesine yazmak için hiçbir sebebi yok, ve temizliğin sahibi
	// onu açan taraf olmalı.
	bundleRoot := t.TempDir()
	_, _, err := buildStackArtifact(context.Background(), dir, bundleRoot, io.Discard)
	if err != nil {
		t.Fatalf("build: %v", err)
	}

	// NEGATİF KONTROL: bundle GERÇEKTEN üretilmiş olmalı, yoksa bu test
	// "hiçbir şey yazılmadı" derken aslında hiç build olmadığını ölçer.
	produced := filepath.Join(bundleRoot, ".palbase", "esm", "controllers", "controllers.js")
	if _, err := os.Stat(produced); err != nil {
		t.Fatalf("bundle üretilmemiş: %v", err)
	}

	for _, sub := range bundleOutputDirs {
		p := filepath.Join(dir, ".palbase", sub)
		if _, err := os.Stat(p); !os.IsNotExist(err) {
			t.Errorf("başarılı bir build müşterinin projesine ürün yazdı: %s", p)
		}
	}
}

// KODSUZ BİR STACK PUSH'U SESSİZCE GİDEMEZ.
func TestAStackTarballRefusesAnEmptyBundleRoot(t *testing.T) {
	_, err := BuildStackTarball(t.TempDir(), "")
	if err == nil {
		t.Fatal("bundle kökü olmadan bir stack artefaktı üretildi — kodsuz giderdi")
	}
	if !strings.Contains(err.Error(), "no code") {
		t.Errorf("red, sonucu adlandırmıyor: %v", err)
	}
	// NEGATİF KONTROL: kök verilince kabul etmeli, yoksa kapı her şeyi reddeder.
	if _, err := BuildStackTarball(t.TempDir(), t.TempDir()); err != nil {
		t.Errorf("geçerli bir kök reddedildi: %v", err)
	}
}
