package backend

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// YARIDA KESİLEN BİR BUILD, PROJEDE ÜRÜN BIRAKIR — VE BİR SONRAKİ KOŞU ONU
// TOPLAMALI.
//
// `.palbase/{esm,jobs,hooks}` tek bir komut boyunca yaşar; dosyanın kendi yorumu
// söylüyor: "Nothing reads them across invocations, and leaving them behind is
// worse than litter". Temizlik `defer removeBundleOutput(dir)` ile yapılıyor
// (`plan.go`, `stack_push.go`) ve o defer SIGINT'te, SIGKILL'de, panikte KOŞMAZ.
// `.palbase-build-controllers` için ignore listesinin kendi gerekçesi bunu zaten
// itiraf ediyor: "removed on exit, LEFT BEHIND BY A SIGKILL".
//
// Aynı sınıf `link`'in hazırlık alanında canlıda ödendi: bir gün öncesinden
// kalmış bir kalıntı, içinde bir API anahtarıyla birlikte müşterinin deposunda
// duruyordu. Çare orada da buydu — sinyal yakalamak yetmez (SIGKILL
// yakalanamaz), her koşu BAŞTA eskiyi süpürmeli.
func TestSweepBuildLitterRemovesWhatAKilledRunLeaves(t *testing.T) {
	dir := t.TempDir()
	litter := []string{
		filepath.Join(dir, ".palbase", "esm", "controllers", "controllers.js"),
		filepath.Join(dir, ".palbase", "jobs", "manifest.json"),
		filepath.Join(dir, ".palbase", "hooks", "manifest.json"),
		filepath.Join(dir, stagedControllersDir, "a.ts"),
		filepath.Join(dir, deployStagingDir, "b.ts"),
	}
	for _, p := range litter {
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("stale\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	// SÖZLEŞME DOSYASI KALMALI: `.palbase/project.json` bir ÜRÜN değil, klonun
	// ihtiyacı olan sözleşme. Süpürücü `.palbase`'i toptan silseydi projeyi
	// kiracısından koparırdı.
	keep := filepath.Join(dir, ".palbase", "project.json")
	if err := os.WriteFile(keep, []byte(`{"url":"x"}`), 0o600); err != nil {
		t.Fatal(err)
	}

	sweepBuildLitter(dir)

	for _, p := range litter {
		if _, err := os.Stat(p); !os.IsNotExist(err) {
			t.Errorf("kalıntı süpürülmedi: %s", p)
		}
	}
	if _, err := os.Stat(keep); err != nil {
		t.Errorf("sözleşme dosyası silindi — proje kiracısından koparıldı: %v", err)
	}
}

// VE ÜRETİM YOLU ONU ÇAĞIRMALI. Test edilen ama çağrılmayan bir süpürücü, ölü
// koddur ve testi onu canlı gösterir.
//
// Gözlem noktası bilinçli: `*.module.ts` bulunmayan bir dizin, `buildStackArtifact`
// içinde HİÇBİR temizlik yapmadan erken dönüyor (`stack_bundle.go`, sources==0
// dalı). Yani bu yolda kalıntı ancak BAŞTAKİ süpürme sayesinde gidebilir.
func TestBuildSweepsBeforeItRefuses(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, ".palbase", "esm", "controllers", "controllers.js")
	if err := os.MkdirAll(filepath.Dir(stale), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(stale, []byte("// GENERATED by a killed run\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	_, _, err := buildStackArtifact(context.Background(), dir, &strings.Builder{})
	if err == nil {
		t.Fatal("modülsüz bir proje derlendi")
	}
	// NEGATİF KONTROL: beklediğimiz erken-red dalından döndüğümüzü doğrula,
	// yoksa test başka bir yolu ölçüyor olabilir.
	if !strings.Contains(err.Error(), "*.module.ts") {
		t.Fatalf("beklenen erken red değil: %v", err)
	}
	if _, statErr := os.Stat(stale); !os.IsNotExist(statErr) {
		t.Errorf("öldürülmüş bir koşunun bundle'ı duruyor: %s — bir sonraki push "+
			"onu gönderebilir", stale)
	}
}
