package backend

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// fixtureBackendPkg is a self-contained CJS stand-in for the project's installed
// @palbase/backend, faithful to the SDK contract this CLI depends on:
//   - column factories return builders carrying their definition on `._def`
//     (uuid/text/integer/boolean/timestamp/jsonb/enumType + the chainable
//     primaryKey/notNull/nullable/default/defaultRandom/defaultNow modifiers)
//   - defineSchema({ tables }) derives each TableDef.name from the object key
//   - makeEnvDts(schema) emits the exact `palbase-env.d.ts` text (golden-matched
//     below) — mirrors src/db/env-gen.ts
//
// The bundled db/schema.ts keeps @palbase/* external, so at eval time both the
// bundle's imports AND the env-gen bridge's `require('@palbase/backend')` resolve
// here via NODE_PATH. Keeping this verbatim with the SDK is what makes the test
// a real contract lock without a network install of the actual package.
const fixtureBackendPkg = `
'use strict';
function builder(type, def) {
  const _def = def || { type, nullable: false, primaryKey: false };
  return {
    _def,
    primaryKey() { _def.primaryKey = true; return builder(type, _def); },
    notNull() { _def.nullable = false; return builder(type, _def); },
    nullable() { _def.nullable = true; return builder(type, _def); },
    default(v) { _def.defaultValue = v; return builder(type, _def); },
    defaultRandom() { _def.defaultRandom = true; return builder(type, _def); },
    defaultNow() { _def.defaultNow = true; return builder(type, _def); },
    references(table, column) { _def.references = { table, column }; return builder(type, _def); },
    onDelete(a) { _def.onDeleteAction = a; return builder(type, _def); },
  };
}
const uuid = () => builder('uuid');
const text = () => builder('text');
const integer = () => builder('integer');
const boolean = () => builder('boolean');
const timestamp = () => builder('timestamp');
const jsonb = () => builder('jsonb');
function enumType(name, values) {
  const b = builder('enum');
  b._def.enumName = name;
  b._def.enumValues = values.slice();
  return b;
}
function defineSchema(input) {
  const tables = {};
  for (const name of Object.keys(input.tables)) {
    tables[name] = { name, columns: input.tables[name] };
  }
  return { tables };
}
function baseTsType(def) {
  switch (def.type) {
    case 'uuid': case 'text': case 'timestamp': return 'string';
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'jsonb': return 'unknown';
    case 'enum': {
      const values = def.enumValues || [];
      if (values.length === 0) return 'string';
      return values.map((v) => JSON.stringify(v)).join(' | ');
    }
    default: return 'unknown';
  }
}
function rowType(def) {
  const base = baseTsType(def);
  return def.nullable ? base + ' | null' : base;
}
function optionalOnInsert(def) {
  return def.nullable === true || def.defaultRandom === true || def.defaultNow === true || def.defaultValue !== undefined;
}
function tableBlock(table, indent) {
  const cols = Object.entries(table.columns);
  const rowLines = cols.map(([col, b]) => indent + '    ' + col + ': ' + rowType(b._def) + ';');
  const insertLines = cols.map(([col, b]) => {
    const def = b._def;
    const opt = optionalOnInsert(def) ? '?' : '';
    return indent + '    ' + col + opt + ': ' + rowType(def) + ';';
  });
  return [
    indent + table.name + ': {',
    indent + '  row: {',
    ...rowLines,
    indent + '  };',
    indent + '  insert: {',
    ...insertLines,
    indent + '  };',
    indent + '};',
  ].join('\n');
}
function makeEnvDts(schema) {
  const names = Object.keys(schema.tables);
  const blocks = names.map((name) => tableBlock(schema.tables[name], '    '));
  const body = blocks.length > 0 ? '\n' + blocks.join('\n') + '\n  ' : '';
  return '// AUTO-GENERATED by @palbase/backend — DO NOT EDIT.\n' +
    '// Regenerated from db/schema.ts on every ` + "`palbase serve`" + ` / deploy.\n' +
    '// Augments the @palbase/backend/env ` + "`Tables`" + ` interface so ` + "`Database.tables.*`" + `\n' +
    '// is typed with no import and no generic.\n' +
    '\n' +
    'declare module "@palbase/backend/env" {\n' +
    '  interface Tables {' + body + '}\n' +
    '}\n' +
    '\n' +
    'export {};\n';
}
module.exports = { uuid, text, integer, boolean, timestamp, jsonb, enumType, defineSchema, makeEnvDts };
`

// TestGenerateEnvTypes drives the real Go bridge end-to-end: a fixture project
// with a db/schema.ts (importing @palbase/backend) is esbuild-bundled, the
// embedded env-gen.js bridge evaluates it and calls makeEnvDts, and
// palbase-env.d.ts lands at the project root with the expected typed tables.
func TestGenerateEnvTypes(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	if _, err := exec.LookPath("npx"); err != nil {
		t.Skip("npx not on PATH")
	}

	root := t.TempDir()

	// Self-sufficient fixture: bundleSchemaTS shells out to `npx --yes esbuild`
	// from the project root — seed esbuild locally so npx resolves the fixture's
	// own bin (same trap as the serve tests: a fixture node_modules without
	// esbuild makes npx resolution host-dependent).
	seedEsbuild(t, root)

	// The project's installed @palbase/backend (resolved via NODE_PATH).
	mustWrite(t, root, "node_modules/@palbase/backend/package.json",
		`{"name":"@palbase/backend","version":"0.0.0-test","main":"index.js"}`)
	mustWrite(t, root, "node_modules/@palbase/backend/index.js", fixtureBackendPkg)

	// db/schema.ts — the documented `export default defineSchema(...)` form.
	mustWrite(t, root, "db/schema.ts", `
import { defineSchema, uuid, text, boolean, timestamp } from "@palbase/backend";

export default defineSchema({
  tables: {
    todos: {
      id: uuid().primaryKey().defaultRandom(),
      title: text().notNull(),
      done: boolean().default(false),
      created_at: timestamp().defaultNow(),
    },
  },
});
`)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	if err := generateEnvTypes(ctx, root, filepath.Join(root, "node_modules")); err != nil {
		t.Fatalf("generateEnvTypes: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(root, "palbase-env.d.ts"))
	if err != nil {
		t.Fatalf("read palbase-env.d.ts: %v", err)
	}

	want := "// AUTO-GENERATED by @palbase/backend — DO NOT EDIT.\n" +
		"// Regenerated from db/schema.ts on every `palbase serve` / deploy.\n" +
		"// Augments the @palbase/backend/env `Tables` interface so `Database.tables.*`\n" +
		"// is typed with no import and no generic.\n" +
		"\n" +
		"declare module \"@palbase/backend/env\" {\n" +
		"  interface Tables {\n" +
		"    todos: {\n" +
		"      row: {\n" +
		"        id: string;\n" +
		"        title: string;\n" +
		"        done: boolean;\n" +
		"        created_at: string;\n" +
		"      };\n" +
		"      insert: {\n" +
		"        id?: string;\n" +
		"        title: string;\n" +
		"        done?: boolean;\n" +
		"        created_at?: string;\n" +
		"      };\n" +
		"    };\n" +
		"  }\n" +
		"}\n" +
		"\n" +
		"export {};\n"

	if string(got) != want {
		t.Fatalf("palbase-env.d.ts mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}

	// The generated output must never leak the phantom ColumnBuilder type.
	if strings.Contains(string(got), "ColumnBuilder") {
		t.Fatalf("generated palbase-env.d.ts leaked ColumnBuilder:\n%s", got)
	}
}

// TestGenerateEnvTypesNoSchema asserts the no-op path: a project with no
// db/schema.ts must not error and must not write palbase-env.d.ts.
func TestGenerateEnvTypesNoSchema(t *testing.T) {
	root := t.TempDir()
	// A plain v1 project: endpoints/ but no db/schema.ts.
	mustWrite(t, root, "endpoints/hello/get.ts", "export default { handler: async () => ({}) };\n")

	if err := generateEnvTypes(context.Background(), root, filepath.Join(root, "node_modules")); err != nil {
		t.Fatalf("generateEnvTypes (no schema) must be a clean no-op, got: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "palbase-env.d.ts")); !os.IsNotExist(err) {
		t.Fatalf("palbase-env.d.ts must NOT exist when there is no db/schema.ts (stat err: %v)", err)
	}
}
