package backend

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// TEK DOSYA, TEK YAZICI (FR-001a, FR-002).
//
// Köprü şemayı ve yığının adlarını AYNI çağrıda render eder ve tek dosyayı
// yazar; içerik diskteki baytlarla aynıysa YAZMAZ.
//
// Köprü CLI'ın kendi embed.FS'inden okunur: ölçülen şey diskteki bir kardeş
// kopya değil, binary'yle GİDEN baytlardır.

// fixtureSingleFileBackendPkg stands in for an @palbase/backend whose
// makeEnvDts renders BOTH blocks between the markers the CLI splices on. It is
// strict where the real renderer is typed: a set that arrives as anything but
// an array throws, so a bridge that forwarded the wrong shape fails here the
// way it would fail the compiler.
var fixtureSingleFileBackendPkg = strings.NewReplacer(
	"__ENV_BEGIN__", palbaseEnvBlockBegin,
	"__ENV_END__", palbaseEnvBlockEnd,
	"__STACK_BEGIN__", palbaseStackBlockBegin,
	"__STACK_END__", palbaseStackBlockEnd,
).Replace(`
'use strict';
function set(name, v) {
  if (!Array.isArray(v)) throw new Error('names.' + name + ' must be an array, got ' + JSON.stringify(v));
  return v.map((x) => (x && typeof x === 'object' ? x.name : x)).sort();
}
function members(list) {
  return list.length ? '\n' + list.map((n) => '    ' + JSON.stringify(n) + ': true;').join('\n') + '\n  ' : '';
}
function makeEnvDts(schemas, names) {
  const s = names === undefined
    ? { secrets: [], flags: [], buckets: [], roles: [] }
    : { secrets: set('secrets', names.secrets), flags: set('flags', names.flags),
        buckets: set('buckets', names.buckets), roles: set('roles', names.roles) };
  return '// AUTO-GENERATED by @palbase/backend — DO NOT EDIT.\n\n' +
    '__ENV_BEGIN__\n' +
    'declare module "@palbase/backend/env" {\n  // schemas: ' + schemas.map((d) => d.name).join(',') + '\n}\n' +
    '__ENV_END__\n\n' +
    '__STACK_BEGIN__\n' +
    'declare module "@palbase/backend/stack" {\n' +
    '  interface Secrets {' + members(s.secrets) + '}\n' +
    '  interface Flags {' + members(s.flags) + '}\n' +
    '  interface Buckets {' + members(s.buckets) + '}\n' +
    '  interface Roles {' + members(s.roles) + '}\n' +
    '}\n' +
    '__STACK_END__\n\nexport {};\n';
}
module.exports = { makeEnvDts };
`)

// fixtureEnvOnlyBackendPkg is an @palbase/backend from before the single file:
// makeEnvDts takes one argument and renders the env block alone.
const fixtureEnvOnlyBackendPkg = `
'use strict';
module.exports = {
  makeEnvDts(schemas) {
    return 'declare module "@palbase/backend/env" {\n  // schemas: ' + schemas.length + '\n}\n\nexport {};\n';
  },
};
`

// bridgeProject lays out a project with the given @palbase/backend stand-in and
// one bundled schema — the shape the Go caller hands the bridge — and answers
// where the generated file goes. Its directory exists, as the Go caller makes
// sure it does.
func bridgeProject(t *testing.T, sdk string) (root, bundle, out string) {
	t.Helper()
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	root = t.TempDir()
	mustWrite(t, root, "node_modules/@palbase/backend/package.json",
		`{"name":"@palbase/backend","version":"0.0.0-test","main":"index.js"}`)
	mustWrite(t, root, "node_modules/@palbase/backend/index.js", sdk)
	mustWrite(t, root, "bundle/schema.js",
		`module.exports = { modules: [{ default: { name: "public", tables: {} } }], names: ["public"] };`+"\n")
	out = filepath.Join(root, filepath.FromSlash(EnvTypesPath()))
	require.NoError(t, os.MkdirAll(filepath.Dir(out), 0o755))
	return root, filepath.Join(root, "bundle", "schema.js"), out
}

type bridgeAnswer struct {
	Error     string `json:"error"`
	Unchanged bool   `json:"unchanged"`
}

// runEmbeddedBridge runs one devjs bridge the way the Go caller does: the script
// comes out of the CLI's embed.FS, NODE_PATH points at the project's
// node_modules, and the request arrives on stdin as JSON.
func runEmbeddedBridge(t *testing.T, script, root string, req map[string]any) bridgeAnswer {
	t.Helper()
	body, err := buildCheckFS.ReadFile("devjs/" + script)
	require.NoError(t, err)
	scriptPath := filepath.Join(t.TempDir(), script)
	require.NoError(t, os.WriteFile(scriptPath, body, 0o644))

	payload, err := json.Marshal(req)
	require.NoError(t, err)
	cmd := exec.Command("node", scriptPath)
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "NODE_PATH="+filepath.Join(root, "node_modules"))
	cmd.Stdin = bytes.NewReader(payload)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	require.NoErrorf(t, err, "%s: %s", script, stderr.String())

	var answer bridgeAnswer
	require.NoErrorf(t, json.Unmarshal(stdout, &answer), "%s answered no JSON: %s", script, stdout)
	return answer
}

// wireNames is StackNames exactly as the CLI puts it on the wire. Marshalled from
// the Go type itself, so a renamed JSON tag goes red here instead of rendering
// an empty set in a customer's file.
func wireNames(t *testing.T, names StackNames) map[string]any {
	t.Helper()
	raw, err := json.Marshal(names)
	require.NoError(t, err)
	var wire map[string]any
	require.NoError(t, json.Unmarshal(raw, &wire))
	return wire
}

func readText(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(raw)
}

func TestEnvGenBridgeRendersTheStackBlockFromNames(t *testing.T) {
	root, bundle, out := bridgeProject(t, fixtureSingleFileBackendPkg)

	answer := runEmbeddedBridge(t, "env-gen.js", root, map[string]any{
		"bundle_path": bundle,
		"out_path":    out,
		"names": wireNames(t, StackNames{
			Secrets: []string{"STRIPE_KEY"},
			Flags:   []string{"new_ui"},
			Buckets: []StackBucket{{Name: "avatars", Variants: []string{"thumb"}}},
			Roles:   []string{"admin"},
		}),
	})
	require.Empty(t, answer.Error)
	require.False(t, answer.Unchanged)

	got := readText(t, out)
	for _, want := range []string{
		"// schemas: public",
		`"STRIPE_KEY": true;`,
		`"new_ui": true;`,
		`"avatars": true;`,
		`"admin": true;`, // roller de TELDEN geçiyor
		palbaseEnvBlockBegin,
		palbaseStackBlockEnd,
	} {
		require.Containsf(t, got, want, "tek dosya %q taşımıyor:\n%s", want, got)
	}
	require.True(t, strings.HasSuffix(got, "export {};\n"), "dosya bir modül olarak kalmalı (FR-005)")
}

func TestEnvGenBridgeWithoutNamesRendersAnEmptyStackBlock(t *testing.T) {
	root, bundle, out := bridgeProject(t, fixtureSingleFileBackendPkg)

	answer := runEmbeddedBridge(t, "env-gen.js", root, map[string]any{"bundle_path": bundle, "out_path": out})
	require.Empty(t, answer.Error)

	got := readText(t, out)
	// Blok YİNE VAR — boş; korumayı Go tarafı yapar (FR-003a).
	require.Contains(t, got, palbaseStackBlockBegin)
	require.Contains(t, got, "interface Secrets {}")
	require.Contains(t, got, "interface Roles {}")
}

func TestEnvGenBridgeSkipsAnUnchangedFile(t *testing.T) {
	root, bundle, out := bridgeProject(t, fixtureSingleFileBackendPkg)
	request := func(flags ...string) map[string]any {
		return map[string]any{
			"bundle_path": bundle,
			"out_path":    out,
			"names":       wireNames(t, StackNames{Secrets: []string{}, Flags: flags, Buckets: []StackBucket{}, Roles: []string{}}),
		}
	}

	require.Empty(t, runEmbeddedBridge(t, "env-gen.js", root, request("new_ui")).Error)
	past := time.Now().Add(-2 * time.Hour).Truncate(time.Second)
	require.NoError(t, os.Chtimes(out, past, past))

	// AYNI İÇERİK: yazım yok, mtime tazelenmiyor (FR-001a).
	again := runEmbeddedBridge(t, "env-gen.js", root, request("new_ui"))
	require.Empty(t, again.Error)
	require.True(t, again.Unchanged, "aynı baytlar için köprü unchanged demeli")
	info, err := os.Stat(out)
	require.NoError(t, err)
	require.True(t, info.ModTime().Equal(past), "değişmeyen dosya yeniden yazıldı (mtime %s)", info.ModTime())

	// NEGATİF KONTROL: içerik değişince YAZILIR — "hiç yazma" bu testi geçemez.
	changed := runEmbeddedBridge(t, "env-gen.js", root, request("new_ui", "dark_mode"))
	require.Empty(t, changed.Error)
	require.False(t, changed.Unchanged)
	info, err = os.Stat(out)
	require.NoError(t, err)
	require.True(t, info.ModTime().After(past), "değişen içerik yazılmadı")
	require.Contains(t, readText(t, out), `"dark_mode": true;`)
}

func TestEnvGenBridgeRendersWithoutADatabase(t *testing.T) {
	root, _, out := bridgeProject(t, fixtureSingleFileBackendPkg)

	// db/ yok: paket yolu yok. Adlar yine tek dosyaya iner (FR-002, uç durum).
	// Yalnız Secrets dolu; öteki kümeler telde `null` — köprü onları boş küme
	// olarak iletmeli.
	answer := runEmbeddedBridge(t, "env-gen.js", root, map[string]any{
		"out_path": out,
		"names":    wireNames(t, StackNames{Secrets: []string{"STRIPE_KEY"}}),
	})
	require.Empty(t, answer.Error)

	got := readText(t, out)
	require.Contains(t, got, "// schemas: \n", "şema bildirmeyen proje boş bir Tables bloğu alır")
	require.Contains(t, got, `"STRIPE_KEY": true;`)
}

// ESKİ BİR SDK KÖPRÜYÜ DÜŞÜRMEZ — VERDİKT LANDER'INDIR (D-36, final-cli C1).
//
// Köprü bu redde bir noktada düşüyordu ("rendered no stack block … upgrade"),
// ve o red `palbase build`i BÜTÜNÜYLE düşürüyordu: bağlı her proje, eski bir
// major'da, `✗ DEPLOY WOULD FAIL: db/` ile — şemayla hiç ilgisi olmayan bir
// sürüm farkı, şemanın üstüne yıkılarak. Adların düşmesine karşı koruma
// landEnvTypes'ta ve ORADA ölçülüyor
// (TestPreserveStackBlockRefusesAnUnmarkedRenderEvenWithNames); köprü render
// ettiğini yazar, checkout'un dosyasına ne olacağına çağıran karar verir.
func TestEnvGenBridgeLeavesTheNarrowingVerdictToItsCaller(t *testing.T) {
	root, bundle, out := bridgeProject(t, fixtureEnvOnlyBackendPkg)

	answer := runEmbeddedBridge(t, "env-gen.js", root, map[string]any{
		"bundle_path": bundle,
		"out_path":    out,
		"names":       wireNames(t, StackNames{Secrets: []string{"STRIPE_KEY"}}),
	})
	require.Empty(t, answer.Error, "eski bir SDK köprüyü düşüremez — build'i düşüren red buydu")
	rendered := readText(t, out)
	require.Contains(t, rendered, "// schemas: 1", "şema yarısı yine render edilir")
	require.NotContains(t, rendered, `declare module "@palbase/backend/stack"`,
		"bu fikstür stack bloğu RENDER EDEMEZ — testin ölçtüğü durum bu")

	// NEGATİF KONTROL: ad verilmeyen aynı eski SDK da aynı şeyi yazar — köprünün
	// cevabı adların verilip verilmediğine göre DEĞİŞMEZ.
	plain := runEmbeddedBridge(t, "env-gen.js", root, map[string]any{"bundle_path": bundle, "out_path": out})
	require.Empty(t, plain.Error)
	require.Contains(t, readText(t, out), "// schemas: 1")
}

// TEK YAZICI, ÇÜNKÜ İKİNCİSİ ARTIK GÖMÜLÜ DEĞİL (D-36, final-cli I1).
//
// Burası eskiden emekli `stack-gen.js`'i koşturup "retired" cevabını ölçüyordu.
// O cevabı hiçbir müşteri göremezdi: betiği çağıran üretim yolu bu koşuda
// silindi, yani gömülü ağırlıktı — ve ulaşılabilirlik kapısı onu "kütüphane"
// sanıp hiç listelemiyordu (kapı da bu turda sıkılaştırıldı). Dosya silindi;
// ölçü artık "ikinci yazıcı YOK"tur, ve gömülü küme bunu kanıtlar.
func TestEnvGenBridgeIsTheOnlyWriter(t *testing.T) {
	entries, err := buildCheckFS.ReadDir("devjs")
	require.NoError(t, err)
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	require.NotEmpty(t, names)
	require.NotContains(t, names, "stack-gen.js",
		"emekli ikinci yazıcı hâlâ gömülü — hiçbir komut onu koşturmuyor")
	require.Contains(t, names, "env-gen.js", "tek yazıcı gömülü olmalı")

	// …ve eski dosyanın adı, onu ARAYAN bir yol olarak hiçbir yerde kalmadı:
	// gömülü kümede olmayan bir betiği okumak spawn hatası verirdi.
	_, err = buildCheckFS.ReadFile("devjs/stack-gen.js")
	require.Error(t, err, "silinen betik hâlâ okunabiliyor")
}
