package backend

// legacy_layout_tracked_test.go — THE RETIRED LAYOUT IS REFUSED ONLY WHERE A
// PERSON COMMITTED IT, AND WHAT THIS CLI LEFT BEHIND IS SWEPT.
//
// Two retirements meet here. The hidden root `.palbase` stops being a reason to
// refuse `link` unless git TRACKS a file under it (FR-010b) — an untracked one
// belongs to the sweeper (FR-010). And the two files older CLIs wrote beside the
// declaration — `palbase-stack.d.ts` at the checkout root and
// `palbase/.gitattributes` — are no longer written and are swept where they are
// found (FR-008, FR-011).

import (
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// FR-010b: THE REFUSAL FIRES ONLY FOR A TRACKED `.palbase`.
func TestLegacyHiddenRootIsRefusedOnlyWhenGitTracksIt(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	mustWrite(t, dir, ".palbase/project.json", `{"url":"x"}`)
	mustWrite(t, dir, "package.json", `{}`)

	// Not a repository: nothing here can have been committed.
	require.Empty(t, CarriesLegacyLayout(dir), "a .palbase in a directory git does not manage was refused")

	// A repository where a NEIGHBOUR is tracked and `.palbase` is not. A gate that
	// asked "does this repository track anything" would refuse here.
	gitCheckout(t, dir, "package.json")
	require.Empty(t, CarriesLegacyLayout(dir), "an untracked .palbase was refused — the sweeper owns it")

	// Tracked: refused, BY NAME.
	out, err := exec.Command("git", "-C", dir, "add", "--", ".palbase/project.json").CombinedOutput()
	require.NoError(t, err, "git add: %s", out)
	require.Equal(t, []string{".palbase"}, CarriesLegacyLayout(dir), "a tracked .palbase was not refused by name")
}

// FR-008, FR-011: THE ROOT STACK TYPES AND `palbase/.gitattributes` ARE SWEPT —
// COMMITTED OR NOT, because both were this CLI's product and never a person's
// (D-5). What this CLI writes today, and the checkout's own attributes, stay.
func TestLegacyStackTypesAndGitattributesAreSwept(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	mustWrite(t, dir, stackTypesFile, "// palbase-stack.d.ts — GENERATED by @palbase/backend. Do not edit.\nexport {};\n")
	mustWrite(t, dir, RootDir()+"/.gitattributes", "**/openapi.json linguist-generated=true -diff\n")
	mustWrite(t, dir, EnvTypesPath(), "export {};\n")
	mustWrite(t, dir, projectPath(), `{"url":"x"}`)
	mustWrite(t, dir, ".gitattributes", "*.png binary\n")
	gitCheckout(t, dir, stackTypesFile, RootDir()+"/.gitattributes", ".gitattributes", EnvTypesPath(), projectPath())

	kept := reapRetiredArtifacts(dir)

	require.Empty(t, kept, "a retired product was kept because git tracks it")
	require.NoFileExists(t, filepath.Join(dir, stackTypesFile), "the retired root stack types survived")
	require.NoFileExists(t, filepath.Join(dir, RootDir(), ".gitattributes"), "the retired palbase/.gitattributes survived")
	require.FileExists(t, filepath.Join(dir, filepath.FromSlash(EnvTypesPath())), "the one generated file was swept")
	require.FileExists(t, filepath.Join(dir, filepath.FromSlash(projectPath())), "the project's contract was swept")
	require.FileExists(t, filepath.Join(dir, ".gitattributes"), "the checkout's own .gitattributes was swept")
}

// FR-011: `link` WRITES NO `palbase/.gitattributes`, AND TAKES AN OLD ONE AWAY.
func TestLegacyLinkWritesNoGitattributes(t *testing.T) {
	inScratchCheckout(t)
	useStub(t, stubSwiftgen(t, filepath.Join(t.TempDir(), "argv")), nil)
	srv := stackServing(t, "pb_project_cPUBLISHABLE", nil)
	linkedAs(t, srv.URL, "a-credential")
	attributes := filepath.Join(RootDir(), ".gitattributes")

	require.NoError(t, runLink(context.Background(), linkOpts{url: srv.URL, platforms: []string{"ios"}}, io.Discard))
	require.NoFileExists(t, attributes, "`link` wrote palbase/.gitattributes")
	// NEGATIVE CONTROL: the link really ran and wrote into palbase/ — otherwise the
	// absence above measures a link that did nothing. Asked through the environment
	// the link RECORDED, never a literal: this checkout's environment is named by
	// the stack, and a test that spells one cannot see the value be wrong.
	envs, err := readAppEnvironments("ios")
	require.NoError(t, err)
	require.NotEmpty(t, envs.Default, "the link recorded no environment")
	require.FileExists(t, filepath.FromSlash(ConfigPath(envs.Default, "ios")),
		"the link wrote nothing, so the absence above measures nothing")

	// What an older link left behind: the next link takes it.
	require.NoError(t, os.WriteFile(attributes, []byte("**/openapi.json linguist-generated=true -diff\n"), 0o644))
	require.NoError(t, runLink(context.Background(), linkOpts{url: srv.URL, platforms: []string{"ios"}}, io.Discard))
	require.NoFileExists(t, attributes, "a retired palbase/.gitattributes survived a link")
}
