package backend

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// ERİŞİLEMEZ BİR YIĞIN TİPLERİ DARALTMAZ (FR-003a, NFR-003).
//
// Tek dosya iki bloğu birden taşıyor: şemanınki her koşuda yerelden render
// edilir, yığınınki ise ancak yığın (ya da bu makinenin önbelleği) cevap
// verdiğinde. Adlar hiç okunamadığında yeni render'ın BOŞ stack bloğunu
// yazmak, kod doğruyken derleyiciyi "kodun yanlış" dedirten bir hataya
// düşürür. O yüzden yalnız env işaretçileri arası değişir; `.d.ts`
// AYRIŞTIRILMAZ, iki ucu da bu ürün yazdığı için sınırlar bilinir.

// renderedEnvFile is the shape the renderer emits: a header, the env block and
// the stack block, each between its own markers, and `export {};` at the end.
func renderedEnvFile(envBody, stackBody string) string {
	return "// AUTO-GENERATED by @palbase/backend — DO NOT EDIT.\n\n" +
		palbaseEnvBlockBegin + "\n" +
		"declare module \"@palbase/backend/env\" {\n  interface Tables {" + envBody + "}\n}\n" +
		palbaseEnvBlockEnd + "\n\n" +
		palbaseStackBlockBegin + "\n" +
		"declare module \"@palbase/backend/stack\" {\n  interface Secrets {" + stackBody + "}\n}\n" +
		palbaseStackBlockEnd + "\n\nexport {};\n"
}

const (
	oldTables   = "\n    todos: { row: { id: string } };\n  "
	newTables   = "\n    notes: { row: { id: string } };\n  "
	filledStack = "\n    STRIPE_KEY: true;\n  "
)

func TestPreserveStackBlockKeepsTheStackBytes(t *testing.T) {
	existing := renderedEnvFile(oldTables, filledStack)
	// The render an unreachable stack produces: the schema is current, the stack
	// block is empty because nothing could be asked.
	fresh := renderedEnvFile(newTables, "")

	start, stop, err := markedSpan(fresh, palbaseEnvBlockBegin, palbaseEnvBlockEnd)
	require.NoError(t, err)

	got, err := preserveStackBlock(existing, fresh[start:stop])
	require.NoError(t, err)

	// (a) Şema TAZELENDİ.
	require.Contains(t, got, "notes: { row: { id: string } };")
	require.NotContains(t, got, "todos:")
	// (b) Stack bloğu BAYT OLARAK aynı.
	oldStart, oldStop, err := markedSpan(existing, palbaseStackBlockBegin, palbaseStackBlockEnd)
	require.NoError(t, err)
	newStart, newStop, err := markedSpan(got, palbaseStackBlockBegin, palbaseStackBlockEnd)
	require.NoError(t, err)
	require.Equal(t, existing[oldStart:oldStop], got[newStart:newStop],
		"stack bloğunun baytları değişemez — yığın okunamadı, daraltacak bilgi yok")
	require.Contains(t, got, "STRIPE_KEY: true;")
	// (c) Dosya hâlâ bir MODÜL: `export {}` düşerse augmentation gölgelemeye
	// döner (FR-005).
	require.True(t, strings.HasSuffix(got, "export {};\n"), "dosyanın kuyruğu da korunmalı:\n%s", got)
}

func TestPreserveStackBlockRefusesWhatItCannotBound(t *testing.T) {
	envBlock := palbaseEnvBlockBegin + "\nx\n" + palbaseEnvBlockEnd
	twoBegins := renderedEnvFile(oldTables, filledStack) + palbaseEnvBlockBegin + "\n"

	for _, c := range []struct {
		name     string
		existing string
		envBlock string
	}{
		{"the file carries no markers at all", "declare module \"@palbase/backend/env\" {}\nexport {};\n", envBlock},
		{"the file carries two env begins", twoBegins, envBlock},
		{"the file has no stack block", palbaseEnvBlockBegin + "\nx\n" + palbaseEnvBlockEnd + "\n", envBlock},
		{"the new block is not bounded", "\n" + envBlock, renderedEnvFile(newTables, "")},
		{"the new block carries a stack marker", renderedEnvFile(oldTables, filledStack),
			palbaseEnvBlockBegin + "\n" + palbaseStackBlockBegin + "\n" + palbaseEnvBlockEnd},
	} {
		t.Run(c.name, func(t *testing.T) {
			_, err := preserveStackBlock(c.existing, c.envBlock)
			require.Error(t, err, "sınırı bilinmeyen bir dosyaya yazmak yarım bir bildirim bırakır")
		})
	}
}

// The one thing a marker constant cannot answer for itself: whether the
// RENDERER writes it. The two live in two repositories with no compiler between
// them, so this reads the SDK's own source — and skips, saying which file it
// wanted, where that checkout is not beside this one.
func TestPreserveStackBlockMarkersAreTheRenderers(t *testing.T) {
	sdk := sdkSourceDir(t)
	var corpus string
	for _, rel := range []string{
		filepath.Join("src", "db", "env-gen.ts"),
		filepath.Join("src", "stack-gen.ts"),
	} {
		raw, err := os.ReadFile(filepath.Join(sdk, rel))
		if err != nil {
			t.Skipf("the SDK source is not beside this checkout: %v", err)
		}
		corpus += string(raw)
	}
	for _, marker := range []string{
		palbaseEnvBlockBegin, palbaseEnvBlockEnd, palbaseStackBlockBegin, palbaseStackBlockEnd,
	} {
		require.Containsf(t, corpus, marker,
			"no renderer writes %q — the CLI would splice on a boundary the generated file does not have", marker)
	}
}

// landFixture stages a fresh render in a build root and, when `existing` is not
// empty, a previously generated file in the checkout.
func landFixture(t *testing.T, existing, fresh string) (buildRoot, cwd, dest string) {
	t.Helper()
	buildRoot, cwd = t.TempDir(), t.TempDir()
	rel := filepath.FromSlash(EnvTypesPath())
	mustWrite(t, buildRoot, rel, fresh)
	if existing != "" {
		mustWrite(t, cwd, rel, existing)
	}
	return buildRoot, cwd, filepath.Join(cwd, rel)
}

func TestPreserveStackBlockThroughTheLander(t *testing.T) {
	fresh := renderedEnvFile(newTables, "")
	buildRoot, cwd, dest := landFixture(t, renderedEnvFile(oldTables, filledStack), fresh)

	var out bytes.Buffer
	unreachable := checkoutStackNames{Source: namesUnavailable, Why: errors.New("the stack could not be reached")}
	require.NoError(t, landEnvTypes(buildRoot, cwd, unreachable, &out))

	landed, err := os.ReadFile(dest)
	require.NoError(t, err)
	require.Contains(t, string(landed), "notes: { row: { id: string } };")
	require.Contains(t, string(landed), "STRIPE_KEY: true;", "checkout'taki stack bloğu boşaltılamaz")

	// İKİNCİ KOŞU, AYNI BAYTLAR: yazım yok ve mtime tazelenmiyor (FR-001a) —
	// değişmemiş bir dosyayı yeniden yazmak izleyicileri ve derleme
	// önbelleklerini boşuna uyandırır.
	past := time.Now().Add(-2 * time.Hour).Truncate(time.Second)
	require.NoError(t, os.Chtimes(dest, past, past))
	out.Reset()
	require.NoError(t, landEnvTypes(buildRoot, cwd, unreachable, &out))
	info, err := os.Stat(dest)
	require.NoError(t, err)
	require.True(t, info.ModTime().Equal(past), "değişmeyen dosya yeniden yazıldı (mtime %s)", info.ModTime())
	require.Contains(t, out.String(), "(unchanged)")
}

func TestPreserveStackBlockWritesAnEmptyBlockWhenThereIsNoFile(t *testing.T) {
	fresh := renderedEnvFile(newTables, "")
	buildRoot, cwd, dest := landFixture(t, "", fresh)

	var out bytes.Buffer
	require.NoError(t, landEnvTypes(buildRoot, cwd,
		checkoutStackNames{Source: namesUnavailable, Why: errors.New("this checkout is not linked to a stack")}, &out))

	landed, err := os.ReadFile(dest)
	require.NoError(t, err)
	require.Equal(t, fresh, string(landed), "daraltılacak bir bilgi yok: boş stack bloğu DOĞRU cevap")

	// …ve NEDEN boş olduğu tek satırda söylenir.
	var said string
	for _, line := range strings.Split(out.String(), "\n") {
		if strings.Contains(line, "EMPTY") {
			said = line
		}
	}
	require.NotEmpty(t, said, "boş bloğun sebebi söylenmedi:\n%s", out.String())
	require.Contains(t, said, "this checkout is not linked to a stack")
}

// NEGATİF KONTROL: adlar OKUNDUYSA render'ın stack bloğu KAZANIR. Yığından
// silinen bir secret'ın tipten de düşmesi gerekir — "her zaman koru" bunu
// imkânsız kılardı.
func TestPreserveStackBlockYieldsToNamesThatWereRead(t *testing.T) {
	fresh := renderedEnvFile(newTables, "\n    NEW_KEY: true;\n  ")
	buildRoot, cwd, dest := landFixture(t, renderedEnvFile(oldTables, filledStack), fresh)

	var out bytes.Buffer
	require.NoError(t, landEnvTypes(buildRoot, cwd,
		checkoutStackNames{Source: namesFromStack, Names: StackNames{Secrets: []string{"NEW_KEY"}}}, &out))

	landed, err := os.ReadFile(dest)
	require.NoError(t, err)
	require.Equal(t, fresh, string(landed))
	require.NotContains(t, string(landed), "STRIPE_KEY", "yığın cevap verdi: artık olmayan bir secret tipte kalamaz")
}

// A DOWNGRADED SDK MUST NOT COST THE NAMES, and a file that predates the single
// render has nothing to lose.
func TestPreserveStackBlockAndAnUnmarkedRender(t *testing.T) {
	unmarked := "declare module \"@palbase/backend/env\" {\n  interface Tables {" + newTables + "}\n}\n\nexport {};\n"

	t.Run("the file on disk has a stack block", func(t *testing.T) {
		existing := renderedEnvFile(oldTables, filledStack)
		buildRoot, cwd, dest := landFixture(t, existing, unmarked)

		var out bytes.Buffer
		require.NoError(t, landEnvTypes(buildRoot, cwd, checkoutStackNames{Source: namesUnavailable}, &out))

		landed, err := os.ReadFile(dest)
		require.NoError(t, err)
		require.Equal(t, existing, string(landed), "işaretsiz bir render dolu stack bloğunu düşüremez")
		require.Contains(t, out.String(), "not refreshed")
	})

	t.Run("the file on disk is unmarked too", func(t *testing.T) {
		buildRoot, cwd, dest := landFixture(t, "declare module \"@palbase/backend/env\" {}\nexport {};\n", unmarked)

		var out bytes.Buffer
		require.NoError(t, landEnvTypes(buildRoot, cwd, checkoutStackNames{Source: namesUnavailable}, &out))

		landed, err := os.ReadFile(dest)
		require.NoError(t, err)
		require.Equal(t, unmarked, string(landed), "korunacak stack bloğu yok — eski üretici ne yazıyorsa o iner")
	})
}
