package backend

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// What `selfhost link` must get right, and the two ways it could be dangerous.
//
// It handles both of a stack's keys, and they are not interchangeable: the
// secret one fetches the spec, the publishable one is written into a file that
// ships inside an app. Swapping them puts a key that bypasses row-level security
// on every phone that installs it — silently, because the app would work.

func TestKeysComeFromTheStacksEnvFile(t *testing.T) {
	dir := t.TempDir()
	env := filepath.Join(dir, ".env")
	if err := os.WriteFile(env, []byte(`# generated by palsvc --init-env
POSTGRES_PASSWORD=irrelevant
PALBASE_ANON_KEY=pb_selfhost_cPUBLISHABLE0000000000
PALBASE_SERVICE_ROLE_KEY=pb_selfhost_sSECRET00000000000000
LOCAL_JWT_PEM="-----BEGIN EC PRIVATE KEY-----
MHcCAQEE
-----END EC PRIVATE KEY-----"
`), 0o600); err != nil {
		t.Fatal(err)
	}

	anon, service, err := resolveSelfhostKeys(selfhostOpts{envFile: env})
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if anon != "pb_selfhost_cPUBLISHABLE0000000000" {
		t.Errorf("publishable key read as %q", anon)
	}
	if service != "pb_selfhost_sSECRET00000000000000" {
		t.Errorf("secret key read as %q", service)
	}
}

func TestKeysAreRefusedRatherThanGuessed(t *testing.T) {
	// No env file and no explicit keys: the command must say what it needs. The
	// alternative — carrying on with an empty key — reaches the stack and comes
	// back 401, which reads like the stack is broken.
	if _, _, err := resolveSelfhostKeys(selfhostOpts{}); err == nil {
		t.Fatal("linking with no keys at all was allowed")
	}

	dir := t.TempDir()
	env := filepath.Join(dir, ".env")
	if err := os.WriteFile(env, []byte("POSTGRES_PASSWORD=x\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	_, _, err := resolveSelfhostKeys(selfhostOpts{envFile: env})
	if err == nil {
		t.Fatal("an .env carrying no Palbase keys was accepted")
	}
	if !strings.Contains(err.Error(), "PALBASE_ANON_KEY") {
		t.Errorf("the error does not name what is missing: %v", err)
	}
}

func TestTheSpecIsFetchedWithTheSECRETKey(t *testing.T) {
	var seen string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != specPath {
			t.Errorf("asked for %s", r.URL.Path)
		}
		seen = r.Header.Get("apikey")
		w.Header().Set("content-type", "application/json")
		_, _ = w.Write([]byte(`{"openapi":"3.2.0","paths":{}}`))
	}))
	defer srv.Close()

	body, err := fetchSelfhostSpec(context.Background(), srv.URL, "pb_selfhost_sSECRET", false)
	if err != nil {
		t.Fatalf("fetch: %v", err)
	}
	if seen != "pb_selfhost_sSECRET" {
		t.Errorf("the spec was fetched with %q — the publishable key is refused there on purpose", seen)
	}
	if !strings.Contains(string(body), "openapi") {
		t.Errorf("body came back as %q", body)
	}
}

func TestARefusedKeySaysWhichKeyIsWanted(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte(`{"error":"service_role_required"}`))
	}))
	defer srv.Close()

	_, err := fetchSelfhostSpec(context.Background(), srv.URL, "pb_selfhost_cPUBLISHABLE", false)
	if err == nil {
		t.Fatal("a 403 was treated as a spec")
	}
	// The single most likely mistake is reaching for the key already in hand —
	// the publishable one — so the refusal names the other.
	if !strings.Contains(err.Error(), "SERVICE ROLE") {
		t.Errorf("the refusal does not say which key is wanted: %v", err)
	}
}

func TestNothingDeployedYetIsAStateNotAFailure(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write([]byte(`{"error":"spec_unavailable","error_description":"nothing is deployed yet"}`))
	}))
	defer srv.Close()

	_, err := fetchSelfhostSpec(context.Background(), srv.URL, "pb_selfhost_sSECRET", false)
	if err == nil {
		t.Fatal("an empty stack was treated as a spec")
	}
	// A stack that is up with nothing pushed to it is the normal first state, so
	// the message says what to do next rather than what went wrong.
	if !strings.Contains(err.Error(), "push a backend first") {
		t.Errorf("the message does not say what to do: %v", err)
	}
}

func TestTheAppConfigCarriesThePUBLISHABLEKey(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("content-type", "application/json")
		_, _ = w.Write([]byte(`{"openapi":"3.2.0","paths":{}}`))
	}))
	defer srv.Close()

	dir := t.TempDir()
	wd, _ := os.Getwd()
	t.Cleanup(func() { _ = os.Chdir(wd) })
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}

	opts := selfhostOpts{
		url:        srv.URL,
		anonKey:    "pb_selfhost_cPUBLISHABLE",
		serviceKey: "pb_selfhost_sSECRET",
		platforms:  []string{"ios"},
	}
	if err := runSelfhostLink(context.Background(), opts, &strings.Builder{}); err != nil {
		t.Fatalf("link: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(nativeArtifactsDir, "ios", "palbase-config.json"))
	if err != nil {
		t.Fatalf("no slot file: %v", err)
	}
	var entry pullSpecConfigEntry
	if err := json.Unmarshal(raw, &entry); err != nil {
		t.Fatal(err)
	}
	// THE assertion. This file is committed and ships inside the app; the secret
	// key bypasses row-level security, so it landing here would put a key that
	// reads every user's rows on every phone that installs the app — and the app
	// would work, which is what makes it silent.
	if entry.APIKey != "pb_selfhost_cPUBLISHABLE" {
		t.Errorf("the app's config carries %q", entry.APIKey)
	}
	if strings.Contains(string(raw), "SECRET") {
		t.Errorf("the secret key reached a committed file:\n%s", raw)
	}
	if entry.BaseURL != srv.URL {
		t.Errorf("base_url is %q", entry.BaseURL)
	}
	if entry.EnvironmentRef != selfhostRef || entry.AppID != selfhostRef {
		t.Errorf("identity is %q/%q", entry.AppID, entry.EnvironmentRef)
	}
}
