package backend

// stack_bundle.go — building what a push ships.
//
// A stack takes an ARTIFACT: the controllers bundled into one module. It does
// not build, and it cannot: bundling needs the
// project's own node_modules, and those live on the machine that wrote the code.
// So `palbase push` builds first, here, rather than shipping whatever a previous
// build happened to leave on disk — which is how somebody edits a controller,
// pushes, and deploys yesterday's code with today's commit message.
//
// The bundle is built with BUN, not esbuild, and that is not a preference: the
// runtime is Bun, so the code is built by the engine that will run it. Two
// bundlers means two opinions about how a decorator lowers, and the one that
// matters is the runtime's.
//
// DRIFT. The stack's own one-shot (`palsvc --push`) runs the same steps from
// runtime/scripts/bundle-controllers.sh in the palbase repository, so there are
// two implementations of one contract. What keeps them honest is the end of a
// push: the stack activates the artifact and REFUSES it unless the runtime is
// serving endpoints from it, so a bundle this file builds wrongly fails the push
// that built it rather than becoming a quiet 404 later.
import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// deployStagingDir is the staging tree older CLIs wrote into the project.
// Keep excluding it from archives and generated-file ignores for old leftovers.
// New builds stage outside the checkout.
const deployStagingDir = ".palbase-staged-controllers"

// bundleOutputDirs is what the bundler writes into the project: the compiled
// controllers and the two manifests.
//
// They exist for the length of ONE command. `push` builds them and tars them in
// the same process — a stack takes an artifact and cannot make one — and `plan`
// builds them to answer a question and never ships anything. Nothing reads them
// across invocations, and leaving them behind is worse than litter: the push
// path says out loud that shipping "whatever a previous build left on disk is
// how somebody edits a controller, pushes, and deploys yesterday's code under
// today's commit message".
var bundleOutputDirs = []string{"esm", "jobs", "hooks"}

// removeBundleOutput deletes them. Best effort by design: it runs after the
// artifact is already sent, and a failed cleanup has nowhere useful to go —
// reporting it would displace the result the person is waiting for.
func removeBundleOutput(dir string) {
	for _, sub := range bundleOutputDirs {
		_ = os.RemoveAll(filepath.Join(dir, ".palbase", sub))
	}
}

// bundleEntryHeader is the first line of the generated entry. It is asserted by
// a golden test: the entry's SHAPE is the contract between this bundler and the
// runtime that loads its output.
const bundleEntryHeader = "// GENERATED by `palbase push` — do not edit, do not commit."

// buildStackArtifact bundles a project's controllers and reports the buckets
// its @Upload routes name.
//
// It writes .palbase/esm/controllers/controllers.js and removes it if any step
// refuses — a failed build must leave NOTHING to deploy, because the
// alternative is a push that ships the last good bundle while its author
// believes they shipped the new one.
//
// It no longer evaluates config/: a backend's source carries code and schema,
// and nothing else. Settings live on the stack, put there by whoever changed
// them, so there is nothing here to read and nothing to send.
// Returns the @Upload buckets the routes name AND the ABI rung this bundle
// reaches — the second so a push can be refused against the stack's ceiling
// before the artifact is activated, rather than by the pod that already took it.
func buildStackArtifact(ctx context.Context, dir string, w io.Writer) ([]uploadUse, *int, error) {
	// No `controllers/` requirement: a module owns its classes wherever it lives,
	// and requiring a directory the module system does not use turned the
	// feature-folder layout into a push that could never happen. The precondition
	// that MATTERS is checked below — at least one `*.module.ts`.
	if _, err := exec.LookPath("bun"); err != nil {
		return nil, nil, fmt.Errorf("bun is not installed, and it is what builds a backend for this runtime " +
			"(https://bun.sh). The stack runs Bun, so the bundle is built by the engine that will run it")
	}

	sources, err := moduleSources(dir)
	if err != nil {
		return nil, nil, err
	}
	if len(sources) == 0 {
		return nil, nil, fmt.Errorf("no *.module.ts under %s — nothing would answer. A module is "+
			"what says which classes exist, who owns them and what they may reach, and a "+
			"project with none declares nothing at all (`palbase init` scaffolds one)", dir)
	}

	// STAGE FIRST: each controller's RETURN TYPE becomes a response schema.
	//
	// A route's response schema is derived from the method's TypeScript return
	// type, and a type exists only in the source — so something has to read it
	// and write it into the bundle (`recordReturn`, the SDK's own mechanism).
	// Bundling the raw tree skips that, and the artifact then serves a
	// specification whose every 200 response is `{}`. Measured on 2026-08-16:
	// a real app failed to compile against its own project's generated client,
	// because every response had become an opaque value.
	//
	// The staging is the SAME code `palbase build` runs (devjs/return_types.js,
	// devjs/throw_analysis.js), which is the same code the cloud's deploy stager
	// runs. One implementation of a contract that has to hold in three places.
	staged, err := stageControllers(ctx, dir, w)
	if err != nil {
		return nil, nil, err
	}
	defer func() { _ = os.RemoveAll(staged) }()

	// THE SCHEMA IS EVALUATED BEFORE ANYTHING IS SHIPPED (measured 2026-09-04).
	//
	// `db/` was READ by this function and never RUN: the declarations went into
	// the bundle verbatim, so a schema that cannot form its relation graph
	// shipped, applied its DDL, and refused at BOOT — inside `setSchema`, where
	// the cure is a push and the exit kills the process that accepts one. The
	// gate existed the whole time in `palbase build`, a command nobody is
	// required to run before pushing.
	//
	// The SAME evaluator `build` uses, not a second opinion about it: a gate
	// that imitates the real tool passes what the real tool rejects. It writes
	// nothing into the checkout — see validateSchemaDeclaration.
	//
	// AFTER stageControllers, and that placement is deliberate: this needs node,
	// and stageControllers needs it first with a message that says what node is
	// FOR here. Refusing above would have replaced a sentence about controllers'
	// return types with one about db/, for a person whose actual problem is that
	// they have no node at all. Nothing above touches the checkout, so the
	// refusal still arrives before any side effect.
	if err := validateSchemaDeclaration(ctx, dir, filepath.Join(dir, "node_modules")); err != nil {
		return nil, nil, fmt.Errorf("%s/ would refuse to boot: %w", SchemaDir, err)
	}

	esmDir := filepath.Join(dir, ".palbase", "esm", "controllers")
	if err := os.MkdirAll(esmDir, 0o755); err != nil {
		return nil, nil, err
	}
	out := filepath.Join(esmDir, "controllers.js")

	// Anything written from here on is removed when a gate refuses.
	built := false
	defer func() {
		if !built {
			// The manifests go with it: a refused build must leave NOTHING to
			// deploy, and a surviving jobs.manifest.json would let the next push
			// ship a schedule its bundle no longer carries.
			removeBundleOutput(dir)
		}
	}()

	if err := os.WriteFile(filepath.Join(dir, ".palbase", "esm", "package.json"),
		[]byte(`{"type":"module"}`+"\n"), 0o644); err != nil {
		return nil, nil, err
	}

	// The entry imports the STAGED module files: a module owns its controllers by
	// relative path, and those paths have to land inside the staged tree or the
	// injected return types are bypassed.
	stagedSources, err := moduleSources(staged)
	if err != nil {
		return nil, nil, err
	}
	if len(stagedSources) == 0 {
		return nil, nil, fmt.Errorf("staging dropped every module file — the bundle would declare nothing")
	}
	entry := filepath.Join(staged, ".controllers-entry.ts")
	entryBody, err := bundleEntry(dir, stagedSources)
	if err != nil {
		return nil, nil, err
	}
	if err := os.WriteFile(entry, []byte(entryBody), 0o644); err != nil {
		return nil, nil, err
	}

	// VERSION BEFORE BUNDLER: an SDK below what this CLI builds against fails
	// deep inside bun with a message about `undefined`, and the person is left
	// reading a stack trace instead of a sentence about versions.
	if err := checkSDKVersion(dir); err != nil {
		return nil, nil, err
	}

	// Bun labels bundled sources relative to its working directory. Building
	// from the stage keeps random temp directory names out of those labels and
	// gives identical sources an identical artifact on the same toolchain.
	if err := run(ctx, staged, "bun", "build", entry, "--target=bun", "--format=esm", "--outfile="+out); err != nil {
		return nil, nil, fmt.Errorf("the bundle did not build: %w", err)
	}

	// A bundle carrying no controller is the silent-404 class: it would deploy,
	// activate, and answer nothing. Refused here, where its author is watching.
	count, err := output(ctx, dir, "bun", "-e", countControllers, out)
	if err != nil {
		return nil, nil, fmt.Errorf("the bundle could not be inspected: %w", err)
	}
	n, convErr := strconv.Atoi(strings.TrimSpace(count))
	if convErr != nil || n == 0 {
		return nil, nil, fmt.Errorf("the bundle carries ZERO controllers — nothing would answer")
	}
	// WHICH BUN BUILT IT, said out loud.
	//
	// The bundle is byte-identical for a fixed toolchain — measured: two builds
	// of one tree produce one digest — so the digest a push activates is stable
	// per machine. Across machines it is not: nothing pins bun, and the digest is
	// content-addressed to the bytes it produced. Two people pushing the same
	// commit can therefore activate two digests, and `palbase deploys` shows two
	// entries for what is one version of the code.
	//
	// Printing the version does not close that, and pretending otherwise with a
	// pin would break every machine whose bun is a patch ahead. What it closes is
	// the part that actually costs time: "why is my digest different from yours"
	// is answerable at a glance instead of by bisecting two laptops.
	fmt.Fprintf(w, "built %d controller file(s) → %d controller(s)  [bun %s]\n", len(sources), n, bunVersion(ctx, dir))

	// WHAT THIS BUNDLE WOULD SERVE, read from the container it would build.
	//
	// A job, a webhook and a hook fail SILENTLY when they are missing — the
	// push-activation gate asks whether endpoints answer, and all three are
	// invisible to it. So they are read out of the built bundle, and the Go
	// half's schedule manifest is written from the same read, before anything
	// is packed.
	surfaces, err := readSurfaces(ctx, dir, out)
	if err != nil {
		return nil, nil, err
	}
	if err := writeDefinitionManifests(ctx, dir, surfaces, w); err != nil {
		return nil, nil, err
	}
	if len(surfaces.Webhooks) > 0 {
		fmt.Fprintf(w, "bundled %d webhook(s) → /webhooks/{%s}\n",
			len(surfaces.Webhooks), strings.Join(surfaces.Webhooks, ", "))
	}
	if len(surfaces.Hooks) > 0 {
		fmt.Fprintf(w, "bundled hook(s) → %s\n", strings.Join(surfaces.Hooks, ", "))
	}

	// @Upload names a bucket that must EXIST, and only the bundle knows which
	// names it uses — so they are read out here and checked against the stack by
	// whoever has one. A typo caught then names the bucket; caught later it is a
	// 404 somebody debugs from a phone.
	uses, err := readUploadBuckets(ctx, dir, out)
	if err != nil {
		return nil, nil, err
	}

	// The project's own tests, bundled so they can travel. A deploy runs them
	// against the release it just built, in a container that has no node_modules
	// — so the resolution happens here, where they are.
	if err := bundleTests(ctx, dir, w); err != nil {
		return nil, nil, err
	}

	built = true
	return uses, surfaces.AbiGeneration, nil
}

// testsDir is where a project keeps the suites a deploy runs, and
// bundledTestsDir is where their build lands. The artifact collects everything
// under .palbase/esm, so putting them there is what makes them travel.
const (
	testsDir        = "tests"
	bundledTestsDir = ".palbase/esm/tests"
)

// bundleTests builds each *.test.ts into a self-contained module.
//
// ONE BUNDLE PER SUITE, not one for all of them: `bun test` reports per file,
// and a single blob would collapse every suite into one name in the output a
// person reads when their deploy is refused.
//
// Only *.test.* files become suites. A helper beside them is pulled IN by the
// suite that imports it; emitted as its own file it would be run, report zero
// tests, and read as a suite that silently does nothing.
func bundleTests(ctx context.Context, dir string, w io.Writer) error {
	root := filepath.Join(dir, testsDir)
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil // A project with no tests is a legitimate project.
	}

	var suites []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !isTestSource(name) {
			continue
		}
		suites = append(suites, filepath.Join(root, name))
	}
	if len(suites) == 0 {
		return nil
	}
	sort.Strings(suites)

	outDir := filepath.Join(dir, filepath.FromSlash(bundledTestsDir))
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// bun:test and node:test are the RUNNER's, not the bundle's. Inlining them
	// would give each suite its own copy of a registry the runner owns, and the
	// run would report zero tests while every file executed.
	args := append([]string{"build"}, suites...)
	args = append(args, "--target=bun", "--format=esm", "--outdir="+outDir,
		"--external=bun:test", "--external=node:test", "--external=node:assert")
	if err := run(ctx, dir, "bun", args...); err != nil {
		return fmt.Errorf("the tests did not build: %w", err)
	}
	fmt.Fprintf(w, "bundled %d test suite(s)\n", len(suites))
	return nil
}

func isTestSource(name string) bool {
	return strings.HasSuffix(name, ".test.ts") || strings.HasSuffix(name, ".test.js") ||
		strings.HasSuffix(name, ".test.mts") || strings.HasSuffix(name, ".test.mjs")
}

// controllerClassRe finds the class a `@Controller(...)` decorates. It tolerates
// the decorator's own arguments (one level of nested parens), further
// decorators between it and the class, and `export` / `default` / `abstract`.
//
// A regex rather than a parser because the ONLY consumer fails closed: a miss
// leaves the bundle exactly as it was, and a wrong name renames nothing because
// the value has to be the bundled name minus a numeric suffix.
var controllerClassRe = regexp.MustCompile(
	`@Controller\s*\((?:[^()]|\([^()]*\))*\)\s*(?:@[\w$.]+\s*\((?:[^()]|\([^()]*\))*\)\s*)*(?:export\s+)?(?:default\s+)?(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)`)

// controllerClassNames reads the controller class names OUT OF THE SOURCES, in
// the order the bundle will register them: file by file, declaration by
// declaration. A file that cannot be read contributes nothing, which is the
// fail-closed reading — see the block in bundleEntry that consumes this.
func controllerClassNames(sources []string) []string {
	var names []string
	for _, src := range sources {
		raw, err := os.ReadFile(src)
		if err != nil {
			continue
		}
		for _, m := range controllerClassRe.FindAllStringSubmatch(string(raw), -1) {
			names = append(names, m[1])
		}
	}
	return names
}

// moduleSources lists a project's MODULE files, recursively, in a stable order.
//
// One glob, and this is it. There used to be four — controllers/, jobs/,
// webhooks/, hooks/ — and each was a second declaration the module system never
// saw. Measured: @Job, @Webhook and @Hook register NOTHING (only @Controller
// does), so a class carrying @Job outside jobs/ never ran, and one inside it ran
// whether or not any module listed it.
//
// A module lives beside the domain it owns rather than in a directory this
// bundler names, so the walk is recursive; node_modules and build output are not
// source and are skipped by name (node_modules is often a symlink, for which
// IsDir() is false).
func moduleSources(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() || name == "node_modules" || name == "dist" || name == ".git" {
			if path != root && (name == "node_modules" || name == "dist" || name == ".git" ||
				strings.HasPrefix(name, ".palbase")) {
				if d.IsDir() {
					return filepath.SkipDir
				}
				// SkipDir on a symlink skips its remaining siblings as well.
				return nil
			}
			return nil
		}
		if strings.HasSuffix(name, ".module.ts") {
			out = append(out, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// bundleEntry is the module the bundler starts from.
//
// It re-exports the SDK's request-scope hooks and the SDK namespace beside the
// controllers so the bundle and the runtime share ONE module instance: two
// instances would each get their own AsyncLocalStorage, and the request scope
// would silently not reach a handler.
//
// Controllers are imported for their SIDE EFFECT and never named — @Controller
// records the class as it decorates it, so a controller needs no export at all.
func bundleEntry(dir string, sources []string) (string, error) {
	var b strings.Builder
	b.WriteString(bundleEntryHeader + "\n")
	// buildModuleClients RIDES THE SAME SEAM, and leaving it out is not cosmetic:
	// the runtime builds this project's module clients from the BUNDLE's SDK copy
	// and REFUSES TO BOOT a bundle that does not re-export it. A bundle without
	// this line is a deploy that does not come up.
	//
	// There are two bundlers — this one and runtime/scripts/bundle-controllers.sh
	// in the palbase repository — and they must emit the same seam. They did not,
	// for one release: the shell one gained this symbol and this one did not.
	b.WriteString(`export { __runWithRuntime, __requestALS, __getRuntime, buildModuleClients } from "@palbase/backend";` + "\n")
	b.WriteString(`import * as SDK from "@palbase/backend"; export { SDK };` + "\n")
	for _, src := range sources {
		fmt.Fprintf(&b, "import %q;\n", src)
	}
	// EVERY SCHEMA THE DIRECTORY DECLARES.
	//
	// It used to carry the public file alone, because `setSchema` took ONE
	// declaration and an array would have been read as empty. `setSchema` takes
	// the SET now, so the sibling schemas — planned and applied by the deploy,
	// which has always read the directory — finally reach the runtime that has
	// to resolve their tables.
	//
	// ReadSchemaSources is the same reader the deploy rail uses, sorted the same
	// way. THE TWO BUNDLERS CHANGE TOGETHER (see bundle-controllers.sh): they
	// drifted once over `buildModuleClients` and the drift lasted a release.
	//
	// ONLY "no declaration" IS OPTIONAL — every other failure is reported.
	//
	// `err == nil` here would have swallowed the retired layout, a db/ with no
	// public file, and an unreadable directory alike, and produced a bundle with
	// NO SCHEMA and no complaint: the project's typed `.tables` surface would
	// come back empty at runtime with nothing anywhere naming the cause. That is
	// the same silence the shell bundler just stopped doing, and generateEnvTypes
	// in this package already gets it right.
	declared, err := ReadSchemaSources(dir)
	switch {
	case errors.Is(err, ErrNoSchema):
		// A project with no declaration still bundles, like channels.ts.
	case err != nil:
		return "", fmt.Errorf("read the schema declaration: %w", err)
	default:
		refs := make([]string, 0, len(declared))
		for i, src := range declared {
			fmt.Fprintf(&b, "import __schema%d from %q;\n", i, filepath.Join(dir, src.Path()))
			refs = append(refs, fmt.Sprintf("__schema%d", i))
		}
		fmt.Fprintf(&b, "export const schemas = [%s];\n", strings.Join(refs, ", "))
	}
	// CHANNELS TRAVEL THE SAME WAY, and for a sharper reason than the schema.
	//
	// `defineChannels` writes its declaration onto a globalThis symbol as the
	// module is evaluated, and the runtime reads this EXPORT first, falling back
	// to that symbol. Nothing else in a project imports channels.ts — it is not
	// a controller, a job, a webhook or a hook — so without this line the file
	// is not in the bundle at all, neither path finds a declaration, and the
	// table ships empty.
	//
	// An empty table is not a missing feature: undeclared channels are REFUSED,
	// fail-closed by design. So a project whose channels.ts never shipped has
	// every join answered `unauthorized` while the file sits in plain sight and
	// the deploy reports success. That is `jobs = []` again — same silence, same
	// class — and it is why the three lines below exist at all.
	//
	// It cannot live under config/: nothing evaluates that directory.
	if channels := filepath.Join(dir, "channels.ts"); fileExists(channels) {
		fmt.Fprintf(&b, "import __channels from %q; export const channels = __channels;\n", channels)
	}
	// THE APPLICATION'S DEFAULT AUTH, on the same terms and for the same reason.
	//
	// `defineDefaultAuth` is a call at module scope: it writes the application
	// ring of the auth cascade (route → controller → application → `true`) onto
	// a globalThis symbol as its file is evaluated. Nothing else in a project
	// imports that file — it is not a controller, a job, a webhook or a hook —
	// so without this line it is not in the bundle, is never evaluated, and the
	// declaration is simply NOT THERE.
	//
	// The cascade then falls through to its terminal `true`, and the direction
	// of that failure is the dangerous one: an application declaring
	// `{ verifiedEmail: true }` TIGHTENS the terminal default, so losing the
	// declaration leaves every route open to any signed-in user — the file in
	// plain sight, the deploy reporting success, nothing saying so. Same silence
	// as `jobs = []` and as the channels table that shipped empty.
	//
	// SIDE EFFECT, never named: the declaration is a call and not a value, so —
	// unlike channels — there is nothing to export. It only has to be evaluated,
	// and it is evaluated here, before the module body reads the registry.
	if auth := filepath.Join(dir, "auth.ts"); fileExists(auth) {
		fmt.Fprintf(&b, "import %q;\n", auth)
	}
	// Read AFTER the imports above have run — ESM evaluates every import before
	// the module body, so every decorator has fired by this line.
	// THE BUNDLER DOES NOT GET TO NAME THE PUBLIC API.
	//
	// Every controller lands in ONE bundle, and a bundler MUST rename duplicate
	// top-level identifiers to keep them apart: two files both declaring `class
	// PalaiController` become `PalaiController` and `PalaiController2`. That
	// rename is not cosmetic — `extract_meta.js` derives the dotted-operationId
	// NAMESPACE from `Ctrl.name`, so the shipped API surface ends up chosen by
	// the bundler's dedup counter, and its numbers follow bundle ORDER: adding
	// one file renumbers the others and every client's generated code shifts
	// under it.
	//
	// Ölçüldü 25.08.2026 (palai-cloud, canlı): on bir dosya da `PalaiController`
	// diyordu ve dağıtılan sözleşme `palai` + `palaiController2..11` olarak
	// bölünmüştü. Hiçbir adım hata vermedi; yalnız uygulama kendi backend'ine
	// karşı derlenmez oldu.
	//
	// `--keep-names` BUNU KAPSAMAZ: o minification'a karşıdır, iki ayrı
	// tanımlayıcının tekilleştirilmesine değil (ölçüldü, bun 1.3.9: bayrak
	// açıkken de yeniden adlandırıyor).
	//
	// The names come from the SOURCE, read here rather than from the bundle,
	// because a controller NEED NOT BE EXPORTED — the decorator registers it and
	// the entry imports the file for its side effect alone. Registration order
	// is import order, which is this list's order, so the table lines up
	// position by position.
	//
	// FAILS CLOSED. A name is restored only when the bundled one is exactly the
	// source name followed by digits — the bundler's own pattern. If this table
	// ever drifts from what the bundle registered, nothing is renamed and the
	// behaviour is what it was before this block existed.
	//
	// Two controllers that genuinely share a class name then share a namespace,
	// which is what the source says; a real clash between their METHOD names is
	// still refused, loudly, by the operationId gate in the runtime's generator.
	if names := controllerClassNames(sources); len(names) > 0 {
		blob, _ := json.Marshal(names)
		fmt.Fprintf(&b, `{
  const __want = %s;
  const __regs = SDK.getRegisteredControllers();
  for (let __i = 0; __i < __regs.length && __i < __want.length; __i++) {
    const __c = __regs[__i], __w = __want[__i];
    if (!__w || typeof __c !== "function" || __c.name === __w) continue;
    if (!__c.name.startsWith(__w) || !/^[0-9]+$/.test(__c.name.slice(__w.length))) continue;
    Object.defineProperty(__c, "name", { value: __w, configurable: true });
  }
}
`, blob)
	}
	b.WriteString("export const controllers = SDK.getRegisteredControllers();\n")
	b.WriteString("export const getRegisteredControllers = SDK.getRegisteredControllers;\n")
	b.WriteString("export const resources = [];\n")

	// THE THREE SURFACES THAT TRAVEL BY NAME, unlike controllers.
	//
	// @Controller records its class into a global registry as it decorates it,
	// so a controller needs no export and the entry imports it for the side
	// effect alone. @Job, @Webhook and @Hook do NOT: each stamps metadata onto
	// the class and nothing collects it. The runtime reads these three exports
	// — collectJobs, mountWebhooks, collectHooks — so the class has to reach
	// them by name or the surface never exists.
	//
	// EACH OF THESE LINES WAS ONCE A HARDCODED `[]`, AND EACH COST THE SAME.
	// `webhooks = []` was fixed on 2026-08-25 after a project's
	// `webhooks/stripe.ts` compiled into the bundle and was then declared
	// absent: the URL answered 404 while the deploy said "successful".
	// `jobs = []` was left sitting one line above it and cost the same thing for
	// another year of tenants — measured 2026-08-26 on the live tenant
	// `1jhp7jbrm`, whose `jobs/` held four @Job classes: the artifact carried
	// `var jobs = []`, the classes were not in the bundle at all, the runtime
	// printed no `[runtime] jobs:` line across five boots, and
	// `jobs.job_definitions` held ZERO rows while palsvc ran WITH the jobs
	// module mounted. Nothing errored; the scheduler simply had nothing to
	// schedule, and one of the four was a balance auto-top-up.
	// `hooks` was never emitted AT ALL, so `collectHooks` read `undefined` and
	// every @Hook was dropped by the push that claimed to ship it.
	//
	// The palbase repository's own bundle-controllers.sh has emitted all three
	// since 2026-08-21. That file's header calls the two implementations a
	// DRIFT and says the push-activation gate keeps them honest — it does not:
	// that gate asks whether ENDPOINTS are served, and all three of these
	// surfaces are invisible to it. So the gate is here, below, per surface.
	//
	// NO by-name arrays any more.
	//
	// They were built here from directory globs, each entry's NAME taken from
	// its file. Both halves were a second declaration: the directory decided
	// what existed and the file name decided its identity. The name is now
	// DECLARED on the decorator (`@Job({ name })`, `@Webhook({ name })`) and the
	// runtime derives the surfaces from the app's container — the module says
	// which classes exist and the decorator says what each one is.
	return b.String(), nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func run(ctx context.Context, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	blob, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	return nil
}

func output(ctx context.Context, dir, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	blob, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%s", strings.TrimSpace(trimDiagnostic([]byte(stderr.String()))))
	}
	return string(blob), nil
}

// surfacesScript reports what the CONTAINER holds, for every kind at once.
//
// It used to read `m.jobs` / `m.webhooks` / `m.hooks` — arrays the bundler built
// from directory globs. Those are gone: discovery is the module's now, so the
// honest question is what the container this bundle would build actually holds.
//
// Building one here is safe because this process exits immediately.
// `buildContainer` CLAIMS the declarations, which matters inside the runtime and
// does not matter in a `bun -e`.
const surfacesScript = `
const m = await import(process.argv[1]);
const SDK = m.SDK;
if (typeof SDK?.buildContainer !== "function") {
  console.error("the @palbase/backend in this project exposes no buildContainer — that SDK is too old for module-declared projects.");
  process.exit(2);
}
let c;
try {
  c = SDK.buildContainer();
} catch (e) {
  console.error("the modules in this project do not form a valid graph.\n" + e.message);
  process.exit(2);
}
// THE RUNG THIS BUNDLE REACHES, measured the same way the runtime measures it
// (v2/runtime/src/abi.ts): cumulative, from the seams the bundle RE-EXPORTS, and
// never from a version number. Measured HERE so a push can be refused before the
// artifact is activated, rather than by the pod that has already taken it.
const gen = (() => {
  const has = (k) => typeof (m[k] ?? SDK?.[k]) === "function" || (m[k] ?? SDK?.[k]) !== undefined;
  if (!has("__runWithRuntime") || !has("__requestALS")) return null;
  if (!has("buildModuleClients")) return 1;
  if (typeof SDK?.__claimModules !== "function" ||
      typeof SDK?.buildContainer !== "function" ||
      typeof SDK?.__claimInjectables !== "function") return 2;
  return 3;
})();

console.log(JSON.stringify({
  abiGeneration: gen,
  controllers: SDK.controllersOf(c).length,
  rooms: SDK.roomsOf(c).length,
  hooks: SDK.hooksOf(c).flatMap((k) => {
    const m = SDK.getHookManifest(k);
    return [...m.blocking, ...m.listeners];
  }),
  jobs: SDK.jobsOf(c).map((k) => SDK.getJobManifest(k)),
  webhooks: SDK.webhooksOf(c).map((k) => SDK.getWebhookManifest(k).name),
}));
`

// bundleSurfaces is what the built bundle would serve, read through the SDK the
// project itself carries.
type bundleSurfaces struct {
	// The ABI rung this bundle reaches — `null` when it reaches none.
	//
	// A POINTER: 0 is a measurement ("reaches no rung") and absence is not. The
	// reader is a gate deciding whether a stack can serve this, and collapsing
	// the two would hand it a confident verdict it has not earned.
	AbiGeneration *int `json:"abiGeneration"`
	Controllers   int  `json:"controllers"`
	Rooms         int  `json:"rooms"`
	// THE EVENTS, not a count. A hook's identity IS the event it intercepts
	// (`before.user.create`) — it has no name of its own — and this line used to
	// be `int`, so the build said "2 hook class(es)" where jobs and webhooks said
	// what they were. A count cannot tell an operator that a deploy stopped
	// intercepting an event, which is the one thing they would want to know.
	Hooks    []string `json:"hooks"`
	Jobs     []jobDef `json:"jobs"`
	Webhooks []string `json:"webhooks"`
}

type jobDef struct {
	Name     string `json:"name"`
	Schedule string `json:"schedule"`
	Timeout  int    `json:"timeout"`
	Retry    int    `json:"retry"`
}

// readSurfaces asks the built bundle what it carries.
//
// The gate this replaces compared a DIRECTORY against the bundle, because a
// project could declare four @Job classes on disk and ship a bundle carrying
// none — measured on tenant 1jhp7jbrm, 2026-08-26, deployed green for weeks.
// That gap cannot open the same way now: a job exists because a module lists it,
// and the same module is what the bundle imports. What remains worth refusing is
// a bundle whose modules do not form a valid graph, and this asks the container
// itself rather than guessing.
func readSurfaces(ctx context.Context, dir, bundle string) (*bundleSurfaces, error) {
	raw, err := output(ctx, dir, "bun", "-e", surfacesScript, bundle)
	if err != nil {
		return nil, fmt.Errorf("the bundle could not be inspected: %w", err)
	}
	var out bundleSurfaces
	if err := json.Unmarshal([]byte(strings.TrimSpace(raw)), &out); err != nil {
		return nil, fmt.Errorf("the bundle did not report its surfaces: %q", strings.TrimSpace(raw))
	}
	return &out, nil
}

func writeDefinitionManifests(_ context.Context, dir string, s *bundleSurfaces, w io.Writer) error {
	jobsDir := filepath.Join(dir, ".palbase", "jobs")
	if len(s.Jobs) == 0 {
		// No jobs, no manifest — and a STALE one must not survive a build that
		// removed the last job, or the scheduler keeps firing something the
		// bundle no longer carries.
		return os.RemoveAll(jobsDir)
	}
	seen := map[string]bool{}
	for _, j := range s.Jobs {
		if seen[j.Name] {
			return fmt.Errorf("two jobs are named %q. The name is DECLARED (@Job({ name })), so rename one of them", j.Name)
		}
		seen[j.Name] = true
	}
	if err := os.MkdirAll(jobsDir, 0o755); err != nil {
		return err
	}
	blob, err := json.MarshalIndent(map[string]any{"jobs": s.Jobs}, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(jobsDir, "jobs.manifest.json"), append(blob, '\n'), 0o644); err != nil {
		return fmt.Errorf("the job manifest could not be written: %w", err)
	}
	names := make([]string, 0, len(s.Jobs))
	for _, j := range s.Jobs {
		names = append(names, j.Name)
	}
	fmt.Fprintf(w, "bundled %d job(s) → %s\n", len(s.Jobs), strings.Join(names, ", "))
	return nil
}

// countControllers reports how many classes in the bundle actually carry
// controller metadata — a count of exports would include anything.
const countControllers = `
const m = await import(process.argv[1]);
const withMeta = (m.controllers ?? []).filter(
  (c) => c && c[Symbol.for("palbase.backend.controllerMeta")] !== undefined,
);
console.log(withMeta.length);
`

// listUploadBucketsScript reads the routes from the CLASS, under the SDK's own
// symbol — not from controllerMeta, which carries only __palbase and basePath.
// Guessing that shape produced a gate that quietly passed everything.
//
// It only REPORTS. The comparison used to happen here, against config/storage.ts,
// and that file is gone: buckets are created on the stack, so the only list worth
// comparing against is the stack's. Reporting here and deciding there also means
// `palbase build`, which has no stack, still builds.
const listUploadBucketsScript = `
const bundle = await import(process.argv[1]);
const listed = typeof bundle.getRegisteredControllers === "function"
  ? bundle.getRegisteredControllers() : [];
const ROUTES = Symbol.for("palbase.backend.routes");
for (const c of listed) {
  for (const route of (c?.[ROUTES] ?? [])) {
    const bucket = route?.options?.uploadConfig?.bucket;
    if (bucket) console.log(c.name + "." + (route.fnName ?? route.subpath) + "\t" + bucket);
  }
}
`

// uploadUse is one @Upload route and the bucket it names.
type uploadUse struct {
	Where  string
	Bucket string
}

// readUploadBuckets runs the extractor over a built bundle.
func readUploadBuckets(ctx context.Context, dir, bundle string) ([]uploadUse, error) {
	out, err := output(ctx, dir, "bun", "-e", listUploadBucketsScript, bundle)
	if err != nil {
		return nil, fmt.Errorf("read @Upload buckets from the bundle: %w", err)
	}
	var uses []uploadUse
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		where, bucket, ok := strings.Cut(strings.TrimSpace(line), "\t")
		if !ok || bucket == "" {
			continue
		}
		uses = append(uses, uploadUse{Where: where, Bucket: bucket})
	}
	return uses, nil
}

// unknownUploadBuckets refuses a bundle whose @Upload names a bucket the stack
// does not have. Storage will not create one on demand, so the alternative is a
// route that compiles, deploys, activates, and 404s the first file somebody
// uploads.
// bucketNames is the name-only view, for the gates that only care whether a
// bucket EXISTS.
func bucketNames(buckets []StackBucket) []string {
	names := make([]string, 0, len(buckets))
	for _, b := range buckets {
		names = append(names, b.Name)
	}
	return names
}

func unknownUploadBuckets(uses []uploadUse, have []string) error {
	if len(uses) == 0 {
		return nil
	}
	exists := make(map[string]bool, len(have))
	for _, name := range have {
		exists[name] = true
	}
	var bad []string
	for _, u := range uses {
		if !exists[u.Bucket] {
			bad = append(bad, fmt.Sprintf("%s → bucket %q", u.Where, u.Bucket))
		}
	}
	if len(bad) == 0 {
		return nil
	}
	held := "(none)"
	if len(have) > 0 {
		held = strings.Join(have, ", ")
	}
	return fmt.Errorf("@Upload names %d bucket(s) this stack does not have:\n  %s\nIt has: %s\n"+
		"Create it with `palbase storage add <name>` or fix the name — storage will not create it on demand",
		len(bad), strings.Join(bad, "\n  "), held)
}

// StackBucket is one bucket as the generated types need it: a NAME and the
// renditions it declares.
//
// It is not just a name because `stack-gen.ts` renders a SHAPE per bucket
// carrying its variant union — `never` for a bucket with none — so that asking
// for a rendition a bucket does not have is a compile error. That generator was
// already written and already expecting `{name, variants}`; this side parsed
// only `name` and dropped the rest, so a rendition declared on the stack never
// reached a type. A flag with a reader and no writer.
type StackBucket struct {
	Name string `json:"name"`
	// Variants is EMPTY, never nil, for a bucket with no renditions: the
	// generator renders an empty union as `never`, which is exactly right, and
	// `omitempty` here would make "declares none" indistinguishable from
	// "was not asked".
	Variants []string `json:"variants"`
}

// stackBuckets asks the stack which buckets it actually has.
func stackBuckets(ctx context.Context, target Target) ([]StackBucket, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		strings.TrimSuffix(target.URL, "/")+"/v1/management/storage/buckets", nil)
	if err != nil {
		return nil, err
	}
	if cred, _, credErr := Credential(target.URL); credErr == nil {
		cred.Apply(req)
	}
	res, err := stackClient(target).Do(req)
	if err != nil {
		return nil, fmt.Errorf("%w: reach %s: %v", errStackSilent, target.URL, err)
	}
	defer func() { _ = res.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s did not list its buckets (%d)", target.Describe(), res.StatusCode)
	}
	var payload struct {
		Buckets []struct {
			Name     string `json:"name"`
			Variants []struct {
				Name string `json:"name"`
			} `json:"variants"`
		} `json:"buckets"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("the bucket list did not parse: %w", err)
	}
	out := make([]StackBucket, 0, len(payload.Buckets))
	for _, b := range payload.Buckets {
		// Empty rather than nil: a bucket with no renditions has an EMPTY union,
		// which the generator renders as `never`. nil and empty would generate
		// the same thing today and diverge the moment somebody checks for one.
		variants := make([]string, 0, len(b.Variants))
		for _, v := range b.Variants {
			variants = append(variants, v.Name)
		}
		out = append(out, StackBucket{Name: b.Name, Variants: variants})
	}
	return out, nil
}

// stageControllers writes a copy of the project's controllers with each route's
// return-type schema and inferred throws injected, and returns that directory.
//
// The project's own tree is never touched: the injection is machine-written code
// that belongs in a build, not in somebody's repository. Everything that is not
// a controller is copied verbatim, so relative imports (`../services`) still
// resolve from the staged tree.
func stageControllers(ctx context.Context, dir string, w io.Writer) (string, error) {
	if _, err := exec.LookPath("node"); err != nil {
		return "", fmt.Errorf("node is not installed, and it is what reads your controllers' return " +
			"types (https://nodejs.org). Without it every response in the deployed specification " +
			"would be untyped, and every generated client with it")
	}

	tools, err := os.MkdirTemp("", "palbase-stage-tools-*")
	if err != nil {
		return "", err
	}
	defer removeTemp(tools)
	if err := extractFS(buildCheckFS, "devjs", tools); err != nil {
		return "", fmt.Errorf("extract the stager: %w", err)
	}

	// The whole relative source tree travels together, so it can live outside
	// the checkout. Linking the installed dependencies preserves bare imports
	// without copying node_modules. A unique directory also prevents two builds
	// from replacing each other's staged sources.
	stageDir, err := os.MkdirTemp("", "palbase-staged-controllers-*")
	if err != nil {
		return "", err
	}
	staged := false
	defer func() {
		if !staged {
			removeTemp(stageDir)
		}
	}()
	modules, err := filepath.Abs(filepath.Join(dir, "node_modules"))
	if err != nil {
		return "", err
	}
	if _, err := os.Stat(modules); err == nil {
		if err := os.Symlink(modules, filepath.Join(stageDir, "node_modules")); err != nil {
			return "", fmt.Errorf("make the project's dependencies reachable: %w", err)
		}
	}

	script := filepath.Join(tools, "stage-for-push.js")
	if err := os.WriteFile(script, []byte(stageForPushScript), 0o644); err != nil {
		return "", err
	}

	// The WHOLE project is staged, not just controllers/: a module file imports
	// its controllers by relative path, so staging one directory produced a tree
	// whose modules still pointed at the un-staged sources.
	cmd := exec.CommandContext(ctx, "node", script, dir, stageDir, dir)
	cmd.Dir = dir
	// The analyzers need TypeScript's PARSER — the CLI's pinned copy first, then
	// the project's, because a project may be on TypeScript 7 (whose CommonJS
	// entry has no compiler API) or have none at all. `require` resolves from the
	// SCRIPT's directory, which is a temp dir with nothing in it, so the path has
	// to be said out loud.
	cmd.Env = append(os.Environ(), "NODE_PATH="+devNodePath(dir, w))
	blob, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	if summary := strings.TrimSpace(string(blob)); summary != "" {
		fmt.Fprintln(w, summary)
	}
	staged = true
	return stageDir, nil
}

// stageForPushScript drives the SHARED analyzers over one project.
//
// Written here rather than added to devjs/ because it is the only part that is
// specific to this command: `palbase build` stages into its own validation flow
// and the cloud's deploy stager into its bundler, and all three drive the same
// two modules underneath.
const stageForPushScript = `
const fs = require('fs');
const path = require('path');
const returnTypes = require('./return_types.js');
const throwAnalysis = require('./throw_analysis.js');

const [srcDir, stageDir, projectRoot] = process.argv.slice(2);

const SKIP = new Set(["node_modules", "dist", "build", ".git"]);
function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    // Skipped by NAME, not by type: node_modules is often a SYMLINK and
    // isDirectory() is false for one, so a type-gated check walked into it and
    // tried to copyFileSync a symlinked directory (ENOTSUP).
    if (SKIP.has(entry.name) || entry.name.startsWith(".palbase")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let injected = 0;
for (const file of walk(srcDir)) {
  const rel = path.relative(srcDir, file);
  const dest = path.join(stageDir, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (/\.controller\.(c?ts|tsx)$/i.test(path.basename(file))) {
    let out = returnTypes.injectReturnBindings(fs.readFileSync(file, 'utf8'), rel);
    out = throwAnalysis.injectThrowBindings(out, file, {
      readFile: (p) => { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } },
      fileExists: (p) => fs.existsSync(p),
      projectRoot,
    });
    fs.writeFileSync(dest, out);
    injected += 1;
  } else {
    fs.copyFileSync(file, dest);
  }
}
console.log('typed ' + injected + ' controller file(s) from their return types');
`

// bunVersion is the toolchain that produced the bundle, or "?" when bun answers
// something unexpected — a build is not worth failing over a version string.
func bunVersion(ctx context.Context, dir string) string {
	out, err := output(ctx, dir, "bun", "--version")
	if err != nil {
		return "?"
	}
	return strings.TrimSpace(out)
}

// minimumSDKMajor is the OLDEST @palbase/backend major this CLI can build
// against. It is a floor, not a target: anything from here up bundles.
//
// The 17 line and below have a different controller shape — bundling against
// one produces an entry whose controller export resolves to nothing, and the
// failure surfaces as a bundler stack trace (`var controllers = undefined()`)
// that names neither the version nor the problem. Measured 2026-08-21 against a
// real project.
//
// THE `latest` TRAP IS CLOSED. It used to point at the 17 line, so a
// package.json written the documented way (`"@palbase/backend": "latest"`)
// installed a major BELOW what the runtime served. Verified 2026-08-24:
// `npm view @palbase/backend dist-tags` → latest 21.0.0, and the tenant runtime
// on the live plane resolves 21.0.0 — the two agree, and `latest` is now the
// right thing to write.
const minimumSDKMajor = 18

// checkSDKVersion refuses a build against an SDK this CLI cannot bundle, and
// says which version is installed and why it is wrong.
//
// It runs BEFORE the bundler so the person reads a sentence about versions
// instead of a stack trace about `undefined`. An unreadable package.json is not
// an error here: the bundler's own message is better than a guess.
func checkSDKVersion(projectDir string) error {
	raw, err := os.ReadFile(filepath.Join(projectDir, "node_modules", "@palbase", "backend", "package.json"))
	if err != nil {
		return nil
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil || pkg.Version == "" {
		return nil
	}
	major, err := strconv.Atoi(strings.SplitN(pkg.Version, ".", 2)[0])
	if err != nil || major >= minimumSDKMajor {
		return nil
	}
	return fmt.Errorf(
		"@palbase/backend %s is installed, and this CLI builds against %d or newer.\n"+
			"The %d line declares controllers differently, so a bundle built against it carries\n"+
			"nothing and fails with an error about the bundler rather than about the version.\n\n"+
			"  npm install @palbase/backend@latest\n\n"+
			"`latest` is the right thing to write: it resolves to the line the runtime serves",
		pkg.Version, minimumSDKMajor, major)
}

// errStackSilent marks the one state that must never be spelled as a ceiling:
// the stack did not answer at all.
var errStackSilent = errors.New("the stack did not answer")

// errNoDeploymentYet marks a stack that ANSWERED and has nothing deployed. Its
// ceiling is unknown and unknowable from here, and the first push is exactly
// when that happens.
var errNoDeploymentYet = errors.New("the stack has nothing deployed yet")

// stackServesGeneration asks the target what the HIGHEST rung it can serve is.
//
// `/v1/management/deployments/current` carries it since the DI run wired the
// runtime's ceiling through palsvc. Before that the field existed on the pod and
// nowhere else, so no caller could read it and the admission gate stayed
// one-way: it could ask "is this bundle too OLD for the image" and never "too
// NEW".
//
// (nil, nil) is NOT an error: a stack that has never been deployed to has no
// current deployment, and a stack running an older image does not publish the
// field. What that ABSENCE means is decided by `pushCeilingRefusal`, in one
// place, with its reasoning written down.
//
// THREE STATES, NOT TWO — and conflating the third with the second bricked a
// real tenant. `centauri` answered 503 at every path (its runtime was down), the
// 503 was read as "no answer about the ceiling", the caller turned that into the
// documented default of 2, and the push refused with "the stack's runtime serves
// at most 2" — a measurement nobody made — and sent the author to `palbase
// upgrade`, which refuses back with "push first". Measured 2026-09-02.
//
//	404 / 200-without-the-field  the stack ANSWERED and named no ceiling; its
//	                             image predates the field, so the rung below is
//	                             the answer. (nil, nil)
//	5xx / transport failure      nobody answered. We know NOTHING about this
//	                             stack, and saying otherwise is a lie with an
//	                             outage attached. errStackSilent.
func stackServesGeneration(ctx context.Context, target Target) (*int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		strings.TrimSuffix(target.URL, "/")+"/v1/management/deployments/current", nil)
	if err != nil {
		return nil, err
	}
	if cred, _, credErr := Credential(target.URL); credErr == nil {
		cred.Apply(req)
	}
	res, err := stackClient(target).Do(req)
	if err != nil {
		return nil, fmt.Errorf("%w: reach %s: %v", errStackSilent, target.URL, err)
	}
	defer func() { _ = res.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	if res.StatusCode >= 500 {
		// The stack did not answer. Not "answered with no ceiling" — did not
		// answer. The caller must not turn this into a number.
		return nil, fmt.Errorf("%w: %s answered %d", errStackSilent, target.URL, res.StatusCode)
	}
	if res.StatusCode == http.StatusNotFound {
		// NOTHING DEPLOYED YET — and that is a THIRD state, not the second one.
		//
		// It used to fall through to (nil, nil), which the caller reads as "the
		// image published no ceiling" and answers with the documented default of
		// 2. That default is right for an OLD IMAGE; it is wrong here, and the
		// cost was the whole feature: a bundle reaching rung 3 could never be
		// pushed to a stack that had never been pushed to — which is EVERY
		// project's first push. Measured 2026-09-02.
		//
		// So this gate says nothing here, deliberately. What it protects against
		// is activating an artifact over a working one the runtime cannot serve;
		// with nothing deployed there is nothing to protect, and the runtime's
		// own boot gate (`abi.ts`) still refuses a bundle it cannot serve —
		// loudly, and since FR-149 without killing the pod, so the refusal is
		// readable and the next push is accepted.
		return nil, errNoDeploymentYet
	}
	if res.StatusCode != http.StatusOK {
		return nil, nil
	}
	var out struct {
		ServesBundleGeneration *int `json:"serves_bundle_generation"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, nil
	}
	return out.ServesBundleGeneration, nil
}

// pushCeilingRefusal names why this bundle must not go to this stack, or "".
//
// FR-048. The refusal already existed at BOOT (`abi.ts` aboveCeilingRefusal) and
// it is loud and non-destructive — the previous release keeps serving. What it
// cannot do is arrive before the push, so an author learned that their bundle
// was too new for their stack from a pod log rather than from the command they
// just typed.
//
// ABSENCE IS AN ANSWER on BOTH sides, and each for a measured reason:
//
//   - `serves` nil — the stack publishes no ceiling, so its image was built
//     before the rung that introduced the field. Its ceiling is the rung below.
//     Treating this as "unknown, refuse" would refuse every push to every image
//     in the fleet today, which is not a gate but an outage.
//   - `measured` nil — the bundle reaches NO rung. That is not "too new"; it is
//     a bundle this runtime family cannot run at all, and the floor check at
//     boot owns it by name. This gate stays silent rather than blaming the
//     ceiling for a floor problem.
func pushCeilingRefusal(measured *int, serves *int) string {
	if measured == nil {
		return ""
	}
	ceiling := 2
	if serves != nil {
		ceiling = *serves
	}
	if *measured <= ceiling {
		return ""
	}
	return fmt.Sprintf(
		"this bundle reaches ABI generation %d and the stack's runtime serves at most %d.\n"+
			"  Pushing it would activate an artifact that boots WITHOUT the machinery that\n"+
			"  generation needs — every injected dependency would arrive undefined.\n"+
			"  Upgrade the stack's runtime first (`palbase upgrade`), then push.",
		*measured, ceiling)
}

// trimDiagnostic, YEREL BİR ALETİN hata çıktısını taşır — HTTP gövdesini değil.
//
// Buraya `trimBody` bağlıydı ve o 300 karakterde keser. 300, bir sunucu
// gövdesi için doğru sınır; bir derleyici hatası için yanlış: bun önce kod
// ÇERÇEVESİNİ basar, asıl cümle SONDA gelir. Yani kırpma tam olarak okunması
// gereken yeri atıyordu — `palbase push` "the bundle could not be inspected:"
// deyip ardına bağlamsız birkaç satır bytecode yapıştırıyordu.
//
// BEDELİ ÖLÇÜLDÜ: kontrol düzleminin push'u 02.09.2026'da dört kez bu hatayla
// düştü ve arka arkaya İKİ teşhis yanlış çıktı; ikisi de görünen parçadan
// tahmin yürütmek zorunda kalmıştı, çünkü hatanın kendisi ekrana hiç gelmedi.
//
// SINIRSIZ DA DEĞİL: kaçak bir alet megabaytlarca dökebilir ve terminali
// doldurmak da bir tür saklamaktır. 8 KB, en uzun bun/tsc çerçevesini sonuyla
// birlikte taşır.
func trimDiagnostic(b []byte) string {
	const cap = 8000
	s := strings.TrimSpace(string(b))
	if len(s) <= cap {
		return s
	}
	// BAŞ VE SON BİRLİKTE: baş çerçeveyi, son asıl cümleyi taşır. Yalnız birini
	// tutmak, bu kusurun kendisini bir ucundan tekrar üretmek olurdu.
	return s[:cap/2] + "\n  …[trimmed]…\n" + s[len(s)-cap/2:]
}
