package backend

// stack_bundle.go — building what a push ships.
//
// A stack takes an ARTIFACT: the controllers bundled into one module. It does
// not build, and it cannot: bundling needs the
// project's own node_modules, and those live on the machine that wrote the code.
// So `palbase push` builds first, here, rather than shipping whatever a previous
// build happened to leave on disk — which is how somebody edits a controller,
// pushes, and deploys yesterday's code with today's commit message.
//
// The bundle is built with BUN, not esbuild, and that is not a preference: the
// runtime is Bun, so the code is built by the engine that will run it. Two
// bundlers means two opinions about how a decorator lowers, and the one that
// matters is the runtime's.
//
// DRIFT. The stack's own one-shot (`palsvc --push`) runs the same steps from
// runtime/scripts/bundle-controllers.sh in the palbase repository, so there are
// two implementations of one contract. What keeps them honest is the end of a
// push: the stack activates the artifact and REFUSES it unless the runtime is
// serving endpoints from it, so a bundle this file builds wrongly fails the push
// that built it rather than becoming a quiet 404 later.
import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// bundleEntryHeader is the first line of the generated entry. It is asserted by
// a golden test: the entry's SHAPE is the contract between this bundler and the
// runtime that loads its output.
const bundleEntryHeader = "// GENERATED by `palbase push` — do not edit, do not commit."

// buildStackArtifact bundles a project's controllers and reports the buckets
// its @Upload routes name.
//
// It writes .palbase/esm/controllers/controllers.js and removes it if any step
// refuses — a failed build must leave NOTHING to deploy, because the
// alternative is a push that ships the last good bundle while its author
// believes they shipped the new one.
//
// It no longer evaluates config/: a backend's source carries code and schema,
// and nothing else. Settings live on the stack, put there by whoever changed
// them, so there is nothing here to read and nothing to send.
func buildStackArtifact(ctx context.Context, dir string, w io.Writer) ([]uploadUse, error) {
	controllersDir := filepath.Join(dir, "controllers")
	if _, err := os.Stat(controllersDir); err != nil {
		return nil, fmt.Errorf("%s does not exist — a backend is controllers/*.controller.ts", controllersDir)
	}
	if _, err := exec.LookPath("bun"); err != nil {
		return nil, fmt.Errorf("bun is not installed, and it is what builds a backend for this runtime " +
			"(https://bun.sh). The stack runs Bun, so the bundle is built by the engine that will run it")
	}

	sources, err := controllerSources(controllersDir)
	if err != nil {
		return nil, err
	}
	if len(sources) == 0 {
		return nil, fmt.Errorf("no *.controller.ts under %s — nothing would answer", controllersDir)
	}

	// STAGE FIRST: each controller's RETURN TYPE becomes a response schema.
	//
	// A route's response schema is derived from the method's TypeScript return
	// type, and a type exists only in the source — so something has to read it
	// and write it into the bundle (`recordReturn`, the SDK's own mechanism).
	// Bundling the raw tree skips that, and the artifact then serves a
	// specification whose every 200 response is `{}`. Measured on 2026-08-16:
	// a real app failed to compile against its own project's generated client,
	// because every response had become an opaque value.
	//
	// The staging is the SAME code `palbase build` runs (devjs/return_types.js,
	// devjs/throw_analysis.js), which is the same code the cloud's deploy stager
	// runs. One implementation of a contract that has to hold in three places.
	staged, err := stageControllers(ctx, dir, w)
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.RemoveAll(staged) }()

	esmDir := filepath.Join(dir, ".palbase", "esm", "controllers")
	if err := os.MkdirAll(esmDir, 0o755); err != nil {
		return nil, err
	}
	out := filepath.Join(esmDir, "controllers.js")

	// Anything written from here on is removed when a gate refuses.
	built := false
	defer func() {
		if !built {
			// The manifests go with it: a refused build must leave NOTHING to
			// deploy, and a surviving jobs.manifest.json would let the next push
			// ship a schedule its bundle no longer carries.
			for _, sub := range []string{"esm", "jobs", "hooks"} {
				_ = os.RemoveAll(filepath.Join(dir, ".palbase", sub))
			}
		}
	}()

	if err := os.WriteFile(filepath.Join(dir, ".palbase", "esm", "package.json"),
		[]byte(`{"type":"module"}`+"\n"), 0o644); err != nil {
		return nil, err
	}

	stagedSources, err := controllerSources(staged)
	if err != nil {
		return nil, err
	}
	entry := filepath.Join(staged, ".controllers-entry.ts")
	if err := os.WriteFile(entry, []byte(bundleEntry(dir, stagedSources)), 0o644); err != nil {
		return nil, err
	}

	// VERSION BEFORE BUNDLER: an SDK below what this CLI builds against fails
	// deep inside bun with a message about `undefined`, and the person is left
	// reading a stack trace instead of a sentence about versions.
	if err := checkSDKVersion(dir); err != nil {
		return nil, err
	}

	if err := run(ctx, dir, "bun", "build", entry, "--target=bun", "--format=esm", "--outfile="+out); err != nil {
		return nil, fmt.Errorf("the bundle did not build: %w", err)
	}

	// A bundle carrying no controller is the silent-404 class: it would deploy,
	// activate, and answer nothing. Refused here, where its author is watching.
	count, err := output(ctx, dir, "bun", "-e", countControllers, out)
	if err != nil {
		return nil, fmt.Errorf("the bundle could not be inspected: %w", err)
	}
	n, convErr := strconv.Atoi(strings.TrimSpace(count))
	if convErr != nil || n == 0 {
		return nil, fmt.Errorf("the bundle carries ZERO controllers — nothing would answer")
	}
	// WHICH BUN BUILT IT, said out loud.
	//
	// The bundle is byte-identical for a fixed toolchain — measured: two builds
	// of one tree produce one digest — so the digest a push activates is stable
	// per machine. Across machines it is not: nothing pins bun, and the digest is
	// content-addressed to the bytes it produced. Two people pushing the same
	// commit can therefore activate two digests, and `palbase deploys` shows two
	// entries for what is one version of the code.
	//
	// Printing the version does not close that, and pretending otherwise with a
	// pin would break every machine whose bun is a patch ahead. What it closes is
	// the part that actually costs time: "why is my digest different from yours"
	// is answerable at a glance instead of by bisecting two laptops.
	fmt.Fprintf(w, "built %d controller file(s) → %d controller(s)  [bun %s]\n", len(sources), n, bunVersion(ctx, dir))

	// THE BY-NAME SURFACES, checked and written down.
	//
	// A controller proves itself: the count above refuses a bundle carrying
	// none. Jobs, webhooks and hooks prove nothing by existing on disk, and
	// their failure mode is not a 500 — it is silence. So they are counted OUT
	// OF THE BUILT BUNDLE and compared against what the directories declare,
	// and the Go half's schedule/registration manifests are written from the
	// same bundle, before anything is packed.
	if err := checkDefinitionsSurvived(ctx, dir, out); err != nil {
		return nil, err
	}
	if err := writeDefinitionManifests(ctx, dir, out, w); err != nil {
		return nil, err
	}

	// @Upload names a bucket that must EXIST, and only the bundle knows which
	// names it uses — so they are read out here and checked against the stack by
	// whoever has one. A typo caught then names the bucket; caught later it is a
	// 404 somebody debugs from a phone.
	uses, err := readUploadBuckets(ctx, dir, out)
	if err != nil {
		return nil, err
	}

	// The project's own tests, bundled so they can travel. A deploy runs them
	// against the release it just built, in a container that has no node_modules
	// — so the resolution happens here, where they are.
	if err := bundleTests(ctx, dir, w); err != nil {
		return nil, err
	}

	built = true
	return uses, nil
}

// testsDir is where a project keeps the suites a deploy runs, and
// bundledTestsDir is where their build lands. The artifact collects everything
// under .palbase/esm, so putting them there is what makes them travel.
const (
	testsDir        = "tests"
	bundledTestsDir = ".palbase/esm/tests"
)

// bundleTests builds each *.test.ts into a self-contained module.
//
// ONE BUNDLE PER SUITE, not one for all of them: `bun test` reports per file,
// and a single blob would collapse every suite into one name in the output a
// person reads when their deploy is refused.
//
// Only *.test.* files become suites. A helper beside them is pulled IN by the
// suite that imports it; emitted as its own file it would be run, report zero
// tests, and read as a suite that silently does nothing.
func bundleTests(ctx context.Context, dir string, w io.Writer) error {
	root := filepath.Join(dir, testsDir)
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil // A project with no tests is a legitimate project.
	}

	var suites []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !isTestSource(name) {
			continue
		}
		suites = append(suites, filepath.Join(root, name))
	}
	if len(suites) == 0 {
		return nil
	}
	sort.Strings(suites)

	outDir := filepath.Join(dir, filepath.FromSlash(bundledTestsDir))
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// bun:test and node:test are the RUNNER's, not the bundle's. Inlining them
	// would give each suite its own copy of a registry the runner owns, and the
	// run would report zero tests while every file executed.
	args := append([]string{"build"}, suites...)
	args = append(args, "--target=bun", "--format=esm", "--outdir="+outDir,
		"--external=bun:test", "--external=node:test", "--external=node:assert")
	if err := run(ctx, dir, "bun", args...); err != nil {
		return fmt.Errorf("the tests did not build: %w", err)
	}
	fmt.Fprintf(w, "bundled %d test suite(s)\n", len(suites))
	return nil
}

func isTestSource(name string) bool {
	return strings.HasSuffix(name, ".test.ts") || strings.HasSuffix(name, ".test.js") ||
		strings.HasSuffix(name, ".test.mts") || strings.HasSuffix(name, ".test.mjs")
}

// controllerClassRe finds the class a `@Controller(...)` decorates. It tolerates
// the decorator's own arguments (one level of nested parens), further
// decorators between it and the class, and `export` / `default` / `abstract`.
//
// A regex rather than a parser because the ONLY consumer fails closed: a miss
// leaves the bundle exactly as it was, and a wrong name renames nothing because
// the value has to be the bundled name minus a numeric suffix.
var controllerClassRe = regexp.MustCompile(
	`@Controller\s*\((?:[^()]|\([^()]*\))*\)\s*(?:@[\w$.]+\s*\((?:[^()]|\([^()]*\))*\)\s*)*(?:export\s+)?(?:default\s+)?(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)`)

// controllerClassNames reads the controller class names OUT OF THE SOURCES, in
// the order the bundle will register them: file by file, declaration by
// declaration. A file that cannot be read contributes nothing, which is the
// fail-closed reading — see the block in bundleEntry that consumes this.
func controllerClassNames(sources []string) []string {
	var names []string
	for _, src := range sources {
		raw, err := os.ReadFile(src)
		if err != nil {
			continue
		}
		for _, m := range controllerClassRe.FindAllStringSubmatch(string(raw), -1) {
			names = append(names, m[1])
		}
	}
	return names
}

// controllerSources lists a project's controllers in a stable order, so two
// builds of one tree produce the same bytes.
func controllerSources(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".controller.ts") {
			out = append(out, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(out)
	return out, nil
}

// bundleEntry is the module the bundler starts from.
//
// It re-exports the SDK's request-scope hooks and the SDK namespace beside the
// controllers so the bundle and the runtime share ONE module instance: two
// instances would each get their own AsyncLocalStorage, and the request scope
// would silently not reach a handler.
//
// Controllers are imported for their SIDE EFFECT and never named — @Controller
// records the class as it decorates it, so a controller needs no export at all.
func bundleEntry(dir string, sources []string) string {
	var b strings.Builder
	b.WriteString(bundleEntryHeader + "\n")
	// buildModuleClients RIDES THE SAME SEAM, and leaving it out is not cosmetic:
	// the runtime builds this project's module clients from the BUNDLE's SDK copy
	// and REFUSES TO BOOT a bundle that does not re-export it. A bundle without
	// this line is a deploy that does not come up.
	//
	// There are two bundlers — this one and runtime/scripts/bundle-controllers.sh
	// in the palbase repository — and they must emit the same seam. They did not,
	// for one release: the shell one gained this symbol and this one did not.
	b.WriteString(`export { __runWithRuntime, __requestALS, __getRuntime, buildModuleClients } from "@palbase/backend";` + "\n")
	b.WriteString(`import * as SDK from "@palbase/backend"; export { SDK };` + "\n")
	for _, src := range sources {
		fmt.Fprintf(&b, "import %q;\n", src)
	}
	// The schema is optional: a project with no db/schema.ts still bundles, it
	// just has no typed `.tables` surface.
	if schema := filepath.Join(dir, "db", "schema.ts"); fileExists(schema) {
		fmt.Fprintf(&b, "import __schema from %q; export const schema = __schema;\n", schema)
	}
	// CHANNELS TRAVEL THE SAME WAY, and for a sharper reason than the schema.
	//
	// `defineChannels` writes its declaration onto a globalThis symbol as the
	// module is evaluated, and the runtime reads this EXPORT first, falling back
	// to that symbol. Nothing else in a project imports channels.ts — it is not
	// a controller, a job, a webhook or a hook — so without this line the file
	// is not in the bundle at all, neither path finds a declaration, and the
	// table ships empty.
	//
	// An empty table is not a missing feature: undeclared channels are REFUSED,
	// fail-closed by design. So a project whose channels.ts never shipped has
	// every join answered `unauthorized` while the file sits in plain sight and
	// the deploy reports success. That is `jobs = []` again — same silence, same
	// class — and it is why the three lines below exist at all.
	//
	// It cannot live under config/: nothing evaluates that directory.
	if channels := filepath.Join(dir, "channels.ts"); fileExists(channels) {
		fmt.Fprintf(&b, "import __channels from %q; export const channels = __channels;\n", channels)
	}
	// THE APPLICATION'S DEFAULT AUTH, on the same terms and for the same reason.
	//
	// `defineDefaultAuth` is a call at module scope: it writes the application
	// ring of the auth cascade (route → controller → application → `true`) onto
	// a globalThis symbol as its file is evaluated. Nothing else in a project
	// imports that file — it is not a controller, a job, a webhook or a hook —
	// so without this line it is not in the bundle, is never evaluated, and the
	// declaration is simply NOT THERE.
	//
	// The cascade then falls through to its terminal `true`, and the direction
	// of that failure is the dangerous one: an application declaring
	// `{ verifiedEmail: true }` TIGHTENS the terminal default, so losing the
	// declaration leaves every route open to any signed-in user — the file in
	// plain sight, the deploy reporting success, nothing saying so. Same silence
	// as `jobs = []` and as the channels table that shipped empty.
	//
	// SIDE EFFECT, never named: the declaration is a call and not a value, so —
	// unlike channels — there is nothing to export. It only has to be evaluated,
	// and it is evaluated here, before the module body reads the registry.
	if auth := filepath.Join(dir, "auth.ts"); fileExists(auth) {
		fmt.Fprintf(&b, "import %q;\n", auth)
	}
	// Read AFTER the imports above have run — ESM evaluates every import before
	// the module body, so every decorator has fired by this line.
	// THE BUNDLER DOES NOT GET TO NAME THE PUBLIC API.
	//
	// Every controller lands in ONE bundle, and a bundler MUST rename duplicate
	// top-level identifiers to keep them apart: two files both declaring `class
	// PalaiController` become `PalaiController` and `PalaiController2`. That
	// rename is not cosmetic — `extract_meta.js` derives the dotted-operationId
	// NAMESPACE from `Ctrl.name`, so the shipped API surface ends up chosen by
	// the bundler's dedup counter, and its numbers follow bundle ORDER: adding
	// one file renumbers the others and every client's generated code shifts
	// under it.
	//
	// Ölçüldü 25.08.2026 (palai-cloud, canlı): on bir dosya da `PalaiController`
	// diyordu ve dağıtılan sözleşme `palai` + `palaiController2..11` olarak
	// bölünmüştü. Hiçbir adım hata vermedi; yalnız uygulama kendi backend'ine
	// karşı derlenmez oldu.
	//
	// `--keep-names` BUNU KAPSAMAZ: o minification'a karşıdır, iki ayrı
	// tanımlayıcının tekilleştirilmesine değil (ölçüldü, bun 1.3.9: bayrak
	// açıkken de yeniden adlandırıyor).
	//
	// The names come from the SOURCE, read here rather than from the bundle,
	// because a controller NEED NOT BE EXPORTED — the decorator registers it and
	// the entry imports the file for its side effect alone. Registration order
	// is import order, which is this list's order, so the table lines up
	// position by position.
	//
	// FAILS CLOSED. A name is restored only when the bundled one is exactly the
	// source name followed by digits — the bundler's own pattern. If this table
	// ever drifts from what the bundle registered, nothing is renamed and the
	// behaviour is what it was before this block existed.
	//
	// Two controllers that genuinely share a class name then share a namespace,
	// which is what the source says; a real clash between their METHOD names is
	// still refused, loudly, by the operationId gate in the runtime's generator.
	if names := controllerClassNames(sources); len(names) > 0 {
		blob, _ := json.Marshal(names)
		fmt.Fprintf(&b, `{
  const __want = %s;
  const __regs = SDK.getRegisteredControllers();
  for (let __i = 0; __i < __regs.length && __i < __want.length; __i++) {
    const __c = __regs[__i], __w = __want[__i];
    if (!__w || typeof __c !== "function" || __c.name === __w) continue;
    if (!__c.name.startsWith(__w) || !/^[0-9]+$/.test(__c.name.slice(__w.length))) continue;
    Object.defineProperty(__c, "name", { value: __w, configurable: true });
  }
}
`, blob)
	}
	b.WriteString("export const controllers = SDK.getRegisteredControllers();\n")
	b.WriteString("export const getRegisteredControllers = SDK.getRegisteredControllers;\n")
	b.WriteString("export const resources = [];\n")

	// THE THREE SURFACES THAT TRAVEL BY NAME, unlike controllers.
	//
	// @Controller records its class into a global registry as it decorates it,
	// so a controller needs no export and the entry imports it for the side
	// effect alone. @Job, @Webhook and @Hook do NOT: each stamps metadata onto
	// the class and nothing collects it. The runtime reads these three exports
	// — collectJobs, mountWebhooks, collectHooks — so the class has to reach
	// them by name or the surface never exists.
	//
	// EACH OF THESE LINES WAS ONCE A HARDCODED `[]`, AND EACH COST THE SAME.
	// `webhooks = []` was fixed on 2026-08-25 after a project's
	// `webhooks/stripe.ts` compiled into the bundle and was then declared
	// absent: the URL answered 404 while the deploy said "successful".
	// `jobs = []` was left sitting one line above it and cost the same thing for
	// another year of tenants — measured 2026-08-26 on the live tenant
	// `1jhp7jbrm`, whose `jobs/` held four @Job classes: the artifact carried
	// `var jobs = []`, the classes were not in the bundle at all, the runtime
	// printed no `[runtime] jobs:` line across five boots, and
	// `jobs.job_definitions` held ZERO rows while palsvc ran WITH the jobs
	// module mounted. Nothing errored; the scheduler simply had nothing to
	// schedule, and one of the four was a balance auto-top-up.
	// `hooks` was never emitted AT ALL, so `collectHooks` read `undefined` and
	// every @Hook was dropped by the push that claimed to ship it.
	//
	// The palbase repository's own bundle-controllers.sh has emitted all three
	// since 2026-08-21. That file's header calls the two implementations a
	// DRIFT and says the push-activation gate keeps them honest — it does not:
	// that gate asks whether ENDPOINTS are served, and all three of these
	// surfaces are invisible to it. So the gate is here, below, per surface.
	//
	// THE FILE NAME IS THE NAME — none of the three decorators offers a `name`
	// option, and by the time the code is bundled the file is gone, so the
	// entry is the last place that knows it.
	emitDefinitions(&b, dir, "jobs", "jobs", "__job_", "job")
	emitDefinitions(&b, dir, "webhooks", "webhooks", "__webhook_", "ctor")
	emitDefinitions(&b, dir, "hooks", "hooks", "__hook_", "ctor")
	return b.String()
}

// emitDefinitions writes the import lines and the `export const <export>` array
// for one by-name surface.
//
// `key` is the property the runtime reads the class back from and it is NOT
// uniform: collectJobs reads `record.job`, while mountWebhooks and collectHooks
// read `entry.ctor`. Naming the difference here beats a bundle that loads and
// then quietly carries zero of something.
func emitDefinitions(b *strings.Builder, dir, subdir, export, prefix, key string) {
	sources, err := definitionSources(filepath.Join(dir, subdir))
	if err != nil {
		sources = nil
	}
	var entries []string
	for _, src := range sources {
		name := strings.TrimSuffix(filepath.Base(src), filepath.Ext(src))
		ident := prefix + sanitizeIdent(name)
		fmt.Fprintf(b, "import %s from %q;\n", ident, src)
		entries = append(entries, fmt.Sprintf("{ name: %q, %s: %s }", name, key, ident))
	}
	fmt.Fprintf(b, "export const %s = [%s];\n", export, strings.Join(entries, ", "))
}

// definitionSources lists every `*.ts` one by-name surface declares.
//
// TEST FILES ARE NOT DEFINITIONS: shipping one would mount a URL nobody meant
// to publish (a webhook URL is unauthenticated by design — the signature is the
// credential), or put a test suite on a production cron.
func definitionSources(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() || isTestSource(e.Name()) {
			continue
		}
		if strings.HasSuffix(e.Name(), ".ts") || strings.HasSuffix(e.Name(), ".mts") {
			out = append(out, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(out)
	return out, nil
}

// sanitizeIdent turns a file base name into a JS identifier fragment. A webhook
// named `payment-failed.ts` is legal on disk and illegal as an identifier.
func sanitizeIdent(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func run(ctx context.Context, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	blob, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	return nil
}

func output(ctx context.Context, dir, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	blob, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%s", strings.TrimSpace(trimBody([]byte(stderr.String()))))
	}
	return string(blob), nil
}

// countDefinitionsScript reports what the BUILT bundle carries on each by-name
// surface. `-1` means the export is missing entirely, which is a different
// fault from an empty one and reads differently in the refusal.
const countDefinitionsScript = `
const m = await import(process.argv[1]);
const n = (x) => (Array.isArray(x) ? x.length : -1);
console.log([n(m.jobs), n(m.webhooks), n(m.hooks)].join("\t"));
`

// checkDefinitionsSurvived refuses a bundle that dropped a surface its project
// declares on disk.
//
// THIS IS THE GATE THAT DID NOT EXIST, and its absence is the whole bug. The
// push-activation gate on the stack asks whether ENDPOINTS are served; a job, a
// webhook and a hook are all invisible to it, so a bundle carrying none of them
// activated cleanly and the tenant simply never ran them. Four @Job classes
// deployed green for weeks that way (tenant `1jhp7jbrm`, measured 2026-08-26).
//
// It compares the DIRECTORY against the BUNDLE rather than trusting the
// generator, because the two can disagree for reasons the generator cannot see:
// a file that fails to default-export, a bundler that drops a side-effect-only
// import, an SDK too old to carry the decorator.
func checkDefinitionsSurvived(ctx context.Context, dir, bundle string) error {
	raw, err := output(ctx, dir, "bun", "-e", countDefinitionsScript, bundle)
	if err != nil {
		return fmt.Errorf("the bundle could not be inspected for jobs, webhooks and hooks: %w", err)
	}
	fields := strings.Split(strings.TrimSpace(raw), "\t")
	if len(fields) != 3 {
		return fmt.Errorf("the bundle did not report its jobs, webhooks and hooks: %q", strings.TrimSpace(raw))
	}
	for i, surface := range []struct{ subdir, what string }{
		{"jobs", "@Job class"},
		{"webhooks", "@Webhook class"},
		{"hooks", "@Hook class"},
	} {
		declared, err := definitionSources(filepath.Join(dir, surface.subdir))
		if err != nil || len(declared) == 0 {
			continue
		}
		carried, convErr := strconv.Atoi(strings.TrimSpace(fields[i]))
		if convErr != nil || carried <= 0 {
			return fmt.Errorf(
				"%s/ holds %d file(s) but the bundle carries ZERO of them — every %s in there would deploy and never run. "+
					"One class per file, and it must be the `export default`",
				surface.subdir, len(declared), surface.what)
		}
	}
	return nil
}

// jobManifestScript resolves each @Job's cron out of the built bundle.
//
// palsvc is Go and cannot run a decorator, so the SCHEDULE has to be written
// down by something that can. This file is the only way the scheduler learns
// when a job is due; without it the job code ships and nothing ever calls it.
// Resolved through getJobConfig — the very function the user's class went
// through — so the ceiling checks and cron validation are the SDK's, once.
const jobManifestScript = `
const m = await import(process.argv[1]);
const outPath = process.argv[2];
const getJobConfig = m.SDK?.getJobConfig;
if (typeof getJobConfig !== "function") {
  console.error("the @palbase/backend in this project exposes no getJobConfig — that SDK is too old to carry jobs.");
  process.exit(2);
}
const seen = new Set();
const entries = [];
for (const record of m.jobs ?? []) {
  const name = record?.name;
  const job = record?.job;
  if (!name) {
    console.error("a job record carries no name — the bundler generated a bad entry.");
    process.exit(2);
  }
  if (seen.has(name)) {
    console.error("two jobs are named " + name + ". A job takes its name from its file, so this cannot be renamed away — one of the files has to go.");
    process.exit(2);
  }
  seen.add(name);
  if (!job) {
    console.error("jobs/" + name + ".ts has no default export. One job per file, and the @Job-decorated class must be the default export.");
    process.exit(2);
  }
  let cfg;
  try {
    cfg = getJobConfig(job);
  } catch (e) {
    console.error("jobs/" + name + ".ts — " + e.message);
    process.exit(2);
  }
  entries.push({ name, schedule: cfg.schedule, timeout: cfg.timeout, retry: cfg.retry, file: "jobs/" + name + ".ts" });
}
entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
await Bun.write(outPath, JSON.stringify({ jobs: entries }, null, 2) + "\n");
console.log(entries.length);
`

// hookManifestScript resolves which events a project hooks, and which BLOCK.
//
// Same split as jobs and for the same reason. palsvc reads this at deploy and
// writes the rows that point the event at THIS stack's own runtime; no URL is
// ever typed by an operator.
const hookManifestScript = `
const m = await import(process.argv[1]);
const outPath = process.argv[2];
const getHookConfig = m.SDK?.getHookConfig;
if (typeof getHookConfig !== "function") {
  console.error("the @palbase/backend in this project exposes no getHookConfig — that SDK is too old to carry hooks.");
  process.exit(2);
}
const entries = [];
const seen = new Map();
for (const record of m.hooks ?? []) {
  const name = record?.name;
  const ctor = record?.ctor;
  if (!ctor) {
    console.error("hooks/" + name + ".ts has no default export. One hook class per file, and it must be the default export.");
    process.exit(2);
  }
  let cfg;
  try {
    cfg = getHookConfig(ctor);
  } catch (e) {
    console.error("hooks/" + name + ".ts — " + e.message);
    process.exit(2);
  }
  for (const [event, blocking] of [
    ...Object.keys(cfg.blocking).map((e) => [e, true]),
    ...Object.keys(cfg.listeners).map((e) => [e, false]),
  ]) {
    if (seen.has(event)) {
      console.error("the event \"" + event + "\" is handled by both hooks/" + seen.get(event) + ".ts and hooks/" + name + ".ts. One handler per event.");
      process.exit(2);
    }
    seen.set(event, name);
    entries.push({ event, blocking, file: "hooks/" + name + ".ts" });
  }
}
entries.sort((a, b) => (a.event < b.event ? -1 : a.event > b.event ? 1 : 0));
await Bun.write(outPath, JSON.stringify({ hooks: entries }, null, 2) + "\n");
console.log(entries.length);
`

// writeDefinitionManifests emits the documents the GO half reads.
//
// The bundle carries the code; these carry the facts Go cannot compute without
// executing TypeScript — when each job is due, and which events a hook claims.
// Both are packed into the artifact and read on activation.
//
// NO SURFACE, NO FILE — and the removal matters as much as the write. A project
// that deletes its last job must stop declaring one: `ApplyManifest` prunes
// every definition when the artifact carries no manifest, so a stale file left
// behind from an earlier build would keep a deleted job running on a schedule
// nothing in the source says any more.
func writeDefinitionManifests(ctx context.Context, dir, bundle string, w io.Writer) error {
	for _, m := range []struct{ subdir, file, script, what string }{
		{"jobs", "jobs.manifest.json", jobManifestScript, "job"},
		{"hooks", "hooks.manifest.json", hookManifestScript, "hook"},
	} {
		outDir := filepath.Join(dir, ".palbase", m.subdir)
		declared, err := definitionSources(filepath.Join(dir, m.subdir))
		if err != nil || len(declared) == 0 {
			if err := os.RemoveAll(outDir); err != nil {
				return fmt.Errorf("clear the stale %s manifest: %w", m.what, err)
			}
			continue
		}
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}
		count, err := output(ctx, dir, "bun", "-e", m.script, bundle, filepath.Join(outDir, m.file))
		if err != nil {
			return fmt.Errorf("the %s manifest could not be written: %w", m.what, err)
		}
		fmt.Fprintf(w, "bundled %s %s(s)\n", strings.TrimSpace(count), m.what)
	}
	return nil
}

// countControllers reports how many classes in the bundle actually carry
// controller metadata — a count of exports would include anything.
const countControllers = `
const m = await import(process.argv[1]);
const withMeta = (m.controllers ?? []).filter(
  (c) => c && c[Symbol.for("palbase.backend.controllerMeta")] !== undefined,
);
console.log(withMeta.length);
`

// listUploadBucketsScript reads the routes from the CLASS, under the SDK's own
// symbol — not from controllerMeta, which carries only __palbase and basePath.
// Guessing that shape produced a gate that quietly passed everything.
//
// It only REPORTS. The comparison used to happen here, against config/storage.ts,
// and that file is gone: buckets are created on the stack, so the only list worth
// comparing against is the stack's. Reporting here and deciding there also means
// `palbase build`, which has no stack, still builds.
const listUploadBucketsScript = `
const bundle = await import(process.argv[1]);
const listed = typeof bundle.getRegisteredControllers === "function"
  ? bundle.getRegisteredControllers() : [];
const ROUTES = Symbol.for("palbase.backend.routes");
for (const c of listed) {
  for (const route of (c?.[ROUTES] ?? [])) {
    const bucket = route?.options?.uploadConfig?.bucket;
    if (bucket) console.log(c.name + "." + (route.fnName ?? route.subpath) + "\t" + bucket);
  }
}
`

// uploadUse is one @Upload route and the bucket it names.
type uploadUse struct {
	Where  string
	Bucket string
}

// readUploadBuckets runs the extractor over a built bundle.
func readUploadBuckets(ctx context.Context, dir, bundle string) ([]uploadUse, error) {
	out, err := output(ctx, dir, "bun", "-e", listUploadBucketsScript, bundle)
	if err != nil {
		return nil, fmt.Errorf("read @Upload buckets from the bundle: %w", err)
	}
	var uses []uploadUse
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		where, bucket, ok := strings.Cut(strings.TrimSpace(line), "\t")
		if !ok || bucket == "" {
			continue
		}
		uses = append(uses, uploadUse{Where: where, Bucket: bucket})
	}
	return uses, nil
}

// unknownUploadBuckets refuses a bundle whose @Upload names a bucket the stack
// does not have. Storage will not create one on demand, so the alternative is a
// route that compiles, deploys, activates, and 404s the first file somebody
// uploads.
// bucketNames is the name-only view, for the gates that only care whether a
// bucket EXISTS.
func bucketNames(buckets []StackBucket) []string {
	names := make([]string, 0, len(buckets))
	for _, b := range buckets {
		names = append(names, b.Name)
	}
	return names
}

func unknownUploadBuckets(uses []uploadUse, have []string) error {
	if len(uses) == 0 {
		return nil
	}
	exists := make(map[string]bool, len(have))
	for _, name := range have {
		exists[name] = true
	}
	var bad []string
	for _, u := range uses {
		if !exists[u.Bucket] {
			bad = append(bad, fmt.Sprintf("%s → bucket %q", u.Where, u.Bucket))
		}
	}
	if len(bad) == 0 {
		return nil
	}
	held := "(none)"
	if len(have) > 0 {
		held = strings.Join(have, ", ")
	}
	return fmt.Errorf("@Upload names %d bucket(s) this stack does not have:\n  %s\nIt has: %s\n"+
		"Create it with `palbase storage add <name>` or fix the name — storage will not create it on demand",
		len(bad), strings.Join(bad, "\n  "), held)
}

// StackBucket is one bucket as the generated types need it: a NAME and the
// renditions it declares.
//
// It is not just a name because `stack-gen.ts` renders a SHAPE per bucket
// carrying its variant union — `never` for a bucket with none — so that asking
// for a rendition a bucket does not have is a compile error. That generator was
// already written and already expecting `{name, variants}`; this side parsed
// only `name` and dropped the rest, so a rendition declared on the stack never
// reached a type. A flag with a reader and no writer.
type StackBucket struct {
	Name string `json:"name"`
	// Variants is EMPTY, never nil, for a bucket with no renditions: the
	// generator renders an empty union as `never`, which is exactly right, and
	// `omitempty` here would make "declares none" indistinguishable from
	// "was not asked".
	Variants []string `json:"variants"`
}

// stackBuckets asks the stack which buckets it actually has.
func stackBuckets(ctx context.Context, target Target) ([]StackBucket, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		strings.TrimSuffix(target.URL, "/")+"/v1/management/storage/buckets", nil)
	if err != nil {
		return nil, err
	}
	if cred, _, credErr := Credential(target.URL); credErr == nil {
		cred.Apply(req)
	}
	res, err := stackClient(target).Do(req)
	if err != nil {
		return nil, fmt.Errorf("reach %s: %w", target.URL, err)
	}
	defer func() { _ = res.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s did not list its buckets (%d)", target.Describe(), res.StatusCode)
	}
	var payload struct {
		Buckets []struct {
			Name     string `json:"name"`
			Variants []struct {
				Name string `json:"name"`
			} `json:"variants"`
		} `json:"buckets"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("the bucket list did not parse: %w", err)
	}
	out := make([]StackBucket, 0, len(payload.Buckets))
	for _, b := range payload.Buckets {
		// Empty rather than nil: a bucket with no renditions has an EMPTY union,
		// which the generator renders as `never`. nil and empty would generate
		// the same thing today and diverge the moment somebody checks for one.
		variants := make([]string, 0, len(b.Variants))
		for _, v := range b.Variants {
			variants = append(variants, v.Name)
		}
		out = append(out, StackBucket{Name: b.Name, Variants: variants})
	}
	return out, nil
}

// stageControllers writes a copy of the project's controllers with each route's
// return-type schema and inferred throws injected, and returns that directory.
//
// The project's own tree is never touched: the injection is machine-written code
// that belongs in a build, not in somebody's repository. Everything that is not
// a controller is copied verbatim, so relative imports (`../services`) still
// resolve from the staged tree.
func stageControllers(ctx context.Context, dir string, w io.Writer) (string, error) {
	if _, err := exec.LookPath("node"); err != nil {
		return "", fmt.Errorf("node is not installed, and it is what reads your controllers' return " +
			"types (https://nodejs.org). Without it every response in the deployed specification " +
			"would be untyped, and every generated client with it")
	}

	tools, err := os.MkdirTemp("", "palbase-stage-tools-*")
	if err != nil {
		return "", err
	}
	defer removeTemp(tools)
	if err := extractFS(buildCheckFS, "devjs", tools); err != nil {
		return "", fmt.Errorf("extract the stager: %w", err)
	}

	// Staged as a SIBLING of controllers/, which is what makes both kinds of
	// import resolve. Module resolution walks UP from the file being bundled, so
	// a staging directory in /tmp cannot see the project's node_modules and the
	// very first import — the SDK itself — fails; and one nested a level deeper
	// (.palbase/staged) turns every `../services` in a controller into a path
	// outside the project. The deploy stager stages a sibling for the same two
	// reasons.
	stageDir := filepath.Join(dir, ".palbase-staged-controllers")
	if err := os.RemoveAll(stageDir); err != nil {
		return "", err
	}
	if err := os.MkdirAll(stageDir, 0o755); err != nil {
		return "", err
	}

	script := filepath.Join(tools, "stage-for-push.js")
	if err := os.WriteFile(script, []byte(stageForPushScript), 0o644); err != nil {
		return "", err
	}

	cmd := exec.CommandContext(ctx, "node", script, filepath.Join(dir, "controllers"), stageDir, dir)
	cmd.Dir = dir
	// The analyzers need TypeScript's PARSER — the CLI's pinned copy first, then
	// the project's, because a project may be on TypeScript 7 (whose CommonJS
	// entry has no compiler API) or have none at all. `require` resolves from the
	// SCRIPT's directory, which is a temp dir with nothing in it, so the path has
	// to be said out loud.
	cmd.Env = append(os.Environ(), "NODE_PATH="+devNodePath(dir, w))
	blob, err := cmd.CombinedOutput()
	if err != nil {
		_ = os.RemoveAll(stageDir)
		return "", fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	if summary := strings.TrimSpace(string(blob)); summary != "" {
		fmt.Fprintln(w, summary)
	}
	return stageDir, nil
}

// stageForPushScript drives the SHARED analyzers over one project.
//
// Written here rather than added to devjs/ because it is the only part that is
// specific to this command: `palbase build` stages into its own validation flow
// and the cloud's deploy stager into its bundler, and all three drive the same
// two modules underneath.
const stageForPushScript = `
const fs = require('fs');
const path = require('path');
const returnTypes = require('./return_types.js');
const throwAnalysis = require('./throw_analysis.js');

const [srcDir, stageDir, projectRoot] = process.argv.slice(2);

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let injected = 0;
for (const file of walk(srcDir)) {
  const rel = path.relative(srcDir, file);
  const dest = path.join(stageDir, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (/\.controller\.(c?ts|tsx)$/i.test(path.basename(file))) {
    let out = returnTypes.injectReturnBindings(fs.readFileSync(file, 'utf8'), rel);
    out = throwAnalysis.injectThrowBindings(out, file, {
      readFile: (p) => { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } },
      fileExists: (p) => fs.existsSync(p),
      projectRoot,
    });
    fs.writeFileSync(dest, out);
    injected += 1;
  } else {
    fs.copyFileSync(file, dest);
  }
}
console.log('typed ' + injected + ' controller file(s) from their return types');
`

// bunVersion is the toolchain that produced the bundle, or "?" when bun answers
// something unexpected — a build is not worth failing over a version string.
func bunVersion(ctx context.Context, dir string) string {
	out, err := output(ctx, dir, "bun", "--version")
	if err != nil {
		return "?"
	}
	return strings.TrimSpace(out)
}

// minimumSDKMajor is the OLDEST @palbase/backend major this CLI can build
// against. It is a floor, not a target: anything from here up bundles.
//
// The 17 line and below have a different controller shape — bundling against
// one produces an entry whose controller export resolves to nothing, and the
// failure surfaces as a bundler stack trace (`var controllers = undefined()`)
// that names neither the version nor the problem. Measured 2026-08-21 against a
// real project.
//
// THE `latest` TRAP IS CLOSED. It used to point at the 17 line, so a
// package.json written the documented way (`"@palbase/backend": "latest"`)
// installed a major BELOW what the runtime served. Verified 2026-08-24:
// `npm view @palbase/backend dist-tags` → latest 21.0.0, and the tenant runtime
// on the live plane resolves 21.0.0 — the two agree, and `latest` is now the
// right thing to write.
const minimumSDKMajor = 18

// checkSDKVersion refuses a build against an SDK this CLI cannot bundle, and
// says which version is installed and why it is wrong.
//
// It runs BEFORE the bundler so the person reads a sentence about versions
// instead of a stack trace about `undefined`. An unreadable package.json is not
// an error here: the bundler's own message is better than a guess.
func checkSDKVersion(projectDir string) error {
	raw, err := os.ReadFile(filepath.Join(projectDir, "node_modules", "@palbase", "backend", "package.json"))
	if err != nil {
		return nil
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil || pkg.Version == "" {
		return nil
	}
	major, err := strconv.Atoi(strings.SplitN(pkg.Version, ".", 2)[0])
	if err != nil || major >= minimumSDKMajor {
		return nil
	}
	return fmt.Errorf(
		"@palbase/backend %s is installed, and this CLI builds against %d or newer.\n"+
			"The %d line declares controllers differently, so a bundle built against it carries\n"+
			"nothing and fails with an error about the bundler rather than about the version.\n\n"+
			"  npm install @palbase/backend@latest\n\n"+
			"`latest` is the right thing to write: it resolves to the line the runtime serves.",
		pkg.Version, minimumSDKMajor, major)
}
