package backend

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The stack-gen bridge is deliberately thinner than env-gen's: there is no
// project file to bundle, because the names come from the STACK rather than
// from a declaration the author wrote. This fixture therefore only has to
// provide makeStackDts — kept verbatim with src/stack-gen.ts so the test is a
// contract lock rather than two synthetic halves agreeing with each other.
const fixtureStackPkg = `
'use strict';
function liveNames(names) { return [...new Set(names || [])].sort(); }
function memberName(n) { return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : JSON.stringify(n); }
function members(names) {
  if (names.length === 0) return '';
  return '\n' + names.map((n) => '    ' + memberName(n) + ': true;').join('\n') + '\n  ';
}
function makeStackDts(names) {
  const secrets = liveNames(names.secrets);
  const flags = liveNames(names.flags);
  const buckets = liveNames(names.buckets);
  return '// palbase-stack.d.ts — GENERATED by @palbase/backend. Do not edit.\n' +
    '// Source: the linked environment\'s stack.\n\n' +
    'declare module "@palbase/backend/stack" {\n' +
    '  interface Secrets {' + members(secrets) + '}\n\n' +
    '  interface Flags {' + members(flags) + '}\n\n' +
    '  interface Buckets {' + members(buckets) + '}\n' +
    '}\n\nexport {};\n';
}
module.exports = { makeStackDts };
`

func TestGenerateStackTypes(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	root := t.TempDir()
	mustWrite(t, root, "node_modules/@palbase/backend/package.json",
		`{"name":"@palbase/backend","version":"0.0.0-test","main":"index.js"}`)
	mustWrite(t, root, "node_modules/@palbase/backend/index.js", fixtureStackPkg)

	names := StackNames{
		Secrets: []string{"STRIPE_KEY", "OPENAI_API_KEY"},
		Flags:   []string{"newCheckout"},
		Buckets: []string{"avatars", "my-bucket"},
	}
	if err := generateStackTypes(context.Background(), root, filepath.Join(root, "node_modules"), names); err != nil {
		t.Fatalf("generateStackTypes: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(root, "palbase-stack.d.ts"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	got := string(raw)

	for _, want := range []string{
		`declare module "@palbase/backend/stack"`,
		"OPENAI_API_KEY: true;",
		"STRIPE_KEY: true;",
		"newCheckout: true;",
		"avatars: true;",
		`"my-bucket": true;`, // not a bare identifier — must be quoted
		"export {};",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated file is missing %q\n---\n%s", want, got)
		}
	}

	// Sorted, so the same stack always renders the same bytes and a diff shows
	// what CHANGED rather than how the API ordered its answer.
	if strings.Index(got, "OPENAI_API_KEY") > strings.Index(got, "STRIPE_KEY") {
		t.Error("secret names must be sorted")
	}
}

// A stack that could not be asked must NOT narrow the project's types to
// nothing. Every Secrets.get() in the codebase would become a compile error and
// read as "your code is wrong" rather than "the stack was unreachable", so the
// existing file is left exactly as it was.
func TestGenerateStackTypes_LeavesTheOldFileWhenTheBridgeFails(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	root := t.TempDir()
	// No @palbase/backend installed → the bridge cannot render.
	previous := "// palbase-stack.d.ts — GENERATED by @palbase/backend. Do not edit.\n"
	mustWrite(t, root, "palbase-stack.d.ts", previous)

	err := generateStackTypes(context.Background(), root, filepath.Join(root, "node_modules"), StackNames{})
	if err == nil {
		t.Fatal("expected an error when @palbase/backend is absent")
	}
	if !strings.Contains(err.Error(), "@palbase/backend not found") {
		t.Errorf("the error must name the missing package, got: %v", err)
	}

	raw, readErr := os.ReadFile(filepath.Join(root, "palbase-stack.d.ts"))
	if readErr != nil {
		t.Fatalf("the previous file must survive: %v", readErr)
	}
	if string(raw) != previous {
		t.Errorf("the previous file was overwritten:\n%s", raw)
	}
}
