package backend

// stack_bundle.go — building what a push ships.
//
// A stack takes an ARTIFACT: the controllers bundled into one module. It does
// not build, and it cannot: bundling needs the
// project's own node_modules, and those live on the machine that wrote the code.
// So `palbase push` builds first, here, rather than shipping whatever a previous
// build happened to leave on disk — which is how somebody edits a controller,
// pushes, and deploys yesterday's code with today's commit message.
//
// The bundle is built with BUN, not esbuild, and that is not a preference: the
// runtime is Bun, so the code is built by the engine that will run it. Two
// bundlers means two opinions about how a decorator lowers, and the one that
// matters is the runtime's.
//
// DRIFT. The stack's own one-shot (`palsvc --push`) runs the same steps from
// runtime/scripts/bundle-controllers.sh in the palbase repository, so there are
// two implementations of one contract. What keeps them honest is the end of a
// push: the stack activates the artifact and REFUSES it unless the runtime is
// serving endpoints from it, so a bundle this file builds wrongly fails the push
// that built it rather than becoming a quiet 404 later.
import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// bundleEntryHeader is the first line of the generated entry. It is asserted by
// a golden test: the entry's SHAPE is the contract between this bundler and the
// runtime that loads its output.
const bundleEntryHeader = "// GENERATED by `palbase push` — do not edit, do not commit."

// buildStackArtifact bundles a project's controllers and reports the buckets
// its @Upload routes name.
//
// It writes .palbase/esm/controllers/controllers.js and removes it if any step
// refuses — a failed build must leave NOTHING to deploy, because the
// alternative is a push that ships the last good bundle while its author
// believes they shipped the new one.
//
// It no longer evaluates config/: a backend's source carries code and schema,
// and nothing else. Settings live on the stack, put there by whoever changed
// them, so there is nothing here to read and nothing to send.
func buildStackArtifact(ctx context.Context, dir string, w io.Writer) ([]uploadUse, error) {
	controllersDir := filepath.Join(dir, "controllers")
	if _, err := os.Stat(controllersDir); err != nil {
		return nil, fmt.Errorf("%s does not exist — a backend is controllers/*.controller.ts", controllersDir)
	}
	if _, err := exec.LookPath("bun"); err != nil {
		return nil, fmt.Errorf("bun is not installed, and it is what builds a backend for this runtime " +
			"(https://bun.sh). The stack runs Bun, so the bundle is built by the engine that will run it")
	}

	sources, err := controllerSources(controllersDir)
	if err != nil {
		return nil, err
	}
	if len(sources) == 0 {
		return nil, fmt.Errorf("no *.controller.ts under %s — nothing would answer", controllersDir)
	}

	// STAGE FIRST: each controller's RETURN TYPE becomes a response schema.
	//
	// A route's response schema is derived from the method's TypeScript return
	// type, and a type exists only in the source — so something has to read it
	// and write it into the bundle (`recordReturn`, the SDK's own mechanism).
	// Bundling the raw tree skips that, and the artifact then serves a
	// specification whose every 200 response is `{}`. Measured on 2026-08-16:
	// a real app failed to compile against its own project's generated client,
	// because every response had become an opaque value.
	//
	// The staging is the SAME code `palbase build` runs (devjs/return_types.js,
	// devjs/throw_analysis.js), which is the same code the cloud's deploy stager
	// runs. One implementation of a contract that has to hold in three places.
	staged, err := stageControllers(ctx, dir, w)
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.RemoveAll(staged) }()

	esmDir := filepath.Join(dir, ".palbase", "esm", "controllers")
	if err := os.MkdirAll(esmDir, 0o755); err != nil {
		return nil, err
	}
	out := filepath.Join(esmDir, "controllers.js")

	// Anything written from here on is removed when a gate refuses.
	built := false
	defer func() {
		if !built {
			_ = os.RemoveAll(filepath.Join(dir, ".palbase", "esm"))
		}
	}()

	if err := os.WriteFile(filepath.Join(dir, ".palbase", "esm", "package.json"),
		[]byte(`{"type":"module"}`+"\n"), 0o644); err != nil {
		return nil, err
	}

	stagedSources, err := controllerSources(staged)
	if err != nil {
		return nil, err
	}
	entry := filepath.Join(staged, ".controllers-entry.ts")
	if err := os.WriteFile(entry, []byte(bundleEntry(dir, stagedSources)), 0o644); err != nil {
		return nil, err
	}

	// VERSION BEFORE BUNDLER: an SDK below what this CLI builds against fails
	// deep inside bun with a message about `undefined`, and the person is left
	// reading a stack trace instead of a sentence about versions.
	if err := checkSDKVersion(dir); err != nil {
		return nil, err
	}

	if err := run(ctx, dir, "bun", "build", entry, "--target=bun", "--format=esm", "--outfile="+out); err != nil {
		return nil, fmt.Errorf("the bundle did not build: %w", err)
	}

	// A bundle carrying no controller is the silent-404 class: it would deploy,
	// activate, and answer nothing. Refused here, where its author is watching.
	count, err := output(ctx, dir, "bun", "-e", countControllers, out)
	if err != nil {
		return nil, fmt.Errorf("the bundle could not be inspected: %w", err)
	}
	n, convErr := strconv.Atoi(strings.TrimSpace(count))
	if convErr != nil || n == 0 {
		return nil, fmt.Errorf("the bundle carries ZERO controllers — nothing would answer")
	}
	// WHICH BUN BUILT IT, said out loud.
	//
	// The bundle is byte-identical for a fixed toolchain — measured: two builds
	// of one tree produce one digest — so the digest a push activates is stable
	// per machine. Across machines it is not: nothing pins bun, and the digest is
	// content-addressed to the bytes it produced. Two people pushing the same
	// commit can therefore activate two digests, and `palbase deploys` shows two
	// entries for what is one version of the code.
	//
	// Printing the version does not close that, and pretending otherwise with a
	// pin would break every machine whose bun is a patch ahead. What it closes is
	// the part that actually costs time: "why is my digest different from yours"
	// is answerable at a glance instead of by bisecting two laptops.
	fmt.Fprintf(w, "built %d controller file(s) → %d controller(s)  [bun %s]\n", len(sources), n, bunVersion(ctx, dir))

	// @Upload names a bucket that must EXIST, and only the bundle knows which
	// names it uses — so they are read out here and checked against the stack by
	// whoever has one. A typo caught then names the bucket; caught later it is a
	// 404 somebody debugs from a phone.
	uses, err := readUploadBuckets(ctx, dir, out)
	if err != nil {
		return nil, err
	}

	// The project's own tests, bundled so they can travel. A deploy runs them
	// against the release it just built, in a container that has no node_modules
	// — so the resolution happens here, where they are.
	if err := bundleTests(ctx, dir, w); err != nil {
		return nil, err
	}

	built = true
	return uses, nil
}

// testsDir is where a project keeps the suites a deploy runs, and
// bundledTestsDir is where their build lands. The artifact collects everything
// under .palbase/esm, so putting them there is what makes them travel.
const (
	testsDir        = "tests"
	bundledTestsDir = ".palbase/esm/tests"
)

// bundleTests builds each *.test.ts into a self-contained module.
//
// ONE BUNDLE PER SUITE, not one for all of them: `bun test` reports per file,
// and a single blob would collapse every suite into one name in the output a
// person reads when their deploy is refused.
//
// Only *.test.* files become suites. A helper beside them is pulled IN by the
// suite that imports it; emitted as its own file it would be run, report zero
// tests, and read as a suite that silently does nothing.
func bundleTests(ctx context.Context, dir string, w io.Writer) error {
	root := filepath.Join(dir, testsDir)
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil // A project with no tests is a legitimate project.
	}

	var suites []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !isTestSource(name) {
			continue
		}
		suites = append(suites, filepath.Join(root, name))
	}
	if len(suites) == 0 {
		return nil
	}
	sort.Strings(suites)

	outDir := filepath.Join(dir, filepath.FromSlash(bundledTestsDir))
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// bun:test and node:test are the RUNNER's, not the bundle's. Inlining them
	// would give each suite its own copy of a registry the runner owns, and the
	// run would report zero tests while every file executed.
	args := append([]string{"build"}, suites...)
	args = append(args, "--target=bun", "--format=esm", "--outdir="+outDir,
		"--external=bun:test", "--external=node:test", "--external=node:assert")
	if err := run(ctx, dir, "bun", args...); err != nil {
		return fmt.Errorf("the tests did not build: %w", err)
	}
	fmt.Fprintf(w, "bundled %d test suite(s)\n", len(suites))
	return nil
}

func isTestSource(name string) bool {
	return strings.HasSuffix(name, ".test.ts") || strings.HasSuffix(name, ".test.js") ||
		strings.HasSuffix(name, ".test.mts") || strings.HasSuffix(name, ".test.mjs")
}

// controllerSources lists a project's controllers in a stable order, so two
// builds of one tree produce the same bytes.
func controllerSources(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".controller.ts") {
			out = append(out, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(out)
	return out, nil
}

// bundleEntry is the module the bundler starts from.
//
// It re-exports the SDK's request-scope hooks and the SDK namespace beside the
// controllers so the bundle and the runtime share ONE module instance: two
// instances would each get their own AsyncLocalStorage, and the request scope
// would silently not reach a handler.
//
// Controllers are imported for their SIDE EFFECT and never named — @Controller
// records the class as it decorates it, so a controller needs no export at all.
func bundleEntry(dir string, sources []string) string {
	var b strings.Builder
	b.WriteString(bundleEntryHeader + "\n")
	b.WriteString(`export { __runWithRuntime, __requestALS, __getRuntime } from "@palbase/backend";` + "\n")
	b.WriteString(`import * as SDK from "@palbase/backend"; export { SDK };` + "\n")
	for _, src := range sources {
		fmt.Fprintf(&b, "import %q;\n", src)
	}
	// The schema is optional: a project with no db/schema.ts still bundles, it
	// just has no typed `.tables` surface.
	if schema := filepath.Join(dir, "db", "schema.ts"); fileExists(schema) {
		fmt.Fprintf(&b, "import __schema from %q; export const schema = __schema;\n", schema)
	}
	// Read AFTER the imports above have run — ESM evaluates every import before
	// the module body, so every decorator has fired by this line.
	b.WriteString("export const controllers = SDK.getRegisteredControllers();\n")
	b.WriteString("export const getRegisteredControllers = SDK.getRegisteredControllers;\n")
	b.WriteString("export const jobs = []; export const webhooks = []; export const resources = [];\n")
	return b.String()
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func run(ctx context.Context, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	blob, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	return nil
}

func output(ctx context.Context, dir, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	blob, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%s", strings.TrimSpace(trimBody([]byte(stderr.String()))))
	}
	return string(blob), nil
}

// countControllers reports how many classes in the bundle actually carry
// controller metadata — a count of exports would include anything.
const countControllers = `
const m = await import(process.argv[1]);
const withMeta = (m.controllers ?? []).filter(
  (c) => c && c[Symbol.for("palbase.backend.controllerMeta")] !== undefined,
);
console.log(withMeta.length);
`

// listUploadBucketsScript reads the routes from the CLASS, under the SDK's own
// symbol — not from controllerMeta, which carries only __palbase and basePath.
// Guessing that shape produced a gate that quietly passed everything.
//
// It only REPORTS. The comparison used to happen here, against config/storage.ts,
// and that file is gone: buckets are created on the stack, so the only list worth
// comparing against is the stack's. Reporting here and deciding there also means
// `palbase build`, which has no stack, still builds.
const listUploadBucketsScript = `
const bundle = await import(process.argv[1]);
const listed = typeof bundle.getRegisteredControllers === "function"
  ? bundle.getRegisteredControllers() : [];
const ROUTES = Symbol.for("palbase.backend.routes");
for (const c of listed) {
  for (const route of (c?.[ROUTES] ?? [])) {
    const bucket = route?.options?.uploadConfig?.bucket;
    if (bucket) console.log(c.name + "." + (route.fnName ?? route.subpath) + "\t" + bucket);
  }
}
`

// uploadUse is one @Upload route and the bucket it names.
type uploadUse struct {
	Where  string
	Bucket string
}

// readUploadBuckets runs the extractor over a built bundle.
func readUploadBuckets(ctx context.Context, dir, bundle string) ([]uploadUse, error) {
	out, err := output(ctx, dir, "bun", "-e", listUploadBucketsScript, bundle)
	if err != nil {
		return nil, fmt.Errorf("read @Upload buckets from the bundle: %w", err)
	}
	var uses []uploadUse
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		where, bucket, ok := strings.Cut(strings.TrimSpace(line), "\t")
		if !ok || bucket == "" {
			continue
		}
		uses = append(uses, uploadUse{Where: where, Bucket: bucket})
	}
	return uses, nil
}

// unknownUploadBuckets refuses a bundle whose @Upload names a bucket the stack
// does not have. Storage will not create one on demand, so the alternative is a
// route that compiles, deploys, activates, and 404s the first file somebody
// uploads.
func unknownUploadBuckets(uses []uploadUse, have []string) error {
	if len(uses) == 0 {
		return nil
	}
	exists := make(map[string]bool, len(have))
	for _, name := range have {
		exists[name] = true
	}
	var bad []string
	for _, u := range uses {
		if !exists[u.Bucket] {
			bad = append(bad, fmt.Sprintf("%s → bucket %q", u.Where, u.Bucket))
		}
	}
	if len(bad) == 0 {
		return nil
	}
	held := "(none)"
	if len(have) > 0 {
		held = strings.Join(have, ", ")
	}
	return fmt.Errorf("@Upload names %d bucket(s) this stack does not have:\n  %s\nIt has: %s\n"+
		"Create it with `palbase storage add <name>` or fix the name — storage will not create it on demand",
		len(bad), strings.Join(bad, "\n  "), held)
}

// stackBuckets asks the stack which buckets it actually has.
func stackBuckets(ctx context.Context, target Target) ([]string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		strings.TrimSuffix(target.URL, "/")+"/v1/management/storage/buckets", nil)
	if err != nil {
		return nil, err
	}
	if cred, _, credErr := Credential(target.URL); credErr == nil {
		cred.Apply(req)
	}
	res, err := stackClient(target).Do(req)
	if err != nil {
		return nil, fmt.Errorf("reach %s: %w", target.URL, err)
	}
	defer func() { _ = res.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s did not list its buckets (%d)", target.Describe(), res.StatusCode)
	}
	var payload struct {
		Buckets []struct {
			Name string `json:"name"`
		} `json:"buckets"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("the bucket list did not parse: %w", err)
	}
	names := make([]string, 0, len(payload.Buckets))
	for _, b := range payload.Buckets {
		names = append(names, b.Name)
	}
	return names, nil
}

// stageControllers writes a copy of the project's controllers with each route's
// return-type schema and inferred throws injected, and returns that directory.
//
// The project's own tree is never touched: the injection is machine-written code
// that belongs in a build, not in somebody's repository. Everything that is not
// a controller is copied verbatim, so relative imports (`../services`) still
// resolve from the staged tree.
func stageControllers(ctx context.Context, dir string, w io.Writer) (string, error) {
	if _, err := exec.LookPath("node"); err != nil {
		return "", fmt.Errorf("node is not installed, and it is what reads your controllers' return " +
			"types (https://nodejs.org). Without it every response in the deployed specification " +
			"would be untyped, and every generated client with it")
	}

	tools, err := os.MkdirTemp("", "palbase-stage-tools-*")
	if err != nil {
		return "", err
	}
	defer removeTemp(tools)
	if err := extractFS(buildCheckFS, "devjs", tools); err != nil {
		return "", fmt.Errorf("extract the stager: %w", err)
	}

	// Staged as a SIBLING of controllers/, which is what makes both kinds of
	// import resolve. Module resolution walks UP from the file being bundled, so
	// a staging directory in /tmp cannot see the project's node_modules and the
	// very first import — the SDK itself — fails; and one nested a level deeper
	// (.palbase/staged) turns every `../services` in a controller into a path
	// outside the project. The deploy stager stages a sibling for the same two
	// reasons.
	stageDir := filepath.Join(dir, ".palbase-staged-controllers")
	if err := os.RemoveAll(stageDir); err != nil {
		return "", err
	}
	if err := os.MkdirAll(stageDir, 0o755); err != nil {
		return "", err
	}

	script := filepath.Join(tools, "stage-for-push.js")
	if err := os.WriteFile(script, []byte(stageForPushScript), 0o644); err != nil {
		return "", err
	}

	cmd := exec.CommandContext(ctx, "node", script, filepath.Join(dir, "controllers"), stageDir, dir)
	cmd.Dir = dir
	// The analyzers need TypeScript's PARSER — the CLI's pinned copy first, then
	// the project's, because a project may be on TypeScript 7 (whose CommonJS
	// entry has no compiler API) or have none at all. `require` resolves from the
	// SCRIPT's directory, which is a temp dir with nothing in it, so the path has
	// to be said out loud.
	cmd.Env = append(os.Environ(), "NODE_PATH="+devNodePath(dir, w))
	blob, err := cmd.CombinedOutput()
	if err != nil {
		_ = os.RemoveAll(stageDir)
		return "", fmt.Errorf("%s", strings.TrimSpace(trimBody(blob)))
	}
	if summary := strings.TrimSpace(string(blob)); summary != "" {
		fmt.Fprintln(w, summary)
	}
	return stageDir, nil
}

// stageForPushScript drives the SHARED analyzers over one project.
//
// Written here rather than added to devjs/ because it is the only part that is
// specific to this command: `palbase build` stages into its own validation flow
// and the cloud's deploy stager into its bundler, and all three drive the same
// two modules underneath.
const stageForPushScript = `
const fs = require('fs');
const path = require('path');
const returnTypes = require('./return_types.js');
const throwAnalysis = require('./throw_analysis.js');

const [srcDir, stageDir, projectRoot] = process.argv.slice(2);

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let injected = 0;
for (const file of walk(srcDir)) {
  const rel = path.relative(srcDir, file);
  const dest = path.join(stageDir, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (/\.controller\.(c?ts|tsx)$/i.test(path.basename(file))) {
    let out = returnTypes.injectReturnBindings(fs.readFileSync(file, 'utf8'), rel);
    out = throwAnalysis.injectThrowBindings(out, file, {
      readFile: (p) => { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } },
      fileExists: (p) => fs.existsSync(p),
      projectRoot,
    });
    fs.writeFileSync(dest, out);
    injected += 1;
  } else {
    fs.copyFileSync(file, dest);
  }
}
console.log('typed ' + injected + ' controller file(s) from their return types');
`

// bunVersion is the toolchain that produced the bundle, or "?" when bun answers
// something unexpected — a build is not worth failing over a version string.
func bunVersion(ctx context.Context, dir string) string {
	out, err := output(ctx, dir, "bun", "--version")
	if err != nil {
		return "?"
	}
	return strings.TrimSpace(out)
}

// minimumSDKMajor is the OLDEST @palbase/backend major this CLI can build
// against. It is a floor, not a target: anything from here up bundles.
//
// The 17 line and below have a different controller shape — bundling against
// one produces an entry whose controller export resolves to nothing, and the
// failure surfaces as a bundler stack trace (`var controllers = undefined()`)
// that names neither the version nor the problem. Measured 2026-08-21 against a
// real project.
//
// THE `latest` TRAP IS CLOSED. It used to point at the 17 line, so a
// package.json written the documented way (`"@palbase/backend": "latest"`)
// installed a major BELOW what the runtime served. Verified 2026-08-24:
// `npm view @palbase/backend dist-tags` → latest 21.0.0, and the tenant runtime
// on the live plane resolves 21.0.0 — the two agree, and `latest` is now the
// right thing to write.
const minimumSDKMajor = 18

// checkSDKVersion refuses a build against an SDK this CLI cannot bundle, and
// says which version is installed and why it is wrong.
//
// It runs BEFORE the bundler so the person reads a sentence about versions
// instead of a stack trace about `undefined`. An unreadable package.json is not
// an error here: the bundler's own message is better than a guess.
func checkSDKVersion(projectDir string) error {
	raw, err := os.ReadFile(filepath.Join(projectDir, "node_modules", "@palbase", "backend", "package.json"))
	if err != nil {
		return nil
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil || pkg.Version == "" {
		return nil
	}
	major, err := strconv.Atoi(strings.SplitN(pkg.Version, ".", 2)[0])
	if err != nil || major >= minimumSDKMajor {
		return nil
	}
	return fmt.Errorf(
		"@palbase/backend %s is installed, and this CLI builds against %d or newer.\n"+
			"The %d line declares controllers differently, so a bundle built against it carries\n"+
			"nothing and fails with an error about the bundler rather than about the version.\n\n"+
			"  npm install @palbase/backend@latest\n\n"+
			"`latest` is the right thing to write: it resolves to the line the runtime serves.",
		pkg.Version, minimumSDKMajor, major)
}
