package backend

import (
	"encoding/json"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The stack-gen bridge is deliberately thinner than env-gen's: there is no
// project file to bundle, because the names come from the STACK rather than
// from a declaration the author wrote. This fixture therefore only has to
// provide makeStackDts — kept verbatim with src/stack-gen.ts so the test is a
// contract lock rather than two synthetic halves agreeing with each other.
const fixtureStackPkg = `
'use strict';
function liveNames(names) { return [...new Set(names || [])].sort(); }
function memberName(n) { return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : JSON.stringify(n); }
function members(names) {
  if (names.length === 0) return '';
  return '\n' + names.map((n) => '    ' + memberName(n) + ': true;').join('\n') + '\n  ';
}
// Buckets render a SHAPE carrying their variant union — the real generator's
// behaviour (stack-gen.ts bucketMembers), mirrored here because this stub
// STANDS IN for it. A stub that understood less would pass a test the real
// generator fails, which is the one thing a stand-in must not do.
function bucketMembers(buckets) {
  const rows = (buckets || []).map((b) => (typeof b === 'string' ? { name: b, variants: [] } : b));
  if (rows.length === 0) return '';
  rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return '\n' + rows.map((b) => {
    const union = (b.variants || []).length
      ? [...b.variants].sort().map((v) => JSON.stringify(v)).join(' | ')
      : 'never';
    return '    ' + memberName(b.name) + ': { variants: ' + union + ' };';
  }).join('\n') + '\n  ';
}
function makeStackDts(names) {
  const secrets = liveNames(names.secrets);
  const flags = liveNames(names.flags);
  return '// palbase-stack.d.ts — GENERATED by @palbase/backend. Do not edit.\n' +
    '// Source: the linked environment\'s stack.\n\n' +
    'declare module "@palbase/backend/stack" {\n' +
    '  interface Secrets {' + members(secrets) + '}\n\n' +
    '  interface Flags {' + members(flags) + '}\n\n' +
    '  interface Buckets {' + bucketMembers(names.buckets) + '}\n' +
    '}\n\nexport {};\n';
}
module.exports = { makeStackDts };
`

func TestGenerateStackTypes(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	root := t.TempDir()
	mustWrite(t, root, "node_modules/@palbase/backend/package.json",
		`{"name":"@palbase/backend","version":"0.0.0-test","main":"index.js"}`)
	mustWrite(t, root, "node_modules/@palbase/backend/index.js", fixtureStackPkg)

	names := StackNames{
		Secrets: []string{"STRIPE_KEY", "OPENAI_API_KEY"},
		Flags:   []string{"newCheckout"},
		Buckets: []StackBucket{{Name: "avatars", Variants: []string{}}, {Name: "my-bucket", Variants: []string{"card"}}},
	}
	if err := generateStackTypes(context.Background(), root, filepath.Join(root, "node_modules"), names); err != nil {
		t.Fatalf("generateStackTypes: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(root, "palbase-stack.d.ts"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	got := string(raw)

	for _, want := range []string{
		`declare module "@palbase/backend/stack"`,
		"OPENAI_API_KEY: true;",
		"STRIPE_KEY: true;",
		"newCheckout: true;",
		"avatars: { variants: never };",
		`"my-bucket": { variants: "card" };`, // not a bare identifier — must be quoted
		"export {};",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated file is missing %q\n---\n%s", want, got)
		}
	}

	// Sorted, so the same stack always renders the same bytes and a diff shows
	// what CHANGED rather than how the API ordered its answer.
	if strings.Index(got, "OPENAI_API_KEY") > strings.Index(got, "STRIPE_KEY") {
		t.Error("secret names must be sorted")
	}
}

// A stack that could not be asked must NOT narrow the project's types to
// nothing. Every Secrets.get() in the codebase would become a compile error and
// read as "your code is wrong" rather than "the stack was unreachable", so the
// existing file is left exactly as it was.
func TestGenerateStackTypes_LeavesTheOldFileWhenTheBridgeFails(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH")
	}
	root := t.TempDir()
	// No @palbase/backend installed → the bridge cannot render.
	previous := "// palbase-stack.d.ts — GENERATED by @palbase/backend. Do not edit.\n"
	mustWrite(t, root, "palbase-stack.d.ts", previous)

	err := generateStackTypes(context.Background(), root, filepath.Join(root, "node_modules"), StackNames{})
	if err == nil {
		t.Fatal("expected an error when @palbase/backend is absent")
	}
	if !strings.Contains(err.Error(), "@palbase/backend not found") {
		t.Errorf("the error must name the missing package, got: %v", err)
	}

	raw, readErr := os.ReadFile(filepath.Join(root, "palbase-stack.d.ts"))
	if readErr != nil {
		t.Fatalf("the previous file must survive: %v", readErr)
	}
	if string(raw) != previous {
		t.Errorf("the previous file was overwritten:\n%s", raw)
	}
}

// StackNames'in TELE çıkan şekli, üreticinin BEKLEDİĞİ şekil olmalı. İkisi iki
// repoda yaşıyor (Go tarafı burada, `stack-gen.ts` @palbase/backend'de), yani
// aralarında derleyici yok — bu test o boşluğu tutuyor.
//
// Üreticinin sözleşmesi (stack-gen.ts BucketInput): kova ya düz bir ad, ya da
// {name, variants}. Variant'sız kova BOŞ dizi taşır ve üretici onu `never`
// olarak render eder.
func TestStackNamesMarshalsInTheGeneratorsShape(t *testing.T) {
	raw, err := json.Marshal(StackNames{
		Secrets: []string{"STRIPE_KEY"},
		Flags:   []string{"new_ui"},
		Buckets: []StackBucket{
			{Name: "posts", Variants: []string{"card", "thumb"}},
			{Name: "docs", Variants: []string{}},
		},
	})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var got struct {
		Buckets []struct {
			Name     string   `json:"name"`
			Variants []string `json:"variants"`
		} `json:"buckets"`
	}
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatalf("unmarshal: %v — %s", err, raw)
	}
	if len(got.Buckets) != 2 {
		t.Fatalf("iki kova bekleniyordu: %s", raw)
	}
	if got.Buckets[0].Name != "posts" || len(got.Buckets[0].Variants) != 2 {
		t.Errorf("variant'lar tele çıkmadı: %s", raw)
	}
	// NEGATİF KONTROL: variant'sız kova `null` DEĞİL boş dizi göndermeli —
	// üretici boş birliği `never` yapar, null ise "sorulmadı" demektir.
	if got.Buckets[1].Variants == nil {
		t.Errorf("variant'sız kova null gönderdi, boş dizi göndermeliydi: %s", raw)
	}
}
