package backend

import (
	"sort"
	"strconv"
	"strings"
)

type swiftGeneratedConfig struct {
	URL    string
	APIKey string
	Branch string
	Source string
}

// emitSwift turns parsed operations into one PalbaseEndpoints.swift.
func emitSwift(ops []swiftOp) string {
	return emitSwiftWithConfig(ops, swiftGeneratedConfig{})
}

func emitSwiftWithConfig(ops []swiftOp, cfg swiftGeneratedConfig) string {
	// `auth` is reserved on `pb`; skip endpoints whose top segment is `auth`.
	var usable []swiftOp
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) > 0 && strings.ToLower(segs[0]) == "auth" {
			continue
		}
		usable = append(usable, op)
	}

	var b strings.Builder
	b.WriteString("// Generated by `palbase mobile codegen ios` — DO NOT EDIT.\n")
	b.WriteString("// Source: the active Palbase mobile contract. Re-run after branch/schema changes.\n")
	b.WriteString("import Foundation\n")
	b.WriteString("import Palbe\n\n")

	if cfg.URL != "" {
		b.WriteString("// MARK: - Generated backend config\n\n")
		b.WriteString(emitGeneratedConfig(cfg))
		b.WriteString("\n")
	}

	b.WriteString("// MARK: - Request / response types\n\n")
	b.WriteString(emitTypeTree(usable))

	b.WriteString("\n// MARK: - Namespaced calls (pb.*)\n\n")
	b.WriteString(emitNamespaceTree(usable))

	return b.String()
}

func emitGeneratedConfig(cfg swiftGeneratedConfig) string {
	branch := cfg.Branch
	if branch == "" {
		branch = "main"
	}
	source := cfg.Source
	if source == "" {
		source = "remote"
	}
	var b strings.Builder
	b.WriteString("public enum PalbaseGenerated {\n")
	b.WriteString("    public static let config = PalBackendGeneratedConfig(\n")
	b.WriteString("        url: " + swiftStringLiteral(cfg.URL) + ",\n")
	b.WriteString("        apiKey: " + swiftStringLiteral(cfg.APIKey) + ",\n")
	b.WriteString("        branch: " + swiftStringLiteral(branch) + ",\n")
	b.WriteString("        source: " + swiftStringLiteral(source) + "\n")
	b.WriteString("    )\n")
	b.WriteString("}\n")
	return b.String()
}

func swiftStringLiteral(s string) string {
	return strconv.Quote(s)
}

// --- Naming -----------------------------------------------------------------

func opSegments(opID string) []string {
	parts := strings.Split(opID, ".")
	var out []string
	for _, p := range parts {
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func typeNameOf(s string) string { return sanitize(s, true) }
func identOf(s string) string    { return escapeKeyword(sanitize(s, false)) }

func typePrefix(opID string) string {
	segs := opSegments(opID)
	parts := make([]string, len(segs))
	for i, s := range segs {
		parts[i] = typeNameOf(s)
	}
	return strings.Join(parts, ".")
}

func sanitize(s string, firstUpper bool) string {
	var parts []string
	var cur strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') {
			cur.WriteRune(ch)
		} else if cur.Len() > 0 {
			parts = append(parts, cur.String())
			cur.Reset()
		}
	}
	if cur.Len() > 0 {
		parts = append(parts, cur.String())
	}
	if len(parts) == 0 {
		if firstUpper {
			return "Op"
		}
		return "op"
	}
	var res strings.Builder
	for i, p := range parts {
		if i == 0 && !firstUpper {
			res.WriteString(strings.ToLower(p[:1]) + p[1:])
		} else {
			res.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	out := res.String()
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

var swiftKeywords = map[string]bool{
	"class": true, "struct": true, "enum": true, "func": true, "let": true, "var": true,
	"return": true, "if": true, "else": true, "for": true, "while": true, "switch": true,
	"case": true, "default": true, "import": true, "public": true, "private": true,
	"internal": true, "protocol": true, "extension": true, "self": true, "init": true,
	"deinit": true, "in": true, "where": true, "as": true, "is": true, "try": true,
	"throw": true, "throws": true, "async": true, "await": true, "nil": true, "true": true,
	"false": true, "guard": true, "defer": true, "do": true, "catch": true, "repeat": true,
	"operator": true, "associatedtype": true, "any": true,
}

func escapeKeyword(id string) string {
	if swiftKeywords[id] {
		return "`" + id + "`"
	}
	return id
}

func unbacktick(s string) string { return strings.ReplaceAll(s, "`", "") }

func indent(d int) string { return strings.Repeat("    ", d) }

// --- Type tree (merged namespaces with Input/Output at leaves) --------------

type typeNode struct {
	children map[string]*typeNode
	op       *swiftOp
}

func emitTypeTree(ops []swiftOp) string {
	root := &typeNode{children: map[string]*typeNode{}}
	for i := range ops {
		op := ops[i]
		segs := opSegments(op.operationID)
		node := root
		for _, seg := range segs {
			tn := typeNameOf(seg)
			if node.children[tn] == nil {
				node.children[tn] = &typeNode{children: map[string]*typeNode{}}
			}
			node = node.children[tn]
		}
		node.op = &op
	}

	var lines []string
	var walk func(name string, node *typeNode, depth int)
	walk = func(name string, node *typeNode, depth int) {
		lines = append(lines, indent(depth)+"public enum "+name+" {")
		if node.op != nil {
			if node.op.input != nil {
				lines = append(lines, declLines("Input", *node.op.input, depth+1)...)
			} else {
				lines = append(lines, indent(depth+1)+"public typealias Input = EmptyPayload")
			}
			if node.op.output != nil {
				lines = append(lines, declLines("Output", *node.op.output, depth+1)...)
			} else {
				lines = append(lines, indent(depth+1)+"public typealias Output = EmptyPayload")
			}
		}
		var keys []string
		for k := range node.children {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			walk(k, node.children[k], depth+1)
		}
		lines = append(lines, indent(depth)+"}")
	}
	var top []string
	for k := range root.children {
		top = append(top, k)
	}
	sort.Strings(top)
	for _, k := range top {
		walk(k, root.children[k], 0)
	}
	return strings.Join(lines, "\n") + "\n"
}

func declLines(name string, s swiftSchema, depth int) []string {
	if s.kind == "object" {
		return structLines(name, s.props, depth)
	}
	return []string{indent(depth) + "public typealias " + name + " = " + bareType(s)}
}

func structLines(name string, props []swiftProp, depth int) []string {
	var lines []string
	lines = append(lines, indent(depth)+"public struct "+name+": Codable, Sendable {")
	fd := depth + 1

	type field struct {
		ident, key, typ string
		optional        bool
	}
	var fields []field
	for _, p := range props {
		optional := !p.required || p.schema.nullable
		typ, nested := fieldType(p.schema, p.name, fd)
		lines = append(lines, nested...)
		fields = append(fields, field{ident: identOf(p.name), key: p.name, typ: typ, optional: optional})
	}
	for _, f := range fields {
		t := f.typ
		if f.optional {
			t += "?"
		}
		lines = append(lines, indent(fd)+"public let "+f.ident+": "+t)
	}
	// Memberwise init.
	var params []string
	for _, f := range fields {
		t := f.typ
		if f.optional {
			t += "? = nil"
		}
		params = append(params, f.ident+": "+t)
	}
	lines = append(lines, indent(fd)+"public init("+strings.Join(params, ", ")+") {")
	for _, f := range fields {
		lines = append(lines, indent(fd+1)+"self."+f.ident+" = "+f.ident)
	}
	lines = append(lines, indent(fd)+"}")
	// CodingKeys when any ident was sanitized away from the wire key.
	needKeys := false
	for _, f := range fields {
		if unbacktick(f.ident) != f.key {
			needKeys = true
			break
		}
	}
	if needKeys {
		lines = append(lines, indent(fd)+"enum CodingKeys: String, CodingKey {")
		for _, f := range fields {
			if unbacktick(f.ident) != f.key {
				lines = append(lines, indent(fd+1)+"case "+f.ident+" = \""+f.key+"\"")
			} else {
				lines = append(lines, indent(fd+1)+"case "+f.ident)
			}
		}
		lines = append(lines, indent(fd)+"}")
	}
	lines = append(lines, indent(depth)+"}")
	return lines
}

func fieldType(s swiftSchema, fieldName string, depth int) (string, []string) {
	switch s.kind {
	case "string":
		return "String", nil
	case "number":
		return "Double", nil
	case "integer":
		return "Int", nil
	case "boolean":
		return "Bool", nil
	case "any":
		return "AnyCodableValue", nil
	case "enum":
		typeName := typeNameOf(fieldName) + "Value"
		decl := []string{indent(depth) + "public enum " + typeName + ": String, Codable, Sendable {"}
		for _, c := range s.enumVals {
			decl = append(decl, indent(depth+1)+"case "+identOf(c)+" = \""+c+"\"")
		}
		decl = append(decl, indent(depth)+"}")
		return typeName, decl
	case "array":
		elemType, nested := fieldType(*s.elem, fieldName+"Item", depth)
		return "[" + elemType + "]", nested
	case "object":
		typeName := typeNameOf(fieldName)
		return typeName, structLines(typeName, s.props, depth)
	}
	return "AnyCodableValue", nil
}

func bareType(s swiftSchema) string {
	switch s.kind {
	case "string":
		return "String"
	case "number":
		return "Double"
	case "integer":
		return "Int"
	case "boolean":
		return "Bool"
	case "enum":
		return "String"
	case "array":
		return "[" + bareType(*s.elem) + "]"
	}
	return "AnyCodableValue"
}

// --- Namespace tree (pb.<ns>.<op>) ------------------------------------------

type nsNode struct {
	path     []string
	children map[string]*nsNode
	methods  []swiftOp
}

func emitNamespaceTree(ops []swiftOp) string {
	root := &nsNode{children: map[string]*nsNode{}}
	for _, op := range ops {
		segs := opSegments(op.operationID)
		node := root
		for _, seg := range segs[:max0(len(segs)-1)] {
			if node.children[seg] == nil {
				node.children[seg] = &nsNode{path: append(append([]string{}, node.path...), seg), children: map[string]*nsNode{}}
			}
			node = node.children[seg]
		}
		node.methods = append(node.methods, op)
	}

	// BFS collect for deterministic output.
	var all []*nsNode
	queue := []*nsNode{root}
	for len(queue) > 0 {
		n := queue[0]
		queue = queue[1:]
		all = append(all, n)
		var keys []string
		for k := range n.children {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			queue = append(queue, n.children[k])
		}
	}

	var out strings.Builder
	for _, node := range all {
		out.WriteString(renderNSNode(node))
		out.WriteString("\n")
	}
	return out.String()
}

func nsTypeName(path []string) string {
	if len(path) == 0 {
		return "PalBackendClient"
	}
	parts := make([]string, len(path))
	for i, p := range path {
		parts[i] = typeNameOf(p)
	}
	return "PB" + strings.Join(parts, "") + "Namespace"
}

func renderNSNode(node *nsNode) string {
	isRoot := len(node.path) == 0
	var lines []string
	if isRoot {
		lines = append(lines, "public extension PalBackendClient {")
	} else {
		lines = append(lines, "public struct "+nsTypeName(node.path)+": Sendable {")
		lines = append(lines, "    let _pb: PalBackendClient")
	}
	vis := "public "
	if isRoot {
		vis = "" // public extension members are implicitly public
	}
	pbRef := "_pb"
	if isRoot {
		pbRef = "self"
	}

	var keys []string
	for k := range node.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, seg := range keys {
		child := node.children[seg]
		ct := nsTypeName(child.path)
		lines = append(lines, indent(1)+vis+"var "+identOf(seg)+": "+ct+" { "+ct+"(_pb: "+pbRef+") }")
	}

	for _, op := range node.methods {
		method := identOf(opSegments(op.operationID)[len(opSegments(op.operationID))-1])
		tp := typePrefix(op.operationID)
		httpMethod := op.method
		if httpMethod == "" {
			httpMethod = "POST"
		}
		httpPath := op.path
		if httpPath == "" {
			httpPath = "/" + strings.ReplaceAll(op.operationID, ".", "/")
		}
		lines = append(lines, indent(1)+"@discardableResult")
		if op.input != nil {
			lines = append(lines, indent(1)+vis+"func "+method+"(_ input: "+tp+".Input) async throws(BackendError) -> "+tp+".Output {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"._invoke(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+", input, as: "+tp+".Output.self)")
		} else {
			lines = append(lines, indent(1)+vis+"func "+method+"() async throws(BackendError) -> "+tp+".Output {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"._invoke(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+", as: "+tp+".Output.self)")
		}
		lines = append(lines, indent(1)+"}")
	}

	lines = append(lines, "}")
	return strings.Join(lines, "\n") + "\n"
}

func max0(n int) int {
	if n < 0 {
		return 0
	}
	return n
}
