package backend

import (
	"sort"
	"strconv"
	"strings"
)

type swiftGeneratedConfig struct {
	URL    string
	APIKey string
	Branch string
	Source string
}

// emitSwift turns parsed operations into one PalbaseGenerated.swift.
//
// The Swift file is types + endpoint methods only; the runtime
// config (url / apiKey / branch / source) ships separately as
// PalbaseGenerated.json — a Bundle resource the Palbe SDK reads at
// `pb.configure()` time. The split keeps customer apps off any
// cross-module reflection: typed methods compile against the SDK,
// the SDK loads its config from the bundle at startup.
func emitSwift(ops []swiftOp) string {
	// `auth` is reserved on `pb`; skip endpoints whose top segment is `auth`.
	var usable []swiftOp
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) > 0 && strings.ToLower(segs[0]) == "auth" {
			continue
		}
		usable = append(usable, op)
	}

	var b strings.Builder
	b.WriteString("// Generated by `palbase mobile codegen ios` — DO NOT EDIT.\n")
	b.WriteString("// Source: the active Palbase mobile contract. Re-run after branch/schema changes.\n")
	b.WriteString("import Foundation\n")
	// Generated code calls the SDK's `_invoke` / `_invokeTyped` seam,
	// which is `@_spi(Generated)` on Palbe so it stays off `import Palbe`
	// autocomplete for plain customer code. The seam is reachable only via
	// this SPI import. Public types referenced in generated APIs
	// (AnyCodableValue, BackendErrorEnvelope, TypedBackendError) are now
	// plain `public` — Swift 6 rejects SPI types in public API positions.
	b.WriteString("@_spi(Generated) import Palbe\n\n")

	// Backend config (url/apiKey/branch/source) is written separately as
	// PalbaseGenerated.json next to this file and loaded by the Palbe SDK
	// from Bundle.main at `pb.configure()` time. Keeps this Swift file
	// pure types + endpoint methods; no static-let config literal that
	// the SDK would otherwise need cross-module reflection to find.

	b.WriteString("// MARK: - Request / response types\n\n")
	b.WriteString(emitTypeTree(usable))

	b.WriteString("\n// MARK: - Namespaced calls (pb.*)\n\n")
	b.WriteString(emitNamespaceTree(usable))

	return b.String()
}

func swiftStringLiteral(s string) string {
	return strconv.Quote(s)
}

// --- Naming -----------------------------------------------------------------

func opSegments(opID string) []string {
	parts := strings.Split(opID, ".")
	var out []string
	for _, p := range parts {
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func typeNameOf(s string) string { return sanitize(s, true) }
func identOf(s string) string    { return escapeKeyword(sanitize(s, false)) }

// typePrefix builds the PascalCase concatenation of all op-id segments,
// used as the BASE for top-level <Prefix>Request / <Prefix>Response /
// <Prefix>Error type names. Example: "rooms.create" → "RoomsCreate".
// Dots between segments are dropped — the user wants flat top-level
// struct names ("RoomsCreateRequest"), not nested
// "Rooms.Create.Input"-style enum trees.
func typePrefix(opID string) string {
	segs := opSegments(opID)
	parts := make([]string, len(segs))
	for i, s := range segs {
		parts[i] = typeNameOf(s)
	}
	return strings.Join(parts, "")
}

// requestTypeName / responseTypeName / errorEnumName are the three
// public top-level names per operation. Kept as small helpers so the
// emit + call sites agree without duplicating the suffix.
func requestTypeName(opID string) string  { return typePrefix(opID) + "Request" }
func responseTypeName(opID string) string { return typePrefix(opID) + "Response" }
func errorEnumName(opID string) string    { return typePrefix(opID) + "Error" }

func sanitize(s string, firstUpper bool) string {
	var parts []string
	var cur strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') {
			cur.WriteRune(ch)
		} else if cur.Len() > 0 {
			parts = append(parts, cur.String())
			cur.Reset()
		}
	}
	if cur.Len() > 0 {
		parts = append(parts, cur.String())
	}
	if len(parts) == 0 {
		if firstUpper {
			return "Op"
		}
		return "op"
	}
	var res strings.Builder
	for i, p := range parts {
		if i == 0 && !firstUpper {
			res.WriteString(strings.ToLower(p[:1]) + p[1:])
		} else {
			res.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	out := res.String()
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

var swiftKeywords = map[string]bool{
	"class": true, "struct": true, "enum": true, "func": true, "let": true, "var": true,
	"return": true, "if": true, "else": true, "for": true, "while": true, "switch": true,
	"case": true, "default": true, "import": true, "public": true, "private": true,
	"internal": true, "protocol": true, "extension": true, "self": true, "init": true,
	"deinit": true, "in": true, "where": true, "as": true, "is": true, "try": true,
	"throw": true, "throws": true, "async": true, "await": true, "nil": true, "true": true,
	"false": true, "guard": true, "defer": true, "do": true, "catch": true, "repeat": true,
	"operator": true, "associatedtype": true, "any": true,
}

func escapeKeyword(id string) string {
	if swiftKeywords[id] {
		return "`" + id + "`"
	}
	return id
}

func unbacktick(s string) string { return strings.ReplaceAll(s, "`", "") }

func indent(d int) string { return strings.Repeat("    ", d) }

// --- Top-level Request / Response / Error types ----------------------------
//
// Each operation emits its own flat trio:
//   public struct RoomsCreateRequest:  Codable, Sendable { … }
//   public struct RoomsCreateResponse: Codable, Sendable { … }
//   public enum   RoomsCreateError:    TypedBackendError    { … }
//
// Any nested object inside a request/response property is rendered as a
// `public struct <FieldName> { … }` **inside** the parent struct body
// (Swift's natural type-nesting), so the field references the short
// name directly. The struct emitter recurses depth-first, declaring
// the inner type at the same indent level as the field that uses it.
//
// Operations with no input emit no Request type; with no output emit
// no Response type; with no declared errors emit no Error enum. The
// namespace methods below match those four shapes.

func emitTypeTree(ops []swiftOp) string {
	var lines []string
	for i := range ops {
		op := ops[i]
		emitted := false
		if op.input != nil {
			lines = append(lines, topLevelDeclLines(requestTypeName(op.operationID), *op.input)...)
			emitted = true
		}
		if op.output != nil {
			if emitted {
				lines = append(lines, "")
			}
			lines = append(lines, topLevelDeclLines(responseTypeName(op.operationID), *op.output)...)
			emitted = true
		}
		if len(op.errors) > 0 {
			if emitted {
				lines = append(lines, "")
			}
			lines = append(lines, topLevelErrorEnumLines(errorEnumName(op.operationID), op.errors)...)
			emitted = true
		}
		if emitted {
			lines = append(lines, "")
		}
	}
	return strings.Join(lines, "\n")
}

// topLevelDeclLines renders one top-level type for an operation side
// (request or response). Objects become `public struct <Name>`; scalars
// or arrays (no `properties`) fall back to a `public typealias <Name> =
// <BareType>` so the call signature still reads typed.
func topLevelDeclLines(name string, s swiftSchema) []string {
	if s.kind == "object" {
		return structLines(name, s.props, 0)
	}
	return []string{"public typealias " + name + " = " + bareType(s)}
}

// topLevelErrorEnumLines renders one `public enum <Prefix>Error:
// TypedBackendError` block per operation. `enumName` is the full
// top-level name (e.g. "RoomsCreateError") so customers reference it
// directly — no nested `Rooms.Create.Error` walk.
//
// Cases with a `data` payload carry the parsed Swift type as an
// associated value (declared inside the enum body so the case
// signature can reference it by short name). Cases without are bare.
// init(envelope:) matches the wire `code` and decodes the optional
// data payload via JSON re-encoding (BackendErrorEnvelope.data is an
// AnyCodableValue; we serialise + Decode against the case's typed
// payload). Returning `nil` for an unknown code is what the SDK seam
// uses to fall through to BackendError.server.
func topLevelErrorEnumLines(enumName string, errs []swiftErrorDef) []string {
	var lines []string
	// `nonisolated` for the same Swift 6 + MainActor-default isolation
	// reason as structLines — the TypedBackendError protocol requires
	// a non-isolated `init?(envelope:)`.
	lines = append(lines, "public nonisolated enum "+enumName+": TypedBackendError {")
	fd := 1

	// Per-case data payload structs / typealiases first so the case
	// declarations below can reference them by name (Swift requires
	// the type to be in scope at the case site). Nested inside the
	// enum body so customers reference them as `<Enum>.<Name>Data`.
	for _, e := range errs {
		if e.data == nil {
			continue
		}
		typeName := typeNameOf(e.name) + "Data"
		if e.data.kind == "object" {
			lines = append(lines, structLines(typeName, e.data.props, fd)...)
		} else {
			lines = append(lines, indent(fd)+"public typealias "+typeName+" = "+bareType(*e.data))
		}
	}

	// case declarations
	for _, e := range errs {
		caseName := identOf(e.name)
		if e.data != nil {
			typeName := typeNameOf(e.name) + "Data"
			lines = append(lines, indent(fd)+"case "+caseName+"("+typeName+")")
		} else {
			lines = append(lines, indent(fd)+"case "+caseName)
		}
	}

	// init(envelope:) — match envelope.error against the declared wire code
	lines = append(lines, indent(fd)+"public init?(envelope: BackendErrorEnvelope) {")
	lines = append(lines, indent(fd+1)+"switch envelope.error {")
	for _, e := range errs {
		lines = append(lines, indent(fd+1)+"case "+swiftStringLiteral(e.code)+":")
		caseName := identOf(e.name)
		if e.data != nil {
			typeName := typeNameOf(e.name) + "Data"
			// Re-encode the AnyCodableValue payload to bytes, then decode it
			// into the typed case shape. A missing/malformed payload
			// degrades to .<case>(nil-like) ONLY when the case has no
			// required fields; otherwise nil → caller falls through to
			// BackendError.server.
			lines = append(lines, indent(fd+2)+"guard let raw = envelope.data,")
			lines = append(lines, indent(fd+2)+"      let bytes = try? JSONEncoder().encode(raw),")
			lines = append(lines, indent(fd+2)+"      let data = try? JSONDecoder.palbaseDefault.decode("+typeName+".self, from: bytes)")
			lines = append(lines, indent(fd+2)+"else { return nil }")
			lines = append(lines, indent(fd+2)+"self = ."+caseName+"(data)")
		} else {
			lines = append(lines, indent(fd+2)+"self = ."+caseName)
		}
	}
	lines = append(lines, indent(fd+1)+"default: return nil")
	lines = append(lines, indent(fd+1)+"}")
	lines = append(lines, indent(fd)+"}")

	lines = append(lines, "}")
	return lines
}

func structLines(name string, props []swiftProp, depth int) []string {
	var lines []string
	// `nonisolated` is required for SWIFT_DEFAULT_ACTOR_ISOLATION=MainActor
	// targets (Xcode 16+ Swift 6). Without it, the Codable + Sendable
	// conformances inherit main-actor isolation and the SDK's generic
	// `_invoke<O: Decodable & Sendable>` constraint can't be satisfied:
	// "main actor-isolated conformance of <X> to 'Decodable' cannot
	// satisfy conformance requirement for a 'Sendable' type parameter".
	// Wire DTOs are pure data, so non-isolated is correct.
	lines = append(lines, indent(depth)+"public nonisolated struct "+name+": Codable, Sendable {")
	fd := depth + 1

	type field struct {
		ident, key, typ string
		optional        bool
	}
	var fields []field
	for _, p := range props {
		optional := !p.required || p.schema.nullable
		typ, nested := fieldType(p.schema, p.name, fd)
		lines = append(lines, nested...)
		fields = append(fields, field{ident: identOf(p.name), key: p.name, typ: typ, optional: optional})
	}
	for _, f := range fields {
		t := f.typ
		if f.optional {
			t += "?"
		}
		lines = append(lines, indent(fd)+"public let "+f.ident+": "+t)
	}
	// Memberwise init.
	var params []string
	for _, f := range fields {
		t := f.typ
		if f.optional {
			t += "? = nil"
		}
		params = append(params, f.ident+": "+t)
	}
	lines = append(lines, indent(fd)+"public init("+strings.Join(params, ", ")+") {")
	for _, f := range fields {
		lines = append(lines, indent(fd+1)+"self."+f.ident+" = "+f.ident)
	}
	lines = append(lines, indent(fd)+"}")
	// CodingKeys when any ident was sanitized away from the wire key.
	needKeys := false
	for _, f := range fields {
		if unbacktick(f.ident) != f.key {
			needKeys = true
			break
		}
	}
	if needKeys {
		lines = append(lines, indent(fd)+"enum CodingKeys: String, CodingKey {")
		for _, f := range fields {
			if unbacktick(f.ident) != f.key {
				lines = append(lines, indent(fd+1)+"case "+f.ident+" = \""+f.key+"\"")
			} else {
				lines = append(lines, indent(fd+1)+"case "+f.ident)
			}
		}
		lines = append(lines, indent(fd)+"}")
	}
	lines = append(lines, indent(depth)+"}")
	return lines
}

func fieldType(s swiftSchema, fieldName string, depth int) (string, []string) {
	switch s.kind {
	case "string":
		return "String", nil
	case "number":
		return "Double", nil
	case "integer":
		return "Int", nil
	case "boolean":
		return "Bool", nil
	case "any":
		return "AnyCodableValue", nil
	case "enum":
		typeName := typeNameOf(fieldName) + "Value"
		decl := []string{indent(depth) + "public nonisolated enum " + typeName + ": String, Codable, Sendable {"}
		for _, c := range s.enumVals {
			decl = append(decl, indent(depth+1)+"case "+identOf(c)+" = \""+c+"\"")
		}
		decl = append(decl, indent(depth)+"}")
		return typeName, decl
	case "array":
		elemType, nested := fieldType(*s.elem, fieldName+"Item", depth)
		return "[" + elemType + "]", nested
	case "object":
		typeName := typeNameOf(fieldName)
		return typeName, structLines(typeName, s.props, depth)
	}
	return "AnyCodableValue", nil
}

func bareType(s swiftSchema) string {
	switch s.kind {
	case "string":
		return "String"
	case "number":
		return "Double"
	case "integer":
		return "Int"
	case "boolean":
		return "Bool"
	case "enum":
		return "String"
	case "array":
		return "[" + bareType(*s.elem) + "]"
	}
	return "AnyCodableValue"
}

// --- Namespace tree (pb.<ns>.<op>) ------------------------------------------

type nsNode struct {
	path     []string
	children map[string]*nsNode
	methods  []swiftOp
}

func emitNamespaceTree(ops []swiftOp) string {
	root := &nsNode{children: map[string]*nsNode{}}
	for _, op := range ops {
		segs := opSegments(op.operationID)
		node := root
		for _, seg := range segs[:max0(len(segs)-1)] {
			if node.children[seg] == nil {
				node.children[seg] = &nsNode{path: append(append([]string{}, node.path...), seg), children: map[string]*nsNode{}}
			}
			node = node.children[seg]
		}
		node.methods = append(node.methods, op)
	}

	// BFS collect for deterministic output.
	var all []*nsNode
	queue := []*nsNode{root}
	for len(queue) > 0 {
		n := queue[0]
		queue = queue[1:]
		all = append(all, n)
		var keys []string
		for k := range n.children {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			queue = append(queue, n.children[k])
		}
	}

	var out strings.Builder
	for _, node := range all {
		out.WriteString(renderNSNode(node))
		out.WriteString("\n")
	}
	return out.String()
}

func nsTypeName(path []string) string {
	if len(path) == 0 {
		return "PalBackendClient"
	}
	parts := make([]string, len(path))
	for i, p := range path {
		parts[i] = typeNameOf(p)
	}
	return "PB" + strings.Join(parts, "") + "Namespace"
}

func renderNSNode(node *nsNode) string {
	isRoot := len(node.path) == 0
	var lines []string
	if isRoot {
		lines = append(lines, "public extension PalBackendClient {")
	} else {
		lines = append(lines, "public struct "+nsTypeName(node.path)+": Sendable {")
		lines = append(lines, "    let _pb: PalBackendClient")
	}
	vis := "public "
	if isRoot {
		vis = "" // public extension members are implicitly public
	}
	pbRef := "_pb"
	if isRoot {
		pbRef = "self"
	}

	var keys []string
	for k := range node.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, seg := range keys {
		child := node.children[seg]
		ct := nsTypeName(child.path)
		lines = append(lines, indent(1)+vis+"var "+identOf(seg)+": "+ct+" { "+ct+"(_pb: "+pbRef+") }")
	}

	for _, op := range node.methods {
		method := identOf(opSegments(op.operationID)[len(opSegments(op.operationID))-1])
		reqType := requestTypeName(op.operationID)
		resType := responseTypeName(op.operationID)
		httpMethod := op.method
		if httpMethod == "" {
			httpMethod = "POST"
		}
		httpPath := op.path
		if httpPath == "" {
			httpPath = "/" + strings.ReplaceAll(op.operationID, ".", "/")
		}

		// Four shapes depending on which sides the OpenAPI op declares.
		// Old generator forced Input=EmptyPayload / Output=EmptyPayload so
		// every call looked uniform; that pushed an awkward
		//   _ = try await pb.foo.bar(EmptyPayload())
		// onto every customer even when the route is fire-and-forget. The
		// new shapes match the spec literally: no body → no Input param,
		// no response → -> Void with no @discardableResult.
		//
		// When the endpoint declared errors (defineEndpoint({errors:…}))
		// the method drops to `_invokeTyped(…, errors: <Prefix>Error.self)`
		// and removes the typed-throws constraint — the customer's `catch
		// <Prefix>Error.<case>` clause matches first, and a trailing
		// `catch let e as BackendError` covers everything else.
		typedErrors := op.errors != nil && len(op.errors) > 0
		invoke := "_invoke"
		errorsArg := ""
		throwsKw := "throws(BackendError)"
		if typedErrors {
			invoke = "_invokeTyped"
			errorsArg = ", errors: " + errorEnumName(op.operationID) + ".self"
			throwsKw = "throws" // mixed: typed enum OR BackendError, so no constraint
		}

		switch {
		case op.input != nil && op.output != nil:
			lines = append(lines, indent(1)+"@discardableResult")
			lines = append(lines, indent(1)+vis+"func "+method+"(_ input: "+reqType+") async "+throwsKw+" -> "+resType+" {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"."+invoke+"(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+", input, as: "+resType+".self"+errorsArg+")")
		case op.input != nil && op.output == nil:
			lines = append(lines, indent(1)+vis+"func "+method+"(_ input: "+reqType+") async "+throwsKw+" {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"."+invoke+"(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+", input"+errorsArg+")")
		case op.input == nil && op.output != nil:
			lines = append(lines, indent(1)+"@discardableResult")
			lines = append(lines, indent(1)+vis+"func "+method+"() async "+throwsKw+" -> "+resType+" {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"."+invoke+"(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+", as: "+resType+".self"+errorsArg+")")
		default: // no input, no output
			lines = append(lines, indent(1)+vis+"func "+method+"() async "+throwsKw+" {")
			lines = append(lines, indent(1)+"    try await "+pbRef+"."+invoke+"(method: "+swiftStringLiteral(httpMethod)+", path: "+swiftStringLiteral(httpPath)+errorsArg+")")
		}
		lines = append(lines, indent(1)+"}")
	}

	lines = append(lines, "}")
	return strings.Join(lines, "\n") + "\n"
}

func max0(n int) int {
	if n < 0 {
		return 0
	}
	return n
}
