package backend

import (
	"sort"
	"strings"
)

// tsGeneratedConfig carries the runtime config values the generated
// palbe.gen.ts writes into __configure(). Mirrors swiftGeneratedConfig but
// targets the web SDK seam. OAuth reuses the existing swiftOAuthConfig struct.
type tsGeneratedConfig struct {
	URL    string
	APIKey string
	Branch string
	OAuth  *swiftOAuthConfig
}

// emitTypeScript turns parsed operations into a palbe.gen.ts module.
// The file structure: header → imports → __configure → (types placeholder) →
// (typed errors placeholder) → __registerNamespaces → (declare module placeholder).
func emitTypeScript(ops []swiftOp, cfg tsGeneratedConfig) string {
	var b strings.Builder

	// Filter reserved top-level namespaces; collect skip comments.
	var usable []swiftOp
	var skipComments []string
	skipped := map[string]bool{}
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		ns := segs[0]
		if tsReservedTopLevel(ns) {
			if !skipped[ns] {
				skipped[ns] = true
				skipComments = append(skipComments, ns)
			}
			continue
		}
		usable = append(usable, op)
	}
	sort.Strings(skipComments)

	// --- Header ---
	b.WriteString("// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.\n")
	b.WriteString("// Source: the active Palbase mobile contract. Re-run after branch/schema changes.\n\n")

	// --- Skip comments (sorted, before imports for visibility) ---
	for _, ns := range skipComments {
		b.WriteString("// codegen: skipped reserved namespace \"")
		b.WriteString(ns)
		b.WriteString("\"\n")
	}
	if len(skipComments) > 0 {
		b.WriteString("\n")
	}

	// --- Imports ---
	b.WriteString("import type { BackendError, CallOptions } from 'palbe';\n")
	b.WriteString("import { __configure, __registerNamespaces } from 'palbe/internal';\n\n")

	// --- __configure ---
	b.WriteString(emitTSConfigure(cfg))
	b.WriteString("\n")

	// --- __registerNamespaces ---
	b.WriteString(emitTSRegistration(usable))

	return b.String()
}

// emitTSConfigure renders the __configure({…}) call.
func emitTSConfigure(cfg tsGeneratedConfig) string {
	branch := cfg.Branch
	if branch == "" {
		branch = "main"
	}
	var b strings.Builder
	b.WriteString("__configure({\n")
	b.WriteString("  url: ")
	b.WriteString(tsStringLit(cfg.URL))
	b.WriteString(",\n")
	b.WriteString("  apiKey: ")
	b.WriteString(tsStringLit(cfg.APIKey))
	b.WriteString(",\n")
	b.WriteString("  branch: ")
	b.WriteString(tsStringLit(branch))
	b.WriteString(",\n")

	if oauth := renderTSOAuth(cfg.OAuth); oauth != "" {
		b.WriteString("  oauth: {\n")
		b.WriteString(oauth)
		b.WriteString("  },\n")
	}

	b.WriteString("});\n")
	return b.String()
}

// renderTSOAuth returns the indented inner lines of the oauth block, or "" to
// omit the key entirely. Google is included only when Enabled=true and
// ClientID is non-empty. Apple is included only when Enabled=true.
func renderTSOAuth(o *swiftOAuthConfig) string {
	if o == nil {
		return ""
	}
	var b strings.Builder
	if o.Apple != nil && o.Apple.Enabled {
		b.WriteString("    apple: { enabled: true },\n")
	}
	if o.Google != nil && o.Google.Enabled && o.Google.ClientID != "" {
		b.WriteString("    google: { enabled: true, clientId: ")
		b.WriteString(tsStringLit(o.Google.ClientID))
		b.WriteString(" },\n")
	}
	return b.String()
}

// emitTSRegistration renders the __registerNamespaces({…}) call.
// Operations are grouped into a tree by operationId segments; the last segment
// is the method key and earlier segments nest as namespace objects.
// Deterministic output: namespaces and methods are alphabetically ordered
// (ops arrive sorted by operationId — we preserve that order).
func emitTSRegistration(ops []swiftOp) string {
	// Build tree: map[namespace]map[method]swiftOp.
	// We support exactly one level of namespace for now (seg[0] = ns, seg[-1] = method,
	// anything in between is also part of the ns path — join with dots for the tree key).
	type methodEntry struct {
		op         swiftOp
		methodSeg  string
		skipReason string // non-empty → emit comment, skip from tree
	}

	// nsTree: ordered list of (nsKey, methods) pairs, preserving alpha order.
	type nsEntry struct {
		nsKey   string
		methods []methodEntry
	}
	nsOrder := []string{}
	nsMap := map[string]*nsEntry{}

	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) < 2 {
			// Single-segment op — no namespace, skip with comment.
			continue
		}
		nsKey := strings.Join(segs[:len(segs)-1], ".")
		methodSeg := segs[len(segs)-1]

		// Check nested reserved.
		skip := ""
		// Check all non-first segments (the ns segments, not the top-level
		// which was already filtered; the method segment is the last).
		// Non-first segments here means segs[1:] — but the ns segments are
		// segs[0..len-2] (segs[0] already passed top-level filter). We check
		// segs[1..len-2] for nested reserved AND the method segment.
		for _, seg := range segs[1:] {
			if tsReservedNested(seg) {
				skip = seg
				break
			}
		}

		// Check body+query conflict.
		if skip == "" && op.input != nil && op.query != nil {
			skip = "__bodyquery__"
		}

		entry, exists := nsMap[nsKey]
		if !exists {
			entry = &nsEntry{nsKey: nsKey}
			nsMap[nsKey] = entry
			nsOrder = append(nsOrder, nsKey)
		}
		entry.methods = append(entry.methods, methodEntry{
			op:         op,
			methodSeg:  methodSeg,
			skipReason: skip,
		})
	}

	var b strings.Builder

	// Emit skip comments for nested-reserved / body+query ops first.
	for _, nsKey := range nsOrder {
		entry := nsMap[nsKey]
		for _, m := range entry.methods {
			if m.skipReason == "__bodyquery__" {
				b.WriteString("// codegen: skipped operation \"")
				b.WriteString(m.op.operationID)
				b.WriteString("\" (both body and query declared — unsupported)\n")
			} else if m.skipReason != "" {
				b.WriteString("// codegen: skipped operation \"")
				b.WriteString(m.op.operationID)
				b.WriteString("\" (reserved segment \"")
				b.WriteString(m.skipReason)
				b.WriteString("\")\n")
			}
		}
	}

	// Now emit the registration block. Filter out skipped methods.
	b.WriteString("__registerNamespaces({\n")
	for _, nsKey := range nsOrder {
		entry := nsMap[nsKey]

		// Collect only non-skipped methods.
		var good []methodEntry
		for _, m := range entry.methods {
			if m.skipReason == "" {
				good = append(good, m)
			}
		}
		if len(good) == 0 {
			continue
		}

		b.WriteString("  ")
		b.WriteString(nsKey)
		b.WriteString(": {\n")
		for _, m := range good {
			b.WriteString(renderTSDescriptor(m.op, m.methodSeg, 4))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("});\n")
	return b.String()
}

// renderTSDescriptor renders one method descriptor entry at the given indent
// depth (number of spaces). Single-line when no extras beyond method/path;
// multi-line when errors are present.
//
// Descriptor field rules:
//   - `method` and `path` always present
//   - `pathParams` present when op.pathParams is non-empty
//   - `input: 'none'` when op.input==nil && op.query==nil (explicit: no body, no query)
//   - `input: 'query'` when op.query!=nil (and no body; body+query conflict handled upstream)
//   - no `input` key when op.input != nil (body is the default)
//   - `errors` map when op.errors is non-empty → forces multi-line
func renderTSDescriptor(op swiftOp, methodSeg string, indentSpaces int) string {
	ind := strings.Repeat(" ", indentSpaces)

	hasErrors := len(op.errors) > 0
	hasPathParams := len(op.pathParams) > 0
	hasInput := op.input != nil
	hasQuery := op.query != nil

	// Determine input field.
	inputVal := "" // empty = omit (body default)
	if !hasInput && !hasQuery {
		inputVal = "none"
	} else if hasQuery {
		inputVal = "query"
	}

	if !hasErrors {
		// Single-line format: `methodSeg: { method: 'X', path: '...', [extras...] },`
		var parts []string
		parts = append(parts, "method: "+tsStringLit(op.method))
		parts = append(parts, "path: "+tsStringLit(op.path))
		if hasPathParams {
			parts = append(parts, "pathParams: ["+renderTSStringArray(op.pathParams)+"]")
		}
		if inputVal != "" {
			parts = append(parts, "input: "+tsStringLit(inputVal))
		}
		return ind + methodSeg + ": { " + strings.Join(parts, ", ") + " },\n"
	}

	// Multi-line format.
	var b strings.Builder
	innerInd := strings.Repeat(" ", indentSpaces+2)
	b.WriteString(ind + methodSeg + ": {\n")
	b.WriteString(innerInd + "method: " + tsStringLit(op.method) + ",\n")
	b.WriteString(innerInd + "path: " + tsStringLit(op.path) + ",\n")
	if hasPathParams {
		b.WriteString(innerInd + "pathParams: [" + renderTSStringArray(op.pathParams) + "],\n")
	}
	if inputVal != "" {
		b.WriteString(innerInd + "input: " + tsStringLit(inputVal) + ",\n")
	}
	if hasErrors {
		b.WriteString(innerInd + "errors: { ")
		// Sort errors by code for deterministic output.
		sorted := make([]swiftErrorDef, len(op.errors))
		copy(sorted, op.errors)
		sort.Slice(sorted, func(i, j int) bool { return sorted[i].code < sorted[j].code })
		for i, e := range sorted {
			if i > 0 {
				b.WriteString(", ")
			}
			className := typePrefix(op.operationID) + typeNameOf(e.name) + "Error"
			b.WriteString(e.code + ": (e) => new " + className + "(e)")
		}
		b.WriteString(" },\n")
	}
	b.WriteString(ind + "},\n")
	return b.String()
}

// renderTSStringArray renders a Go []string as TS array literal elements:
// `'a', 'b', 'c'` (no surrounding brackets — caller adds them).
func renderTSStringArray(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = tsStringLit(s)
	}
	return strings.Join(parts, ", ")
}

// tsStringLit returns a single-quoted TypeScript string literal, escaping
// backslash and single quotes (and newlines defensively).
func tsStringLit(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return "'" + s + "'"
}

// tsReservedTopLevel reports whether the top-level namespace segment is
// reserved. Case-insensitive for the iOS SDK set (auth/analytics/flags/realtime)
// + case-sensitive for the web-only set (call, upload, then) and all
// Object.prototype members.
func tsReservedTopLevel(seg string) bool {
	lower := strings.ToLower(seg)
	// iOS SDK reserved (case-insensitive).
	switch lower {
	case "auth", "analytics", "flags", "realtime":
		return true
	}
	// Web SDK reserved + Object.prototype members (case-sensitive).
	return tsReservedWebOnly(seg)
}

// tsReservedNested reports whether a non-first segment is reserved for
// nested positions. This is the Object.prototype members + `then`, but
// NOT `call` or `upload` (those are only reserved at the top level).
func tsReservedNested(seg string) bool {
	switch seg {
	case "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsReservedWebOnly contains the web-only reserved set (call/upload/then)
// plus Object.prototype members. Case-sensitive.
func tsReservedWebOnly(seg string) bool {
	switch seg {
	case "call", "upload", "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsObjectPrototypeMember reports whether seg is an Object.prototype member.
func tsObjectPrototypeMember(seg string) bool {
	switch seg {
	case "constructor", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable",
		"toLocaleString", "toString", "valueOf",
		"__proto__", "__defineGetter__", "__defineSetter__",
		"__lookupGetter__", "__lookupSetter__":
		return true
	}
	return false
}
