package backend

import (
	"os"
	"strings"
	"testing"
)

// tsFixtureOpenAPI is the shared OpenAPI fixture used for TypeScript codegen
// tests. It exercises: a FLAT verb-prefixed operationId (the live wire shape
// every deployed backend emits — must register as a root-level descriptor),
// POST with body+errors, GET with path param, GET with query params, and two
// skipped reserved namespaces (auth, toString).
const tsFixtureOpenAPI = `{
  "openapi":"3.1.0","info":{"title":"t","version":"1"},
  "paths":{
    "/hello":{"get":{"operationId":"getHello",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}},
    "/rooms/create":{"post":{"operationId":"rooms.create",
      "requestBody":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"name":{"type":"string"},"capacity":{"type":"integer"},"kind":{"type":"string","enum":["public","private"]}},
        "required":["name","kind"]}}}},
      "responses":{
        "200":{"content":{"application/json":{"schema":{"type":"object",
          "properties":{"id":{"type":"string"},"tags":{"type":"array","items":{"type":"string"}},"score":{"type":"number","nullable":true}},
          "required":["id","tags","score"]}}}},
        "409":{"content":{"application/json":{"schema":{"type":"object",
          "properties":{"error":{"type":"string","const":"room_locked"},"data":{"type":"object","properties":{"locked_until":{"type":"string"}},"required":["locked_until"]}},
          "required":["error","data"]}}}}
      },
      "x-palbase-errors":{
        "roomLocked":{"status":409,"code":"room_locked","hasData":true,"description":"Room is locked"},
        "roomFull":{"status":423,"code":"room_full","hasData":false,"description":"Room is full"}
      }}},
    "/todos/{id}":{"get":{"operationId":"todos.get",
      "parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string"}}],
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"id":{"type":"string"},"title":{"type":"string"}},
        "required":["id","title"]}}}}}}},
    "/todos":{"get":{"operationId":"todos.list",
      "parameters":[
        {"name":"done","in":"query","required":false,"schema":{"type":"boolean"}},
        {"name":"limit","in":"query","required":true,"schema":{"type":"integer"}}
      ],
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"object",
        "properties":{"id":{"type":"string"}},
        "required":["id"]}}}}}}}},
    "/auth/login":{"post":{"operationId":"auth.login",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}},
    "/ts/x":{"post":{"operationId":"toString.x",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}}
  }
}`

// tsFullCfg is the test config used for the __configure block assertions.
var tsFullCfg = tsGeneratedConfig{
	URL:    "https://abc12345m.dev.palbase.studio",
	APIKey: "pb_abc12345m_cXXXX",
	Branch: "main",
	OAuth: &swiftOAuthConfig{
		Google: &swiftOAuthGoogle{Enabled: true, ClientID: "g-123"},
	},
}

func TestEmitTypeScriptRegistration(t *testing.T) {
	ops, err := parseOpenAPIForSwift([]byte(tsFixtureOpenAPI))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	out := emitTypeScript(ops, tsFullCfg)

	// --- Header (both lines are golden-contract-exact) ---
	must(t, out, "// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.")
	must(t, out, "// Regenerate: palbase types   (or automatically via the predev/prebuild script)")

	// --- Imports ---
	must(t, out, "import type { BackendError, CallOptions } from 'palbe';")
	must(t, out, "import { __configure, __registerNamespaces } from 'palbe/internal';")

	// --- __configure block (full config with google oauth) ---
	must(t, out, "__configure({")
	must(t, out, "  url: 'https://abc12345m.dev.palbase.studio',")
	must(t, out, "  apiKey: 'pb_abc12345m_cXXXX',")
	must(t, out, "  branch: 'main',")
	must(t, out, "  oauth: {")
	must(t, out, "    google: { enabled: true, clientId: 'g-123' },")
	must(t, out, "  },")
	must(t, out, "});")

	// --- __registerNamespaces block ---
	must(t, out, "__registerNamespaces({")

	// getHello — FLAT operationId → root-level descriptor key. This is the
	// live wire shape (verb-prefixed single-segment ids); dropping it would
	// generate an empty SDK against every real backend.
	must(t, out, "  getHello: { method: 'GET', path: '/hello', input: 'none' },")

	// rooms.create — multi-line (has errors map, sorted by code)
	must(t, out, "  rooms: {")
	must(t, out, "    create: {")
	must(t, out, "      method: 'POST',")
	must(t, out, "      path: '/rooms/create',")
	must(t, out, "      errors: { room_full: (e) => new RoomsCreateRoomFullError(e), room_locked: (e) => new RoomsCreateRoomLockedError(e) },")
	must(t, out, "    },")
	must(t, out, "  },")

	// todos.get — single-line (no errors, no body, has path param)
	must(t, out, "  todos: {")
	must(t, out, "    get: { method: 'GET', path: '/todos/{id}', pathParams: ['id'], input: 'none' },")

	// todos.list — single-line (no errors, no body, has query)
	must(t, out, "    list: { method: 'GET', path: '/todos', input: 'query' },")
	must(t, out, "  },")

	must(t, out, "});")

	// --- Skip comments ---
	must(t, out, "// codegen: skipped reserved namespace \"auth\"")
	must(t, out, "// codegen: skipped reserved namespace \"toString\"")

	// Skip comments live at the TOP of the namespaces section: after the
	// __configure block, just above __registerNamespaces (golden contract).
	cfgIdx := strings.Index(out, "__configure({")
	skipIdx := strings.Index(out, `// codegen: skipped reserved namespace "auth"`)
	regIdx := strings.Index(out, "__registerNamespaces({")
	if cfgIdx == -1 || skipIdx == -1 || regIdx == -1 || cfgIdx > skipIdx || skipIdx > regIdx {
		t.Errorf("skip comments must sit between __configure and __registerNamespaces (cfg=%d skip=%d reg=%d)\n---\n%s",
			cfgIdx, skipIdx, regIdx, out)
	}

	// auth and toString must NOT appear as namespace keys in the registration block.
	// Note: "oauth:" contains "auth:" as a substring, so we check for the indented key form.
	if strings.Contains(out, "  auth:") {
		t.Errorf("auth namespace key must not appear in registration block:\n%s", out)
	}
	if strings.Contains(out, "  toString:") {
		t.Errorf("toString namespace key must not appear in registration block:\n%s", out)
	}

	// Dump for external inspection (mirrors swiftgen_test's PALBE_GEN_OUT).
	if p := os.Getenv("PALBE_TS_GEN_OUT"); p != "" {
		if err := os.WriteFile(p, []byte(out), 0o644); err != nil {
			t.Fatalf("write %s: %v", p, err)
		}
	}
}

// TestEmitTypeScriptConfigure_OAuthVariants exercises the OAuth config
// rendering: nil (no oauth key), apple-only, google disabled (omitted),
// google with empty ClientID (omitted), empty branch defaults to 'main'.
func TestEmitTypeScriptConfigure_OAuthVariants(t *testing.T) {
	ops := []swiftOp{}

	t.Run("nil oauth — no oauth key", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
		})
		if strings.Contains(out, "oauth") {
			t.Errorf("expected no oauth key when OAuth is nil, got:\n%s", out)
		}
	})

	t.Run("apple only", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Apple: &swiftOAuthApple{Enabled: true}},
		})
		must(t, out, "  oauth: {")
		must(t, out, "    apple: { enabled: true },")
		if strings.Contains(out, "google") {
			t.Errorf("google must not appear when only apple is set:\n%s", out)
		}
	})

	t.Run("google disabled — omitted", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Google: &swiftOAuthGoogle{Enabled: false, ClientID: "g-123"}},
		})
		if strings.Contains(out, "google") {
			t.Errorf("disabled google must be omitted:\n%s", out)
		}
	})

	t.Run("google empty clientId — omitted", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Google: &swiftOAuthGoogle{Enabled: true, ClientID: ""}},
		})
		if strings.Contains(out, "google") {
			t.Errorf("google with empty clientId must be omitted:\n%s", out)
		}
	})

	t.Run("empty branch defaults to main", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "",
		})
		must(t, out, "  branch: 'main',")
	})
}

// TestEmitTypeScriptRegistration_NestedReserved locks that an operation whose
// NON-first segment is a reserved-nested name (then, Object.prototype members
// excluding call/upload) is skipped with a comment.
func TestEmitTypeScriptRegistration_NestedReserved(t *testing.T) {
	ops := []swiftOp{
		{operationID: "todos.then", method: "GET", path: "/todos/then"},
		{operationID: "todos.create", method: "POST", path: "/todos/create"},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "todos.then" (reserved segment "then")`)
	// The non-skipped op todos.create must still be emitted in the registration
	// block — pinned as the FULL single-line descriptor so a regression that
	// suppresses input:'none' on an input-less POST cannot pass.
	must(t, out, "    create: { method: 'POST', path: '/todos/create', input: 'none' },")
	if strings.Contains(out, "    then:") {
		t.Errorf("reserved nested segment 'then' must not appear in registration:\n%s", out)
	}
}

// TestEmitTypeScriptRegistration_BothBodyAndQuery locks that an op with both
// requestBody and query declared is skipped with a loud comment.
func TestEmitTypeScriptRegistration_BothBodyAndQuery(t *testing.T) {
	ops := []swiftOp{
		{
			operationID: "foo.bar",
			method:      "POST",
			path:        "/foo/bar",
			input:       &swiftSchema{kind: "object"},
			query:       &swiftSchema{kind: "object"},
		},
		{
			operationID: "foo.ok",
			method:      "POST",
			path:        "/foo/ok",
			input:       &swiftSchema{kind: "object"},
		},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "foo.bar" (both body and query declared — unsupported)`)
	// The non-conflicting op foo.ok must still be emitted.
	must(t, out, "    ok: { method: 'POST'")
	if strings.Contains(out, "    bar:") {
		t.Errorf("conflicting body+query op must not appear in registration:\n%s", out)
	}
}

// TestEmitTypeScriptRegistration_TreeAndQuoting locks the real recursive
// namespace tree + tsPropKey quoting rules:
//   - 3-segment ids nest two levels deep (rooms.id.get → rooms: { id: { get } })
//     instead of emitting an invalid dot-joined `rooms.id:` key (SyntaxError);
//   - kebab-case method segments are single-quoted ('delete-all');
//   - kebab-case error codes are single-quoted in the errors map;
//   - an error CODE of __proto__ is skipped with a loud comment (even quoted,
//     a literal '__proto__': key sets the prototype in a JS object literal);
//   - duplicate error codes dedupe first-wins with a skip comment.
func TestEmitTypeScriptRegistration_TreeAndQuoting(t *testing.T) {
	ops := []swiftOp{
		{operationID: "rooms.id.get", method: "POST", path: "/rooms/id/get", input: &swiftSchema{kind: "object"}},
		{operationID: "things.boom", method: "POST", path: "/things/boom", errors: []swiftErrorDef{
			// Parse order matters for the dedupe: dupA precedes dupB, so
			// dupA wins after the stable sort by code.
			{name: "dupA", code: "dup_code", status: 400},
			{name: "dupB", code: "dup_code", status: 400},
			{name: "protoHack", code: "__proto__", status: 400},
			{name: "roomLocked", code: "room-locked", status: 409},
		}},
		{operationID: "todos.delete-all", method: "POST", path: "/todos/delete-all"},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	// 3-segment id → real nested tree, not a dot-joined `rooms.id:` key.
	must(t, out, "  rooms: {")
	must(t, out, "    id: {")
	must(t, out, "      get: { method: 'POST', path: '/rooms/id/get' },")
	if strings.Contains(out, "rooms.id:") {
		t.Errorf("dot-joined namespace key must not appear (SyntaxError in TS):\n%s", out)
	}

	// Kebab method segment quoted.
	must(t, out, "    'delete-all': { method: 'POST', path: '/todos/delete-all', input: 'none' },")

	// Errors map: kebab code quoted, dup_code first-wins (dupA), __proto__ and
	// the duplicate skipped with loud comments.
	must(t, out, "errors: { dup_code: (e) => new ThingsBoomDupAError(e), 'room-locked': (e) => new ThingsBoomRoomLockedError(e) },")
	must(t, out, `// codegen: skipped error code "__proto__"`)
	must(t, out, `// codegen: skipped duplicate error code "dup_code"`)
	if strings.Contains(out, "__proto__:") || strings.Contains(out, "'__proto__':") {
		t.Errorf("__proto__ must never appear as an object key:\n%s", out)
	}
	if strings.Contains(out, "ThingsBoomDupBError") {
		t.Errorf("duplicate error code must keep the FIRST definition (dupA), not dupB:\n%s", out)
	}
}

// TestEmitTypeScriptGolden compares the full emitTypeScript output byte-for-byte
// against testdata/palbe_gen.golden.ts. Run with UPDATE_GOLDEN=1 to regenerate.
func TestEmitTypeScriptGolden(t *testing.T) {
	ops, err := parseOpenAPIForSwift([]byte(tsFixtureOpenAPI))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	got := emitTypeScript(ops, tsFullCfg)

	goldenPath := "testdata/palbe_gen.golden.ts"
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("golden updated: %s", goldenPath)
		return
	}

	goldenBytes, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (run with UPDATE_GOLDEN=1 to create): %v", err)
	}
	want := string(goldenBytes)
	if got == want {
		return
	}
	// Print first differing line for diagnosis.
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			start := i - 2
			if start < 0 {
				start = 0
			}
			end := i + 4
			if end > len(gotLines) {
				end = len(gotLines)
			}
			t.Errorf("golden mismatch at line %d:\n  got:  %q\n  want: %q\ncontext (got lines %d-):\n%s",
				i+1, gotLines[i], wantLines[i], start+1,
				strings.Join(gotLines[start:end], "\n"))
			return
		}
	}
	if len(gotLines) != len(wantLines) {
		t.Errorf("golden mismatch: got %d lines, want %d lines", len(gotLines), len(wantLines))
	}
}

// TestEmitTypeScriptTypes is a substring battery covering type-emission rules.
func TestEmitTypeScriptTypes(t *testing.T) {
	// Extended fixture adding: optional+nullable, nested object, header op,
	// type-name collision pair, kind-mismatch collision pair.
	const fixtureExt = `{
  "openapi":"3.1.0","info":{"title":"t","version":"1"},
  "paths":{
    "/rooms/create":{"post":{"operationId":"rooms.create",
      "requestBody":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{
          "name":{"type":"string"},
          "capacity":{"type":"integer"},
          "kind":{"type":"string","enum":["public","private"]},
          "note":{"type":"string","nullable":true}
        },
        "required":["name","kind"]}}}},
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{
          "id":{"type":"string"},
          "tags":{"type":"array","items":{"type":"string"}},
          "score":{"type":"number","nullable":true},
          "owner":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}
        },
        "required":["id","tags","score","owner"]}}}}}
    }},
    "/todos":{"get":{"operationId":"todos.list",
      "parameters":[
        {"name":"done","in":"query","required":false,"schema":{"type":"boolean"}},
        {"name":"limit","in":"query","required":true,"schema":{"type":"integer"}}
      ],
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"object",
        "properties":{"id":{"type":"string"}},
        "required":["id"]}}}}}}}},
    "/files/sign":{"post":{"operationId":"files.sign",
      "parameters":[
        {"name":"if-match","in":"header","required":true,"schema":{"type":"string"}},
        {"name":"x-trace-id","in":"header","required":false,"schema":{"type":"string"}}
      ],
      "requestBody":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"path":{"type":"string"}},"required":["path"]}}}},
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"url":{"type":"string"}},"required":["url"]}}}}}}},
    "/widgets/get":{"get":{"operationId":"widgets.get",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"x":{"type":"string"}},"required":["x"]}}}}}}},
    "/widgetsGet":{"get":{"operationId":"widgetsGet",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"x":{"type":"string"}},"required":["x"]}}}}}}}
  }
}`

	ops, err := parseOpenAPIForSwift([]byte(fixtureExt))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	// optional non-required prop → `?`
	must(t, out, "capacity?: number;")

	// nullable → `| null`
	must(t, out, "score: number | null;")

	// optional + nullable → `?: T | null`
	must(t, out, "note?: string | null;")

	// enum union
	must(t, out, "kind: 'public' | 'private';")

	// array of strings
	must(t, out, "tags: string[];")

	// array-of-object response → named ResponseItem + type alias
	must(t, out, "export interface TodosListResponseItem {")
	must(t, out, "export type TodosListResponse = TodosListResponseItem[];")

	// nested object prop → inline literal
	must(t, out, "owner: { id: string };")

	// header op: required header → non-optional options arg with headers intersection
	must(t, out, "options: CallOptions & { headers: { 'if-match': string; 'x-trace-id'?: string } }")

	// type-name collision: first op wins, second skipped with comment
	// widgets.get prefix = "WidgetsGet"; widgetsGet prefix = "WidgetsGet" → collision
	must(t, out, `// codegen: skipped type "WidgetsGet" (collides with operation "widgets.get")`)
	// The second op (widgetsGet) must be absent from augmentation
	if strings.Contains(out, "widgetsGet(") {
		t.Errorf("colliding op widgetsGet must be absent from augmentation:\n%s", out)
	}

	// files.sign with required header: options NOT optional
	if strings.Contains(out, "sign(input: FilesSignRequest, options?: CallOptions") {
		t.Errorf("files.sign has required header — options must NOT be optional:\n%s", out)
	}
	must(t, out, "sign(input: FilesSignRequest, options: CallOptions")

	// all-optional headers → options?
	// (no op with all-optional headers in this fixture; tested separately below)
}

// TestEmitTypeScriptTypes_AllOptionalHeaders tests that when all headers are
// optional, the options parameter becomes optional too.
func TestEmitTypeScriptTypes_AllOptionalHeaders(t *testing.T) {
	const fixture = `{
  "openapi":"3.1.0","info":{"title":"t","version":"1"},
  "paths":{
    "/files/check":{"post":{"operationId":"files.check",
      "parameters":[
        {"name":"x-trace-id","in":"header","required":false,"schema":{"type":"string"}}
      ],
      "requestBody":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"path":{"type":"string"}},"required":["path"]}}}},
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}}
  }}`

	ops, err := parseOpenAPIForSwift([]byte(fixture))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "check(input: FilesCheckRequest, options?: CallOptions & { headers?: { 'x-trace-id'?: string } })")
}

// TestEmitTypeScriptTypes_KindMismatch tests that when an op key collides with
// an existing namespace node (e.g. "things" as namespace AND "things" as method),
// the later one (in input order) is skipped — both insertion orders.
func TestEmitTypeScriptTypes_KindMismatch(t *testing.T) {
	mkOps := func() (method, nested swiftOp) {
		method = swiftOp{operationID: "things", method: "GET", path: "/things"}
		nested = swiftOp{operationID: "things.create", method: "POST", path: "/things/create",
			input: &swiftSchema{kind: "object", props: []swiftProp{{name: "name", schema: swiftSchema{kind: "string"}, required: true}}}}
		return
	}

	t.Run("method first — nested op skipped", func(t *testing.T) {
		method, nested := mkOps()
		out := emitTypeScript([]swiftOp{method, nested}, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
		must(t, out, `// codegen: skipped operation "things.create" (key collides with existing namespace/method)`)
		must(t, out, "  things: { method: 'GET', path: '/things', input: 'none' },")
	})

	t.Run("nested first — method op skipped", func(t *testing.T) {
		method, nested := mkOps()
		out := emitTypeScript([]swiftOp{nested, method}, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
		must(t, out, `// codegen: skipped operation "things" (key collides with existing namespace/method)`)
		must(t, out, "    create: { method: 'POST', path: '/things/create' },")
	})
}

// TestEmitTypeScriptAugmentation_PathParamIdents locks that wire path-param
// names are sanitized into valid TS parameter identifiers in the augmentation.
// The names are purely positional — the runtime substitutes via the
// descriptor's pathParams (which keep the WIRE names) — so renaming is safe.
func TestEmitTypeScriptAugmentation_PathParamIdents(t *testing.T) {
	ops := []swiftOp{
		{operationID: "users.posts", method: "GET", path: "/users/{user-id}/posts", pathParams: []string{"user-id"}},
		{operationID: "keys.get", method: "GET", path: "/k/{delete}", pathParams: []string{"delete"}},
		{operationID: "items.update", method: "POST", path: "/i/{input}", pathParams: []string{"input"},
			input: &swiftSchema{kind: "object", props: []swiftProp{{name: "v", schema: swiftSchema{kind: "string"}, required: true}}}},
		{operationID: "pairs.get", method: "GET", path: "/p/{id}/{id}", pathParams: []string{"id", "id"}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	// kebab-case wire name → camelCase identifier
	must(t, out, "posts(userId: string, options?: CallOptions)")
	if strings.Contains(out, "user-id: string") {
		t.Errorf("raw kebab-case param name must not appear as a TS identifier:\n%s", out)
	}
	// TS reserved word escaped with trailing underscore
	must(t, out, "get(delete_: string, options?: CallOptions)")
	// collision with the fixed `input` arg name escaped; input arg itself unchanged
	must(t, out, "update(input_: string, input: ItemsUpdateRequest, options?: CallOptions)")
	// repeated names deduped positionally
	must(t, out, "get(id: string, id2: string, options?: CallOptions)")
	// registration keeps the WIRE names verbatim
	must(t, out, "pathParams: ['user-id']")
	must(t, out, "pathParams: ['delete']")
	must(t, out, "pathParams: ['id', 'id']")
}

// TestEmitTypeScript_NonPrimitiveQuerySkipped locks that an op whose query
// schema has a non-primitive prop (object/array/any — serializeQuery would
// throw at runtime) is skipped loudly, while enum query params stay allowed.
func TestEmitTypeScript_NonPrimitiveQuerySkipped(t *testing.T) {
	ops := []swiftOp{
		{operationID: "search.run", method: "GET", path: "/search",
			query: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "filter", schema: swiftSchema{kind: "object", props: []swiftProp{{name: "x", schema: swiftSchema{kind: "string"}, required: true}}}, required: false},
			}},
			output: &swiftSchema{kind: "object", props: []swiftProp{{name: "hits", schema: swiftSchema{kind: "number"}, required: true}}}},
		{operationID: "tags.list", method: "GET", path: "/tags",
			query: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "kind", schema: swiftSchema{kind: "enum", enumVals: []string{"a", "b"}}, required: true},
			}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "search.run" (non-primitive query parameter "filter")`)
	// Skipped op emits NO types, registration entry, or augmentation method.
	if strings.Contains(out, "SearchRun") {
		t.Errorf("skipped op must not emit types:\n%s", out)
	}
	if strings.Contains(out, "run(") || strings.Contains(out, "path: '/search'") {
		t.Errorf("skipped op must not register or augment:\n%s", out)
	}
	// Enum query props are primitive — the op survives with full typing.
	must(t, out, "list: { method: 'GET', path: '/tags', input: 'query' },")
	must(t, out, "kind: 'a' | 'b';")
}

// TestEmitTypeScript_SkippedOpsEmitNoTypes locks that type emission + the
// type-name collision seen-set run over the REGISTRABLE set: an op skipped by
// the nested-reserved filter must neither emit dead types nor squat its type
// prefix against a later op with the same prefix.
func TestEmitTypeScript_SkippedOpsEmitNoTypes(t *testing.T) {
	ops := []swiftOp{
		{operationID: "todos.then", method: "GET", path: "/todos/then",
			output: &swiftSchema{kind: "object", props: []swiftProp{{name: "a", schema: swiftSchema{kind: "string"}, required: true}}}},
		{operationID: "todosThen", method: "GET", path: "/todos-then",
			output: &swiftSchema{kind: "object", props: []swiftProp{{name: "b", schema: swiftSchema{kind: "string"}, required: true}}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "todos.then" (reserved segment "then")`)
	// The reserved-skipped op must NOT squat the TodosThen type prefix...
	if strings.Contains(out, `// codegen: skipped type "TodosThen"`) {
		t.Errorf("reserved-skipped op must not squat the type prefix:\n%s", out)
	}
	// ...nor leak its own types (prop `a` belongs only to the skipped op).
	if strings.Contains(out, "a: string") {
		t.Errorf("reserved-skipped op must not emit types:\n%s", out)
	}
	// The surviving todosThen op gets the prefix and full typing.
	must(t, out, "b: string;")
	must(t, out, "todosThen(options?: CallOptions): Promise<TodosThenResponse>;")
}

// TestEmitTypeScriptTypes_ProtoPropSkipped locks that a body property named
// __proto__ is skipped with a loud comment inside the interface (JS object-
// literal prototype foot-gun; JSON.stringify drops the key — wire-dead).
func TestEmitTypeScriptTypes_ProtoPropSkipped(t *testing.T) {
	ops := []swiftOp{
		{operationID: "things.create", method: "POST", path: "/things",
			input: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "__proto__", schema: swiftSchema{kind: "string"}, required: true},
				{name: "ok", schema: swiftSchema{kind: "boolean"}, required: true},
			}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `  // codegen: skipped property "__proto__"`)
	must(t, out, "ok: boolean;")
	if strings.Contains(out, "__proto__:") {
		t.Errorf("__proto__ must never be emitted as a property key:\n%s", out)
	}
}

// TestEmitTypeScriptTypes_AnyKind checks that `any` schema kind → `unknown`.
func TestEmitTypeScriptTypes_AnyKind(t *testing.T) {
	ops := []swiftOp{
		{operationID: "things.get", method: "GET", path: "/things",
			output: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "data", schema: swiftSchema{kind: "any"}, required: true},
			}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "data: unknown;")
}

// TestEmitTypeScriptTypes_ArrayPrimitive checks array-of-primitive → `T[]` type alias.
func TestEmitTypeScriptTypes_ArrayPrimitive(t *testing.T) {
	ops := []swiftOp{
		{operationID: "tags.list", method: "GET", path: "/tags",
			output: &swiftSchema{kind: "array", elem: &swiftSchema{kind: "string"}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "export type TagsListResponse = string[];")
	// No ResponseItem interface for primitive arrays.
	if strings.Contains(out, "ResponseItem") {
		t.Errorf("primitive array must not emit ResponseItem interface:\n%s", out)
	}
}

// TestEmitTypeScriptTypes_NullableEnum checks nullable enum wraps in parens.
func TestEmitTypeScriptTypes_NullableEnum(t *testing.T) {
	ops := []swiftOp{
		{operationID: "x.get", method: "GET", path: "/x",
			output: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "status", schema: swiftSchema{kind: "enum", nullable: true, enumVals: []string{"a", "b"}}, required: true},
			}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "status: ('a' | 'b') | null;")
}

// TestEmitTypeScriptTypes_RootMethodNoInput checks root-level no-input op augmentation.
func TestEmitTypeScriptTypes_RootMethodNoInput(t *testing.T) {
	ops := []swiftOp{
		{operationID: "getHello", method: "GET", path: "/hello",
			output: &swiftSchema{kind: "object", props: []swiftProp{
				{name: "ok", schema: swiftSchema{kind: "boolean"}, required: true},
			}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "getHello(options?: CallOptions): Promise<GetHelloResponse>;")
}

// TestEmitTypeScriptTypes_NoOutput checks that ops without output get Promise<void>.
func TestEmitTypeScriptTypes_NoOutput(t *testing.T) {
	ops := []swiftOp{
		{operationID: "things.delete", method: "DELETE", path: "/things"},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "delete(options?: CallOptions): Promise<void>;")
}

// TestEmitTypeScriptTypes_QuotedMethodKey checks that non-identifier method keys
// are quoted in the augmentation.
func TestEmitTypeScriptTypes_QuotedMethodKey(t *testing.T) {
	ops := []swiftOp{
		{operationID: "todos.delete-all", method: "DELETE", path: "/todos/all"},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})
	must(t, out, "'delete-all'(options?: CallOptions): Promise<void>;")
}

// TestEmitTypeScriptTypedErrors_ClassShape locks the typed-error class emission:
// hasData:true includes data field + this.data assignment;
// hasData:false omits them entirely; both carry name/code/status/cause.
func TestEmitTypeScriptTypedErrors_ClassShape(t *testing.T) {
	ops, err := parseOpenAPIForSwift([]byte(tsFixtureOpenAPI))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	out := emitTypeScript(ops, tsFullCfg)

	// --- hasData:true (roomLocked) ---
	must(t, out, "export class RoomsCreateRoomLockedError extends Error {")
	must(t, out, "  readonly name = 'RoomsCreateRoomLockedError';")
	must(t, out, "  readonly code = 'room_locked';")
	must(t, out, "  readonly status = 409;")
	must(t, out, "  readonly data: RoomsCreateRoomLockedData;")
	must(t, out, "  readonly cause: BackendError;")
	must(t, out, "  constructor(cause: BackendError) {")
	must(t, out, "    super(cause.message);")
	must(t, out, "    this.cause = cause;")
	must(t, out, "    this.data = cause.data as RoomsCreateRoomLockedData;")
	must(t, out, "  }")

	// --- hasData:false (roomFull) — no data field, no this.data line ---
	must(t, out, "export class RoomsCreateRoomFullError extends Error {")
	must(t, out, "  readonly name = 'RoomsCreateRoomFullError';")
	must(t, out, "  readonly code = 'room_full';")
	must(t, out, "  readonly status = 423;")
	if strings.Contains(out, "readonly data: RoomsCreateRoomFullData") {
		t.Errorf("hasData:false error must NOT have data field:\n%s", out)
	}
	if strings.Contains(out, "this.data = cause.data as RoomsCreateRoomFullData") {
		t.Errorf("hasData:false error must NOT have this.data assignment:\n%s", out)
	}

	// section header must appear
	must(t, out, "// ── Typed errors ───────────────────────────────────────────────────")

	// section must appear between Types and Namespaces
	typesIdx := strings.Index(out, "// ── Types ──")
	errorsIdx := strings.Index(out, "// ── Typed errors ──")
	nsIdx := strings.Index(out, "// ── Namespaces ──")
	if typesIdx == -1 || errorsIdx == -1 || nsIdx == -1 {
		t.Fatalf("section headers missing (types=%d errors=%d namespaces=%d)", typesIdx, errorsIdx, nsIdx)
	}
	if !(typesIdx < errorsIdx && errorsIdx < nsIdx) {
		t.Errorf("typed errors section must be between Types and Namespaces (types=%d errors=%d ns=%d)", typesIdx, errorsIdx, nsIdx)
	}
}

// TestEmitTypeScriptTypedErrors_ReservedCode locks that infra-reserved error
// codes are skipped in both the typed-errors section and the errors map.
func TestEmitTypeScriptTypedErrors_ReservedCode(t *testing.T) {
	ops := []swiftOp{
		{
			operationID: "users.login",
			method:      "POST",
			path:        "/users/login",
			errors: []swiftErrorDef{
				{name: "unauthorizedAccess", code: "unauthorized", status: 401, description: "Not authorized"},
				{name: "userLocked", code: "user_locked", status: 423, description: "User locked"},
			},
		},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	// reserved code skipped with comment in both errors section and descriptor
	must(t, out, "// codegen: skipped error code \"unauthorized\" (reserved infra code)")
	// class for reserved code must NOT be emitted
	if strings.Contains(out, "UsersLoginUnauthorizedAccessError") {
		t.Errorf("reserved infra code must not emit a class:\n%s", out)
	}
	// reserved code must NOT appear in errors map
	if strings.Contains(out, "unauthorized:") {
		t.Errorf("reserved infra code must not appear in errors map:\n%s", out)
	}
	// non-reserved code must still emit normally
	must(t, out, "export class UsersLoginUserLockedError extends Error {")
	must(t, out, "user_locked: (e) => new UsersLoginUserLockedError(e)")
}

// TestEmitTypeScriptTypedErrors_NoErrors locks that when no ops have errors,
// the Typed errors section is omitted entirely AND BackendError is NOT imported.
func TestEmitTypeScriptTypedErrors_NoErrors(t *testing.T) {
	ops := []swiftOp{
		{operationID: "getHello", method: "GET", path: "/hello",
			output: &swiftSchema{kind: "object", props: []swiftProp{{name: "ok", schema: swiftSchema{kind: "boolean"}, required: true}}}},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	// No BackendError import
	if strings.Contains(out, "BackendError") {
		t.Errorf("no errors → BackendError must NOT be in import:\n%s", out)
	}
	must(t, out, "import type { CallOptions } from 'palbe';")

	// No typed errors section
	if strings.Contains(out, "// ── Typed errors ──") {
		t.Errorf("no errors → Typed errors section must be absent:\n%s", out)
	}
}

// TestEmitTypeScriptTypedErrors_ZeroOps locks that a zero-op spec still
// emits valid TS: header + configure + empty registration.
func TestEmitTypeScriptTypedErrors_ZeroOps(t *testing.T) {
	out := emitTypeScript([]swiftOp{}, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, "// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.")
	must(t, out, "import type { CallOptions } from 'palbe';")
	must(t, out, "__configure({")
	must(t, out, "__registerNamespaces({")
	must(t, out, "__registerNamespaces({\n});")
	if strings.Contains(out, "BackendError") {
		t.Errorf("zero ops → BackendError must NOT appear:\n%s", out)
	}
	if strings.Contains(out, "// ── Typed errors ──") {
		t.Errorf("zero ops → Typed errors section must be absent:\n%s", out)
	}
}

// must is a helper that fails the test when the substring is absent.
func must(t *testing.T, out, want string) {
	t.Helper()
	if !strings.Contains(out, want) {
		t.Errorf("generated TS missing: %q\n---\n%s", want, out)
	}
}
