package backend

import (
	"regexp"
	"sort"
	"strings"
)

// tsGeneratedConfig carries the runtime config values the generated
// palbe.gen.ts writes into __configure(). Mirrors swiftGeneratedConfig but
// targets the web SDK seam. OAuth reuses the existing swiftOAuthConfig struct.
type tsGeneratedConfig struct {
	URL    string
	APIKey string
	Branch string
	OAuth  *swiftOAuthConfig
}

// emitTypeScript turns parsed operations into a palbe.gen.ts module.
// The file structure: header → imports → __configure → (types placeholder) →
// (typed errors placeholder) → namespaces section (skip comments +
// __registerNamespaces) → (declare module placeholder).
func emitTypeScript(ops []swiftOp, cfg tsGeneratedConfig) string {
	var b strings.Builder

	// Filter reserved top-level namespaces; collect skip comments.
	// Single-segment operationIds (the live wire shape — verb-prefixed ids
	// like `getHello` from the backend's OpenAPI generator) pass the same
	// filter and later register as ROOT-LEVEL descriptor keys.
	var usable []swiftOp
	var skippedNS []string
	seenSkip := map[string]bool{}
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		ns := segs[0]
		if tsReservedTopLevel(ns) {
			if !seenSkip[ns] {
				seenSkip[ns] = true
				skippedNS = append(skippedNS, ns)
			}
			continue
		}
		usable = append(usable, op)
	}
	sort.Strings(skippedNS)

	// --- Header ---
	b.WriteString("// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.\n")
	b.WriteString("// Regenerate: palbase types   (or automatically via the predev/prebuild script)\n\n")

	// --- Imports ---
	b.WriteString("import type { BackendError, CallOptions } from 'palbe';\n")
	b.WriteString("import { __configure, __registerNamespaces } from 'palbe/internal';\n\n")

	// --- __configure ---
	b.WriteString(emitTSConfigure(cfg))
	b.WriteString("\n")

	// --- Namespaces section ---
	// Skip comments sit at the TOP of this section, just above
	// __registerNamespaces (golden-contract placement).
	for _, ns := range skippedNS {
		b.WriteString("// codegen: skipped reserved namespace \"")
		b.WriteString(ns)
		b.WriteString("\"\n")
	}
	b.WriteString(emitTSRegistration(usable))

	return b.String()
}

// emitTSConfigure renders the __configure({…}) call.
func emitTSConfigure(cfg tsGeneratedConfig) string {
	branch := cfg.Branch
	if branch == "" {
		branch = "main"
	}
	var b strings.Builder
	b.WriteString("__configure({\n")
	b.WriteString("  url: ")
	b.WriteString(tsStringLit(cfg.URL))
	b.WriteString(",\n")
	b.WriteString("  apiKey: ")
	b.WriteString(tsStringLit(cfg.APIKey))
	b.WriteString(",\n")
	b.WriteString("  branch: ")
	b.WriteString(tsStringLit(branch))
	b.WriteString(",\n")

	if oauth := renderTSOAuth(cfg.OAuth); oauth != "" {
		b.WriteString("  oauth: {\n")
		b.WriteString(oauth)
		b.WriteString("  },\n")
	}

	b.WriteString("});\n")
	return b.String()
}

// renderTSOAuth returns the indented inner lines of the oauth block, or "" to
// omit the key entirely. Google is included only when Enabled=true and
// ClientID is non-empty. Apple is included only when Enabled=true.
func renderTSOAuth(o *swiftOAuthConfig) string {
	if o == nil {
		return ""
	}
	var b strings.Builder
	if o.Apple != nil && o.Apple.Enabled {
		b.WriteString("    apple: { enabled: true },\n")
	}
	if o.Google != nil && o.Google.Enabled && o.Google.ClientID != "" {
		b.WriteString("    google: { enabled: true, clientId: ")
		b.WriteString(tsStringLit(o.Google.ClientID))
		b.WriteString(" },\n")
	}
	return b.String()
}

// --- Registration tree --------------------------------------------------

// tsNode is one level of the __registerNamespaces object literal. Entries
// keep insertion order (ops arrive sorted by operationId, so rendered keys
// come out alphabetically), each entry being either a nested namespace
// (child != nil) or a method descriptor (op != nil).
type tsNode struct {
	entries []*tsEntry
	index   map[string]*tsEntry
}

type tsEntry struct {
	key   string
	child *tsNode
	op    *swiftOp
}

func newTSNode() *tsNode { return &tsNode{index: map[string]*tsEntry{}} }

// childNode returns (creating if needed) the nested namespace node for key.
func (n *tsNode) childNode(key string) *tsNode {
	if e, ok := n.index[key]; ok && e.child != nil {
		return e.child
	}
	e := &tsEntry{key: key, child: newTSNode()}
	n.entries = append(n.entries, e)
	n.index[key] = e
	return e.child
}

func (n *tsNode) addMethod(key string, op swiftOp) {
	e := &tsEntry{key: key, op: &op}
	n.entries = append(n.entries, e)
	n.index[key] = e
}

// emitTSRegistration renders the per-operation skip comments + the
// __registerNamespaces({…}) call. operationIds split on dots: the LAST
// segment is the descriptor key, earlier segments nest as namespace objects
// (a real trie — 3+ segment ids like `rooms.id.get` render
// `rooms: { id: { get: … } }`). Single-segment ids (`getHello`) become
// root-level descriptor keys — that is the live wire shape every deployed
// backend emits today, so dropping them would generate an empty SDK.
func emitTSRegistration(ops []swiftOp) string {
	root := newTSNode()
	var skipLines []string

	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		// Nested reserved check covers EVERY non-first segment — both the
		// intermediate namespace segments and the final method segment.
		// (Deliberate deviation from the plan's "namespace segment" wording:
		// the palbe runtime guards each property key it materializes, so the
		// method key must be guarded the same way.)
		skip := false
		for _, seg := range segs[1:] {
			if tsReservedNested(seg) {
				skipLines = append(skipLines,
					"// codegen: skipped operation \""+op.operationID+"\" (reserved segment \""+seg+"\")")
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		// A descriptor's `input` is single-valued: body (default) or query.
		// Declaring both is unsupported — skip loudly rather than silently
		// dropping one side.
		if op.input != nil && op.query != nil {
			skipLines = append(skipLines,
				"// codegen: skipped operation \""+op.operationID+"\" (both body and query declared — unsupported)")
			continue
		}
		node := root
		for _, seg := range segs[:len(segs)-1] {
			node = node.childNode(seg)
		}
		node.addMethod(segs[len(segs)-1], op)
	}

	var b strings.Builder
	for _, l := range skipLines {
		b.WriteString(l)
		b.WriteString("\n")
	}
	b.WriteString("__registerNamespaces({\n")
	renderTSNode(&b, root, 2)
	b.WriteString("});\n")
	return b.String()
}

// renderTSNode renders one tree level at the given indent, recursing into
// nested namespaces.
func renderTSNode(b *strings.Builder, node *tsNode, indentSpaces int) {
	ind := strings.Repeat(" ", indentSpaces)
	for _, e := range node.entries {
		if e.child != nil {
			b.WriteString(ind)
			b.WriteString(tsPropKey(e.key))
			b.WriteString(": {\n")
			renderTSNode(b, e.child, indentSpaces+2)
			b.WriteString(ind)
			b.WriteString("},\n")
			continue
		}
		b.WriteString(renderTSDescriptor(*e.op, e.key, indentSpaces))
	}
}

// renderTSDescriptor renders one method descriptor entry at the given indent
// depth (number of spaces). Single-line when no errors survive filtering;
// multi-line when an errors map is emitted.
//
// Descriptor field rules:
//   - `method` and `path` always present
//   - `pathParams` present when op.pathParams is non-empty
//   - `input: 'none'` when op.input==nil && op.query==nil (explicit: no body, no query)
//   - `input: 'query'` when op.query!=nil (and no body; body+query conflict handled upstream)
//   - no `input` key when op.input != nil (body is the default)
//   - `errors` map when liftable errors exist → forces multi-line
func renderTSDescriptor(op swiftOp, methodSeg string, indentSpaces int) string {
	ind := strings.Repeat(" ", indentSpaces)
	key := tsPropKey(methodSeg)

	// Filter + sort declared errors: stable sort by wire code (ties keep
	// parse order); duplicate codes keep the FIRST occurrence; a code of
	// `__proto__` is never emitted — even quoted, a literal '__proto__':
	// key sets the object's prototype in a JS object literal, so it is
	// skipped with a loud comment instead.
	var liftable []swiftErrorDef
	var errComments []string
	if len(op.errors) > 0 {
		sorted := make([]swiftErrorDef, len(op.errors))
		copy(sorted, op.errors)
		sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].code < sorted[j].code })
		seen := map[string]bool{}
		for _, e := range sorted {
			if e.code == "__proto__" {
				errComments = append(errComments, "// codegen: skipped error code \"__proto__\"")
				continue
			}
			if seen[e.code] {
				errComments = append(errComments, "// codegen: skipped duplicate error code \""+e.code+"\"")
				continue
			}
			seen[e.code] = true
			liftable = append(liftable, e)
		}
	}
	hasErrors := len(liftable) > 0

	hasPathParams := len(op.pathParams) > 0
	hasInput := op.input != nil
	hasQuery := op.query != nil

	// Determine input field.
	inputVal := "" // empty = omit (body default)
	if !hasInput && !hasQuery {
		inputVal = "none"
	} else if hasQuery {
		inputVal = "query"
	}

	var b strings.Builder
	if !hasErrors {
		// Single-line format: `key: { method: 'X', path: '...', [extras...] },`
		// Skip comments (all error codes filtered out) still surface above it.
		for _, c := range errComments {
			b.WriteString(ind + c + "\n")
		}
		var parts []string
		parts = append(parts, "method: "+tsStringLit(op.method))
		parts = append(parts, "path: "+tsStringLit(op.path))
		if hasPathParams {
			parts = append(parts, "pathParams: ["+renderTSStringArray(op.pathParams)+"]")
		}
		if inputVal != "" {
			parts = append(parts, "input: "+tsStringLit(inputVal))
		}
		b.WriteString(ind + key + ": { " + strings.Join(parts, ", ") + " },\n")
		return b.String()
	}

	// Multi-line format.
	innerInd := strings.Repeat(" ", indentSpaces+2)
	b.WriteString(ind + key + ": {\n")
	b.WriteString(innerInd + "method: " + tsStringLit(op.method) + ",\n")
	b.WriteString(innerInd + "path: " + tsStringLit(op.path) + ",\n")
	if hasPathParams {
		b.WriteString(innerInd + "pathParams: [" + renderTSStringArray(op.pathParams) + "],\n")
	}
	if inputVal != "" {
		b.WriteString(innerInd + "input: " + tsStringLit(inputVal) + ",\n")
	}
	for _, c := range errComments {
		b.WriteString(innerInd + c + "\n")
	}
	b.WriteString(innerInd + "errors: { ")
	for i, e := range liftable {
		if i > 0 {
			b.WriteString(", ")
		}
		className := typePrefix(op.operationID) + typeNameOf(e.name) + "Error"
		b.WriteString(tsPropKey(e.code) + ": (e) => new " + className + "(e)")
	}
	b.WriteString(" },\n")
	b.WriteString(ind + "},\n")
	return b.String()
}

// renderTSStringArray renders a Go []string as TS array literal elements:
// `'a', 'b', 'c'` (no surrounding brackets — caller adds them).
func renderTSStringArray(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = tsStringLit(s)
	}
	return strings.Join(parts, ", ")
}

// tsBareKeyRe matches identifiers that are valid bare TS object keys.
var tsBareKeyRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// tsPropKey renders an object-literal property key: bare when it is a valid
// identifier, single-quoted via tsStringLit otherwise (kebab-case segments,
// codes with dots, …).
func tsPropKey(name string) string {
	if tsBareKeyRe.MatchString(name) {
		return name
	}
	return tsStringLit(name)
}

// tsStringLit returns a single-quoted TypeScript string literal, escaping
// backslash and single quotes (and newlines/carriage returns defensively).
func tsStringLit(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return "'" + s + "'"
}

// tsReservedTopLevel reports whether the top-level namespace segment is
// reserved. Case-insensitive for the iOS SDK set (auth/analytics/flags/realtime)
// + case-sensitive for the web-only set (call, upload, then) and all
// Object.prototype members.
func tsReservedTopLevel(seg string) bool {
	lower := strings.ToLower(seg)
	// iOS SDK reserved (case-insensitive).
	switch lower {
	case "auth", "analytics", "flags", "realtime":
		return true
	}
	// Web SDK reserved + Object.prototype members (case-sensitive).
	return tsReservedWebOnly(seg)
}

// tsReservedNested reports whether a non-first segment is reserved for
// nested positions. This is the Object.prototype members + `then`, but
// NOT `call` or `upload` (those are only reserved at the top level).
// Applied to every non-first segment including the final method segment —
// see emitTSRegistration for why.
func tsReservedNested(seg string) bool {
	switch seg {
	case "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsReservedWebOnly contains the web-only reserved set (call/upload/then)
// plus Object.prototype members. Case-sensitive.
func tsReservedWebOnly(seg string) bool {
	switch seg {
	case "call", "upload", "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsObjectPrototypeMember reports whether seg is an Object.prototype member.
func tsObjectPrototypeMember(seg string) bool {
	switch seg {
	case "constructor", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable",
		"toLocaleString", "toString", "valueOf",
		"__proto__", "__defineGetter__", "__defineSetter__",
		"__lookupGetter__", "__lookupSetter__":
		return true
	}
	return false
}
