package backend

import (
	"strings"
	"testing"
)

// tsFixtureOpenAPI is the shared OpenAPI fixture used for TypeScript codegen
// tests. It exercises: POST with body+errors, GET with path param, GET with
// query params, and two skipped reserved namespaces (auth, toString).
const tsFixtureOpenAPI = `{
  "openapi":"3.1.0","info":{"title":"t","version":"1"},
  "paths":{
    "/rooms/create":{"post":{"operationId":"rooms.create",
      "requestBody":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"name":{"type":"string"},"capacity":{"type":"integer"},"kind":{"type":"string","enum":["public","private"]}},
        "required":["name","kind"]}}}},
      "responses":{
        "200":{"content":{"application/json":{"schema":{"type":"object",
          "properties":{"id":{"type":"string"},"tags":{"type":"array","items":{"type":"string"}},"score":{"type":"number","nullable":true}},
          "required":["id","tags","score"]}}}},
        "409":{"content":{"application/json":{"schema":{"type":"object",
          "properties":{"error":{"type":"string","const":"room_locked"},"data":{"type":"object","properties":{"locked_until":{"type":"string"}},"required":["locked_until"]}},
          "required":["error","data"]}}}}
      },
      "x-palbase-errors":{"roomLocked":{"status":409,"code":"room_locked","hasData":true,"description":"Room is locked"}}}},
    "/todos/{id}":{"get":{"operationId":"todos.get",
      "parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string"}}],
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object",
        "properties":{"id":{"type":"string"},"title":{"type":"string"}},
        "required":["id","title"]}}}}}}},
    "/todos":{"get":{"operationId":"todos.list",
      "parameters":[
        {"name":"done","in":"query","required":false,"schema":{"type":"boolean"}},
        {"name":"limit","in":"query","required":true,"schema":{"type":"integer"}}
      ],
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"object",
        "properties":{"id":{"type":"string"}},
        "required":["id"]}}}}}}}},
    "/auth/login":{"post":{"operationId":"auth.login",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}},
    "/ts/x":{"post":{"operationId":"toString.x",
      "responses":{"200":{"content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}}}}}}}
  }
}`

// tsFullCfg is the test config used for the __configure block assertions.
var tsFullCfg = tsGeneratedConfig{
	URL:    "https://abc12345m.dev.palbase.studio",
	APIKey: "pb_abc12345m_cXXXX",
	Branch: "main",
	OAuth: &swiftOAuthConfig{
		Google: &swiftOAuthGoogle{Enabled: true, ClientID: "g-123"},
	},
}

func TestEmitTypeScriptRegistration(t *testing.T) {
	ops, err := parseOpenAPIForSwift([]byte(tsFixtureOpenAPI))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	out := emitTypeScript(ops, tsFullCfg)

	// --- Header ---
	must(t, out, "// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.")

	// --- Imports ---
	must(t, out, "import type { BackendError, CallOptions } from 'palbe';")
	must(t, out, "import { __configure, __registerNamespaces } from 'palbe/internal';")

	// --- __configure block (full config with google oauth) ---
	must(t, out, "__configure({")
	must(t, out, "  url: 'https://abc12345m.dev.palbase.studio',")
	must(t, out, "  apiKey: 'pb_abc12345m_cXXXX',")
	must(t, out, "  branch: 'main',")
	must(t, out, "  oauth: {")
	must(t, out, "    google: { enabled: true, clientId: 'g-123' },")
	must(t, out, "  },")
	must(t, out, "});")

	// --- __registerNamespaces block ---
	must(t, out, "__registerNamespaces({")

	// rooms.create — multi-line (has errors map)
	must(t, out, "  rooms: {")
	must(t, out, "    create: {")
	must(t, out, "      method: 'POST',")
	must(t, out, "      path: '/rooms/create',")
	must(t, out, "      errors: { room_locked: (e) => new RoomsCreateRoomLockedError(e) },")
	must(t, out, "    },")
	must(t, out, "  },")

	// todos.get — single-line (no errors, no body, has path param)
	must(t, out, "  todos: {")
	must(t, out, "    get: { method: 'GET', path: '/todos/{id}', pathParams: ['id'], input: 'none' },")

	// todos.list — single-line (no errors, no body, has query)
	must(t, out, "    list: { method: 'GET', path: '/todos', input: 'query' },")
	must(t, out, "  },")

	must(t, out, "});")

	// --- Skip comments ---
	must(t, out, "// codegen: skipped reserved namespace \"auth\"")
	must(t, out, "// codegen: skipped reserved namespace \"toString\"")

	// auth and toString must NOT appear as namespace keys in the registration block.
	// Note: "oauth:" contains "auth:" as a substring, so we check for the indented key form.
	if strings.Contains(out, "  auth:") {
		t.Errorf("auth namespace key must not appear in registration block:\n%s", out)
	}
	if strings.Contains(out, "  toString:") {
		t.Errorf("toString namespace key must not appear in registration block:\n%s", out)
	}
}

// TestEmitTypeScriptConfigure_OAuthVariants exercises the OAuth config
// rendering: nil (no oauth key), apple-only, google disabled (omitted),
// google with empty ClientID (omitted), empty branch defaults to 'main'.
func TestEmitTypeScriptConfigure_OAuthVariants(t *testing.T) {
	ops := []swiftOp{}

	t.Run("nil oauth — no oauth key", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
		})
		if strings.Contains(out, "oauth") {
			t.Errorf("expected no oauth key when OAuth is nil, got:\n%s", out)
		}
	})

	t.Run("apple only", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Apple: &swiftOAuthApple{Enabled: true}},
		})
		must(t, out, "  oauth: {")
		must(t, out, "    apple: { enabled: true },")
		if strings.Contains(out, "google") {
			t.Errorf("google must not appear when only apple is set:\n%s", out)
		}
	})

	t.Run("google disabled — omitted", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Google: &swiftOAuthGoogle{Enabled: false, ClientID: "g-123"}},
		})
		if strings.Contains(out, "google") {
			t.Errorf("disabled google must be omitted:\n%s", out)
		}
	})

	t.Run("google empty clientId — omitted", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "main",
			OAuth: &swiftOAuthConfig{Google: &swiftOAuthGoogle{Enabled: true, ClientID: ""}},
		})
		if strings.Contains(out, "google") {
			t.Errorf("google with empty clientId must be omitted:\n%s", out)
		}
	})

	t.Run("empty branch defaults to main", func(t *testing.T) {
		out := emitTypeScript(ops, tsGeneratedConfig{
			URL: "https://x.example.com", APIKey: "pb_x_cABC", Branch: "",
		})
		must(t, out, "  branch: 'main',")
	})
}

// TestEmitTypeScriptRegistration_NestedReserved locks that an operation whose
// NON-first segment is a reserved-nested name (then, Object.prototype members
// excluding call/upload) is skipped with a comment.
func TestEmitTypeScriptRegistration_NestedReserved(t *testing.T) {
	ops := []swiftOp{
		{operationID: "todos.then", method: "GET", path: "/todos/then"},
		{operationID: "todos.create", method: "POST", path: "/todos/create"},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "todos.then" (reserved segment "then")`)
	// The non-skipped op todos.create must still be emitted in the registration
	// block — pinned as the FULL single-line descriptor so a regression that
	// suppresses input:'none' on an input-less POST cannot pass.
	must(t, out, "    create: { method: 'POST', path: '/todos/create', input: 'none' },")
	if strings.Contains(out, "    then:") {
		t.Errorf("reserved nested segment 'then' must not appear in registration:\n%s", out)
	}
}

// TestEmitTypeScriptRegistration_BothBodyAndQuery locks that an op with both
// requestBody and query declared is skipped with a loud comment.
func TestEmitTypeScriptRegistration_BothBodyAndQuery(t *testing.T) {
	ops := []swiftOp{
		{
			operationID: "foo.bar",
			method:      "POST",
			path:        "/foo/bar",
			input:       &swiftSchema{kind: "object"},
			query:       &swiftSchema{kind: "object"},
		},
		{
			operationID: "foo.ok",
			method:      "POST",
			path:        "/foo/ok",
			input:       &swiftSchema{kind: "object"},
		},
	}
	out := emitTypeScript(ops, tsGeneratedConfig{URL: "https://x.example.com", APIKey: "k", Branch: "main"})

	must(t, out, `// codegen: skipped operation "foo.bar" (both body and query declared — unsupported)`)
	// The non-conflicting op foo.ok must still be emitted.
	must(t, out, "    ok: { method: 'POST'")
	if strings.Contains(out, "    bar:") {
		t.Errorf("conflicting body+query op must not appear in registration:\n%s", out)
	}
}

// must is a helper that fails the test when the substring is absent.
func must(t *testing.T, out, want string) {
	t.Helper()
	if !strings.Contains(out, want) {
		t.Errorf("generated TS missing: %q\n---\n%s", want, out)
	}
}
