package backend

import (
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// tsGeneratedConfig carries the runtime config values the generated
// palbe.gen.ts writes into __configure(). Mirrors swiftGeneratedConfig but
// targets the web SDK seam. OAuth reuses the existing swiftOAuthConfig struct.
type tsGeneratedConfig struct {
	URL    string
	APIKey string
	Branch string
	OAuth  *swiftOAuthConfig
}

// emitTypeScript turns parsed operations into a palbe.gen.ts module.
// The file structure:
//   header → imports → __configure → types section → typed-errors section →
//   namespaces section (skip comments + __registerNamespaces) → declare module
func emitTypeScript(ops []swiftOp, cfg tsGeneratedConfig) string {
	// Filter reserved top-level namespaces; collect skip comments.
	// Single-segment operationIds (the live wire shape — verb-prefixed ids
	// like `getHello` from the backend's OpenAPI generator) pass the same
	// filter and later register as ROOT-LEVEL descriptor keys.
	// Skip-comment dedup is case-insensitive (swiftemit parity — auth/Auth
	// are the same reserved surface); the first-seen casing is printed.
	var usable []swiftOp
	var skippedNS []string
	seenSkip := map[string]bool{}
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		ns := segs[0]
		if tsReservedTopLevel(ns) {
			key := strings.ToLower(ns)
			if !seenSkip[key] {
				seenSkip[key] = true
				skippedNS = append(skippedNS, ns)
			}
			continue
		}
		usable = append(usable, op)
	}
	sort.Strings(skippedNS)

	// --- Per-operation gates ---
	// Nested-reserved / body+query / non-primitive-query / kind-mismatch
	// filtering happens BEFORE type emission, so skipped ops neither emit
	// dead types nor squat type-name prefixes against later ops.
	candidates, opSkips := filterTSOps(usable)

	// --- Build all content sections FIRST (in-memory), so the import lines
	// can be derived from what is ACTUALLY emitted. A pre-scan is not enough:
	// an error-bearing op dropped by the nested-reserved or type-collision
	// gates must not leave a stray `BackendError` import behind (TS6196 for
	// consumers compiling with noUnusedLocals).
	typesOut, collisionSkips, typeCollisionOps := emitTSTypes(candidates)

	// Type-collision ops have no usable types — they must not be callable-typed.
	var registerable []swiftOp
	for _, op := range candidates {
		if !typeCollisionOps[op.operationID] {
			registerable = append(registerable, op)
		}
	}

	errorsOut, classCount := emitTSTypedErrors(registerable)

	// --- Assemble ---
	var b strings.Builder

	// Header.
	b.WriteString("// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.\n")
	b.WriteString("// Regenerate: palbase types   (or automatically via the predev/prebuild script)\n")

	// Imports. `BackendError` is referenced only by emitted error classes;
	// `CallOptions` only by augmentation method signatures. When neither is
	// used, the whole `import type ... from '@palbase/web'` line is omitted — the
	// runtime import from '@palbase/web/internal' always stays.
	var typeImports []string
	if classCount > 0 {
		typeImports = append(typeImports, "BackendError")
	}
	if len(registerable) > 0 {
		typeImports = append(typeImports, "CallOptions")
	}
	if len(typeImports) > 0 {
		b.WriteString("import type { " + strings.Join(typeImports, ", ") + " } from '@palbase/web';\n")
	}
	b.WriteString("import { __configure, __registerNamespaces } from '@palbase/web/internal';\n\n")

	// __configure.
	b.WriteString(emitTSConfigure(cfg))
	b.WriteString("\n")

	// Types + typed errors (either may be empty).
	b.WriteString(typesOut)
	b.WriteString(errorsOut)

	// Namespaces section.
	b.WriteString("// ── Namespaces ─────────────────────────────────────────────────────\n\n")
	// Skip comments: reserved-namespace, then per-op gates, then type collisions.
	for _, ns := range skippedNS {
		b.WriteString("// codegen: skipped reserved namespace \"")
		b.WriteString(ns)
		b.WriteString("\"\n")
	}
	for _, l := range opSkips {
		b.WriteString(l)
		b.WriteString("\n")
	}
	for _, c := range collisionSkips {
		b.WriteString(c)
		b.WriteString("\n")
	}
	b.WriteString(emitTSRegistration(registerable))

	// declare module augmentation — omitted entirely when nothing registers:
	// an empty `interface PB {}` block is noise and CallOptions would be an
	// unused import.
	if len(registerable) > 0 {
		b.WriteString("\n")
		b.WriteString(emitTSAugmentation(registerable))
	}

	return b.String()
}

// emitTSConfigure renders the __configure({…}) call.
func emitTSConfigure(cfg tsGeneratedConfig) string {
	branch := cfg.Branch
	if branch == "" {
		branch = "main"
	}
	var b strings.Builder
	b.WriteString("__configure({\n")
	b.WriteString("  url: ")
	b.WriteString(tsStringLit(cfg.URL))
	b.WriteString(",\n")
	b.WriteString("  apiKey: ")
	b.WriteString(tsStringLit(cfg.APIKey))
	b.WriteString(",\n")
	b.WriteString("  branch: ")
	b.WriteString(tsStringLit(branch))
	b.WriteString(",\n")

	if oauth := renderTSOAuth(cfg.OAuth); oauth != "" {
		b.WriteString("  oauth: {\n")
		b.WriteString(oauth)
		b.WriteString("  },\n")
	}

	b.WriteString("});\n")
	return b.String()
}

// renderTSOAuth returns the indented inner lines of the oauth block, or "" to
// omit the key entirely. Google is included only when Enabled=true and
// ClientID is non-empty. Apple is included only when Enabled=true.
func renderTSOAuth(o *swiftOAuthConfig) string {
	if o == nil {
		return ""
	}
	var b strings.Builder
	if o.Apple != nil && o.Apple.Enabled {
		b.WriteString("    apple: { enabled: true },\n")
	}
	if o.Google != nil && o.Google.Enabled && o.Google.ClientID != "" {
		b.WriteString("    google: { enabled: true, clientId: ")
		b.WriteString(tsStringLit(o.Google.ClientID))
		b.WriteString(" },\n")
	}
	return b.String()
}

// --- Per-operation gates ------------------------------------------------

// filterTSOps applies the per-op gates that decide whether an operation can
// register at all: reserved nested segments, body+query conflict, query
// params the runtime's serializeQuery cannot handle, and namespace/method
// kind mismatches (a key claimed as both). Returns the surviving ops (input
// order preserved) plus loud skip-comment lines. Type emission and the
// collision seen-set run over the SURVIVING set only.
func filterTSOps(ops []swiftOp) ([]swiftOp, []string) {
	var out []swiftOp
	var skips []string
	root := newTSNode() // shape-only trie for kind-mismatch detection

	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		// Nested reserved check covers EVERY non-first segment — both the
		// intermediate namespace segments and the final method segment
		// (the palbe runtime guards each property key it materializes).
		skip := false
		for _, seg := range segs[1:] {
			if tsReservedNested(seg) {
				skips = append(skips,
					"// codegen: skipped operation \""+op.operationID+"\" (reserved segment \""+seg+"\")")
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		// A descriptor's `input` is single-valued: body (default) or query.
		if op.input != nil && op.query != nil {
			skips = append(skips,
				"// codegen: skipped operation \""+op.operationID+"\" (both body and query declared — unsupported)")
			continue
		}
		// Non-primitive query params would make the runtime's serializeQuery
		// throw (it String()s values) — skip the whole op loudly.
		if op.query != nil {
			if bad, found := firstNonPrimitiveQueryProp(*op.query); found {
				skips = append(skips,
					"// codegen: skipped operation \""+op.operationID+"\" (non-primitive query parameter \""+bad+"\")")
				continue
			}
		}
		// Kind-mismatch: a key claimed as both namespace and method.
		node := root
		mismatch := false
		for _, seg := range segs[:len(segs)-1] {
			if node = node.childNode(seg); node == nil {
				mismatch = true
				break
			}
		}
		if mismatch || !node.addMethod(segs[len(segs)-1], op) {
			skips = append(skips,
				"// codegen: skipped operation \""+op.operationID+"\" (key collides with existing namespace/method)")
			continue
		}
		out = append(out, op)
	}
	return out, skips
}

// firstNonPrimitiveQueryProp returns the name of the first query property
// whose schema cannot be serialized into a query string (anything beyond
// string/number/integer/boolean/enum), or found=false when all are primitive.
func firstNonPrimitiveQueryProp(q swiftSchema) (name string, found bool) {
	for _, p := range q.props {
		switch p.schema.kind {
		case "string", "number", "integer", "boolean", "enum":
			// primitive — serializeQuery handles it
		default:
			return p.name, true
		}
	}
	return "", false
}

// --- Types section ----------------------------------------------------------

// emitTSTypes emits the `// ── Types ──` section: one named interface or type
// alias per op schema (request, response, query, error-data). Returns:
//   - the rendered section string (empty when no ops produce types)
//   - collision skip comment lines (for ops whose typePrefix collides with a
//     previously seen one — these ops must also be excluded from registration
//     and augmentation)
//   - the set of colliding op IDs (map[opID]true)
func emitTSTypes(ops []swiftOp) (section string, collisionSkips []string, collisionOps map[string]bool) {
	collisionOps = map[string]bool{}
	// seenPrefix maps PascalCase typePrefix → first operationID that claimed it.
	seenPrefix := map[string]string{}

	var lines []string

	for _, op := range ops {
		pfx := typePrefix(op.operationID)
		if first, ok := seenPrefix[pfx]; ok {
			collisionSkips = append(collisionSkips,
				"// codegen: skipped type \""+pfx+"\" (collides with operation \""+first+"\")")
			collisionOps[op.operationID] = true
			continue
		}
		seenPrefix[pfx] = op.operationID

		// Request type (input body).
		if op.input != nil {
			lines = append(lines, tsNamedTypeLines(pfx+"Request", *op.input)...)
		}

		// Query type (emitted before Response, per golden contract order).
		if op.query != nil {
			lines = append(lines, tsNamedTypeLines(pfx+"Query", *op.query)...)
		}

		// Response type (output).
		if op.output != nil {
			lines = append(lines, tsResponseTypeLines(pfx, *op.output)...)
		}

		// Error data interfaces (after response) — only for errors that
		// actually lift. Reserved-code / duplicate-code / duplicate-class-name
		// errors emit no class, so a Data interface would be an orphan.
		liftable, _ := tsLiftableErrors(op)
		for _, e := range liftable {
			if e.data == nil {
				continue
			}
			dataName := pfx + typeNameOf(e.name) + "Data"
			docComment := "/** " + e.code + " (" + strconv.Itoa(e.status) + "): " + e.description + " */"
			lines = append(lines, docComment)
			lines = append(lines, tsNamedTypeLines(dataName, *e.data)...)
		}
	}

	if len(lines) == 0 {
		return "", collisionSkips, collisionOps
	}

	var b strings.Builder
	b.WriteString("// ── Types ──────────────────────────────────────────────────────────\n\n")
	for _, l := range lines {
		b.WriteString(l)
		b.WriteString("\n")
	}
	// Note: each type block ends with an empty-string entry that renders as a
	// blank separator line. No extra trailing newline needed here.
	return b.String(), collisionSkips, collisionOps
}

// tsNamedTypeLines renders a named top-level type declaration: `export interface`
// for object schemas, `export type` alias otherwise.
func tsNamedTypeLines(name string, s swiftSchema) []string {
	if s.kind == "object" {
		return tsInterfaceLines(name, s)
	}
	return []string{"export type " + name + " = " + tsTypeOf(s) + ";", ""}
}

// tsResponseTypeLines handles the special case where a response is an array of
// objects: emits `<Prefix>ResponseItem` interface + `<Prefix>Response` alias.
func tsResponseTypeLines(pfx string, s swiftSchema) []string {
	if s.kind == "array" && s.elem != nil && s.elem.kind == "object" {
		var lines []string
		lines = append(lines, tsInterfaceLines(pfx+"ResponseItem", *s.elem)...)
		lines = append(lines, "export type "+pfx+"Response = "+pfx+"ResponseItem[];", "")
		return lines
	}
	return tsNamedTypeLines(pfx+"Response", s)
}

// tsInterfaceLines renders `export interface Name { ... }` with sorted props.
// A property named __proto__ is skipped loudly: writing it in a JS object
// literal sets the prototype, and JSON.stringify drops it — wire-dead anyway.
func tsInterfaceLines(name string, s swiftSchema) []string {
	var lines []string
	lines = append(lines, "export interface "+name+" {")
	for _, p := range s.props {
		if p.name == "__proto__" {
			lines = append(lines, "  // codegen: skipped property \"__proto__\"")
			continue
		}
		opt := ""
		if !p.required {
			opt = "?"
		}
		lines = append(lines, "  "+tsPropKey(p.name)+opt+": "+tsTypeOf(p.schema)+";")
	}
	lines = append(lines, "}", "")
	return lines
}

// tsTypeOf converts a swiftSchema to its TypeScript type string.
// For NESTED object schemas (appearing as property values) it emits an inline
// literal `{ k: T; ... }` rather than a named interface.
func tsTypeOf(s swiftSchema) string {
	switch s.kind {
	case "string":
		if s.nullable {
			return "string | null"
		}
		return "string"
	case "number", "integer":
		if s.nullable {
			return "number | null"
		}
		return "number"
	case "boolean":
		if s.nullable {
			return "boolean | null"
		}
		return "boolean"
	case "enum":
		union := tsEnumUnion(s.enumVals)
		if s.nullable {
			return "(" + union + ") | null"
		}
		return union
	case "array":
		if s.elem == nil {
			if s.nullable {
				return "unknown[] | null"
			}
			return "unknown[]"
		}
		elem := tsTypeOf(*s.elem)
		// Parenthesise union element types (enum or nullable) so `T[]` parses correctly.
		if strings.Contains(elem, " | ") || strings.HasPrefix(elem, "(") {
			elem = "(" + elem + ")"
		}
		arr := elem + "[]"
		if s.nullable {
			return arr + " | null"
		}
		return arr
	case "object":
		inline := tsInlineObject(s)
		if s.nullable {
			return inline + " | null"
		}
		return inline
	default: // "any" or unknown
		if s.nullable {
			return "unknown | null"
		}
		return "unknown"
	}
}

// tsEnumUnion renders an enum schema as `'a' | 'b'` (no parens — caller wraps).
func tsEnumUnion(vals []string) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = tsStringLit(v)
	}
	return strings.Join(parts, " | ")
}

// tsInlineObject renders `{ k: T; k2?: U }` for a nested object schema.
// __proto__ props are dropped here too (same foot-gun as tsInterfaceLines;
// no comment slot inside a single-line literal).
func tsInlineObject(s swiftSchema) string {
	var parts []string
	for _, p := range s.props {
		if p.name == "__proto__" {
			continue
		}
		opt := ""
		if !p.required {
			opt = "?"
		}
		parts = append(parts, tsPropKey(p.name)+opt+": "+tsTypeOf(p.schema))
	}
	if len(parts) == 0 {
		return "Record<string, unknown>"
	}
	return "{ " + strings.Join(parts, "; ") + " }"
}

// tsInfraReservedCodes is the set of error codes reserved by the palbe
// runtime infrastructure. Emitting a class for these would shadow or
// collide with palbe's own error-handling seams, so they are skipped with
// a loud inline comment.
var tsInfraReservedCodes = map[string]bool{
	"not_configured":         true,
	"network_error":          true,
	"decode_error":           true,
	"validation_error":       true,
	"unauthorized":           true,
	"rate_limited":           true,
	"invalid_endpoint_name":  true,
	"unsupported_get_input":  true,
	"missing_path_param":     true,
	"unexpected_argument":    true,
	"invalid_query_value":    true,
	"reserved_namespace":     true,
	"invalid_namespace_tree": true,
	"aborted":                true,
	"http_error":             true,
}

// tsLiftableErrors applies ALL per-op error filters in one place so the
// typed-errors section, the Data-interface emission, and the descriptor's
// errors map always agree on the surviving set:
//   - stable sort by wire code (ties keep parse order)
//   - `__proto__` codes dropped (object-literal prototype foot-gun)
//   - reserved infra codes dropped (would shadow palbe's own error handling)
//   - duplicate wire codes: first-wins
//   - duplicate CLASS names (e.g. roomLocked + room_locked both PascalCase to
//     RoomLocked → TS2300 duplicate identifier): first-wins
//
// Returns the surviving defs plus the loud skip-comment lines, which are
// rendered at the DESCRIPTOR site in the registration block (single home for
// all error-skip commentary — the class section skips silently).
func tsLiftableErrors(op swiftOp) (liftable []swiftErrorDef, comments []string) {
	if len(op.errors) == 0 {
		return nil, nil
	}
	sorted := make([]swiftErrorDef, len(op.errors))
	copy(sorted, op.errors)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].code < sorted[j].code })
	seenCode := map[string]bool{}
	seenClass := map[string]string{} // PascalCase class-name stem → first error name
	for _, e := range sorted {
		if e.code == "__proto__" {
			comments = append(comments, "// codegen: skipped error code \"__proto__\"")
			continue
		}
		if tsInfraReservedCodes[e.code] {
			comments = append(comments, "// codegen: skipped error code \""+e.code+"\" (reserved infra code)")
			continue
		}
		if seenCode[e.code] {
			comments = append(comments, "// codegen: skipped duplicate error code \""+e.code+"\"")
			continue
		}
		stem := typeNameOf(e.name)
		if first, ok := seenClass[stem]; ok {
			comments = append(comments, "// codegen: skipped error \""+e.name+"\" (class name collides with \""+first+"\")")
			continue
		}
		seenCode[e.code] = true
		seenClass[stem] = e.name
		liftable = append(liftable, e)
	}
	return liftable, comments
}

// emitTSTypedErrors emits the `// ── Typed errors ──` section: one exported
// class per liftable error definition across all registrable ops. Returns the
// section text plus the emitted class COUNT (the import line includes
// `BackendError` iff count ≥ 1). The section — header included — renders only
// when at least one class is emitted; filtered errors are skipped SILENTLY
// here because their skip comments already render at the descriptor site in
// the registration block (see tsLiftableErrors).
func emitTSTypedErrors(ops []swiftOp) (string, int) {
	count := 0
	var lines []string
	for _, op := range ops {
		pfx := typePrefix(op.operationID)
		liftable, _ := tsLiftableErrors(op)
		for _, e := range liftable {
			className := pfx + typeNameOf(e.name) + "Error"
			hasData := e.data != nil
			lines = append(lines, "export class "+className+" extends Error {")
			lines = append(lines, "  readonly name = '"+className+"';")
			lines = append(lines, "  readonly code = '"+e.code+"';")
			lines = append(lines, "  readonly status = "+strconv.Itoa(e.status)+";")
			if hasData {
				dataName := pfx + typeNameOf(e.name) + "Data"
				lines = append(lines, "  readonly data: "+dataName+";")
			}
			lines = append(lines, "  readonly cause: BackendError;")
			lines = append(lines, "  constructor(cause: BackendError) {")
			lines = append(lines, "    super(cause.message);")
			lines = append(lines, "    this.cause = cause;")
			if hasData {
				dataName := pfx + typeNameOf(e.name) + "Data"
				lines = append(lines, "    this.data = cause.data as "+dataName+";")
			}
			lines = append(lines, "  }")
			lines = append(lines, "}")
			lines = append(lines, "")
			count++
		}
	}

	if count == 0 {
		return "", 0
	}

	var b strings.Builder
	b.WriteString("// ── Typed errors ───────────────────────────────────────────────────\n\n")
	for _, l := range lines {
		b.WriteString(l)
		b.WriteString("\n")
	}
	return b.String(), count
}

// --- Registration tree --------------------------------------------------

// tsNode is one level of the __registerNamespaces object literal. Entries
// keep insertion order (ops arrive sorted by operationId, so rendered keys
// come out alphabetically), each entry being either a nested namespace
// (child != nil) or a method descriptor (op != nil).
type tsNode struct {
	entries []*tsEntry
	index   map[string]*tsEntry
}

type tsEntry struct {
	key   string
	child *tsNode
	op    *swiftOp
}

func newTSNode() *tsNode { return &tsNode{index: map[string]*tsEntry{}} }

// childNode returns (creating if needed) the nested namespace node for key.
// Returns nil if a METHOD entry already occupies the key (kind mismatch).
func (n *tsNode) childNode(key string) *tsNode {
	if e, ok := n.index[key]; ok {
		if e.child != nil {
			return e.child
		}
		// Method already claims this key — kind mismatch.
		return nil
	}
	e := &tsEntry{key: key, child: newTSNode()}
	n.entries = append(n.entries, e)
	n.index[key] = e
	return e.child
}

// addMethod registers a method at key. Returns false if the key is already
// occupied (either by another method or by a namespace node — kind mismatch).
func (n *tsNode) addMethod(key string, op swiftOp) bool {
	if _, ok := n.index[key]; ok {
		return false
	}
	e := &tsEntry{key: key, op: &op}
	n.entries = append(n.entries, e)
	n.index[key] = e
	return true
}

// buildTSTrie arranges PRE-FILTERED ops (filterTSOps survivors, possibly minus
// type-collision ops) into the namespace trie. Kind mismatches are impossible
// here — removing ops from a mismatch-free set never creates one — so build
// failures are silently skipped as unreachable defensive guards.
func buildTSTrie(ops []swiftOp) *tsNode {
	root := newTSNode()
	for _, op := range ops {
		segs := opSegments(op.operationID)
		if len(segs) == 0 {
			continue
		}
		node := root
		for _, seg := range segs[:len(segs)-1] {
			if node = node.childNode(seg); node == nil {
				break // unreachable: pre-filtered by filterTSOps
			}
		}
		if node != nil {
			node.addMethod(segs[len(segs)-1], op)
		}
	}
	return root
}

// emitTSRegistration renders the __registerNamespaces({…}) call (no section
// header or skip comments — those are written by emitTypeScript above; ops
// arrive pre-filtered through filterTSOps). With zero ops the call renders
// single-line: `__registerNamespaces({});`.
func emitTSRegistration(ops []swiftOp) string {
	if len(ops) == 0 {
		return "__registerNamespaces({});\n"
	}
	var b strings.Builder
	b.WriteString("__registerNamespaces({\n")
	renderTSNode(&b, buildTSTrie(ops), 2)
	b.WriteString("});\n")
	return b.String()
}

// renderTSNode renders one tree level at the given indent, recursing into
// nested namespaces.
func renderTSNode(b *strings.Builder, node *tsNode, indentSpaces int) {
	ind := strings.Repeat(" ", indentSpaces)
	for _, e := range node.entries {
		if e.child != nil {
			b.WriteString(ind)
			b.WriteString(tsPropKey(e.key))
			b.WriteString(": {\n")
			renderTSNode(b, e.child, indentSpaces+2)
			b.WriteString(ind)
			b.WriteString("},\n")
			continue
		}
		b.WriteString(renderTSDescriptor(*e.op, e.key, indentSpaces))
	}
}

// renderTSDescriptor renders one method descriptor entry at the given indent
// depth (number of spaces). Single-line when no errors survive filtering;
// multi-line when an errors map is emitted.
//
// Descriptor field rules:
//   - `method` and `path` always present
//   - `pathParams` present when op.pathParams is non-empty
//   - `input: 'none'` when op.input==nil && op.query==nil (explicit: no body, no query)
//   - `input: 'query'` when op.query!=nil (and no body; body+query conflict handled upstream)
//   - no `input` key when op.input != nil (body is the default)
//   - `errors` map when liftable errors exist → forces multi-line
func renderTSDescriptor(op swiftOp, methodSeg string, indentSpaces int) string {
	ind := strings.Repeat(" ", indentSpaces)
	key := tsPropKey(methodSeg)

	// Error filtering is shared with the typed-errors section and the Data
	// interface emission (tsLiftableErrors) so all three always agree — a
	// dropped error must neither lift in the errors map nor emit a class or
	// an orphan Data interface. The skip comments render HERE, at the
	// descriptor site.
	liftable, errComments := tsLiftableErrors(op)
	hasErrors := len(liftable) > 0

	hasPathParams := len(op.pathParams) > 0
	hasInput := op.input != nil
	hasQuery := op.query != nil

	// Determine input field.
	inputVal := "" // empty = omit (body default)
	if !hasInput && !hasQuery {
		inputVal = "none"
	} else if hasQuery {
		inputVal = "query"
	}

	var b strings.Builder
	if !hasErrors {
		// Single-line format: `key: { method: 'X', path: '...', [extras...] },`
		for _, c := range errComments {
			b.WriteString(ind + c + "\n")
		}
		var parts []string
		parts = append(parts, "method: "+tsStringLit(op.method))
		parts = append(parts, "path: "+tsStringLit(op.path))
		if hasPathParams {
			parts = append(parts, "pathParams: ["+renderTSStringArray(op.pathParams)+"]")
		}
		if inputVal != "" {
			parts = append(parts, "input: "+tsStringLit(inputVal))
		}
		b.WriteString(ind + key + ": { " + strings.Join(parts, ", ") + " },\n")
		return b.String()
	}

	// Multi-line format.
	innerInd := strings.Repeat(" ", indentSpaces+2)
	b.WriteString(ind + key + ": {\n")
	b.WriteString(innerInd + "method: " + tsStringLit(op.method) + ",\n")
	b.WriteString(innerInd + "path: " + tsStringLit(op.path) + ",\n")
	if hasPathParams {
		b.WriteString(innerInd + "pathParams: [" + renderTSStringArray(op.pathParams) + "],\n")
	}
	if inputVal != "" {
		b.WriteString(innerInd + "input: " + tsStringLit(inputVal) + ",\n")
	}
	for _, c := range errComments {
		b.WriteString(innerInd + c + "\n")
	}
	b.WriteString(innerInd + "errors: { ")
	for i, e := range liftable {
		if i > 0 {
			b.WriteString(", ")
		}
		className := typePrefix(op.operationID) + typeNameOf(e.name) + "Error"
		b.WriteString(tsPropKey(e.code) + ": (e) => new " + className + "(e)")
	}
	b.WriteString(" },\n")
	b.WriteString(ind + "},\n")
	return b.String()
}

// renderTSStringArray renders a Go []string as TS array literal elements:
// `'a', 'b', 'c'` (no surrounding brackets — caller adds them).
func renderTSStringArray(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = tsStringLit(s)
	}
	return strings.Join(parts, ", ")
}

// --- Augmentation (declare module '@palbase/web') ---------------------------

// emitTSAugmentation renders the `declare module '@palbase/web' { interface PB { ... } }`
// block, mirroring the registration trie shape with typed method signatures.
// Ops arrive pre-filtered (same set as emitTSRegistration).
func emitTSAugmentation(ops []swiftOp) string {
	var b strings.Builder
	b.WriteString("declare module '@palbase/web' {\n")
	b.WriteString("  interface PB {\n")
	renderTSAugNode(&b, buildTSTrie(ops), 4)
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

// renderTSAugNode renders augmentation entries at the given indent.
func renderTSAugNode(b *strings.Builder, node *tsNode, indentSpaces int) {
	ind := strings.Repeat(" ", indentSpaces)
	for _, e := range node.entries {
		if e.child != nil {
			b.WriteString(ind + tsPropKey(e.key) + ": {\n")
			renderTSAugNode(b, e.child, indentSpaces+2)
			b.WriteString(ind + "};\n")
			continue
		}
		b.WriteString(ind + tsPropKey(e.key) + renderTSMethodSignature(*e.op) + ";\n")
	}
}

// renderTSMethodSignature builds the TypeScript method signature for one op.
// Shape: (pathParam: string, ..., input?: T, options?: CallOptions): Promise<R>
// Rules (from plan contract §3):
//   - leading args: one `name: string` per pathParam in order
//   - body input (op.input != nil): `input: <Prefix>Request`
//   - query input (op.query != nil): `query: <Prefix>Query`
//   - no input (both nil): no input arg
//   - headers (op.headers != nil): fold into options intersection; required when
//     any header param is required, optional otherwise
//   - options: `options?: CallOptions` when no headers; otherwise as above
//   - return: `Promise<<Prefix>Response>` or `Promise<void>` when no output
func renderTSMethodSignature(op swiftOp) string {
	pfx := typePrefix(op.operationID)
	var args []string

	// Leading path params. Wire names are sanitized into valid TS identifiers
	// (`{user-id}` → userId, reserved words escaped, repeats deduped) — the
	// names are purely positional: the runtime substitutes via the descriptor's
	// pathParams, which keep the WIRE names, so renaming here is safe.
	used := map[string]bool{}
	for _, p := range op.pathParams {
		args = append(args, tsParamIdent(p, used)+": string")
	}

	// Input arg. A zero-prop object body still takes a real `input` arg (lead
	// decision): `{}` is a valid wire body and the descriptor defaults to body.
	if op.input != nil {
		args = append(args, "input: "+pfx+"Request")
	} else if op.query != nil {
		args = append(args, "query: "+pfx+"Query")
	}

	// Options arg: fold headers when present.
	optionsArg := buildOptionsArg(op.headers)
	args = append(args, optionsArg)

	// Return type.
	ret := "Promise<void>"
	if op.output != nil {
		ret = "Promise<" + pfx + "Response>"
	}

	return "(" + strings.Join(args, ", ") + "): " + ret
}

// buildOptionsArg constructs the options parameter (with or without headers).
// Required when any declared header is required; optional otherwise.
func buildOptionsArg(headers *swiftSchema) string {
	if headers == nil || len(headers.props) == 0 {
		return "options?: CallOptions"
	}
	// Check if any header is required.
	anyRequired := false
	for _, p := range headers.props {
		if p.required {
			anyRequired = true
			break
		}
	}

	// Build the headers object type.
	headersOpt := "?"
	if anyRequired {
		headersOpt = ""
	}
	var hParts []string
	for _, p := range headers.props {
		opt := ""
		if !p.required {
			opt = "?"
		}
		hParts = append(hParts, tsPropKey(p.name)+opt+": "+tsTypeOf(p.schema))
	}
	headersType := "{ " + strings.Join(hParts, "; ") + " }"

	if anyRequired {
		return "options: CallOptions & { headers: " + headersType + " }"
	}
	return "options?: CallOptions & { headers" + headersOpt + ": " + headersType + " }"
}

// tsParamIdent converts a wire path-param name into a safe TS parameter
// identifier: camelCase-sanitized (`user-id` → userId), TS reserved words and
// the fixed signature arg names (input/query/options) escaped with a trailing
// underscore (`delete` → delete_), repeats deduped with a numeric suffix
// (`{id}/{id}` → id, id2). Records the chosen name in `used`.
func tsParamIdent(name string, used map[string]bool) string {
	id := sanitize(name, false)
	if tsReservedWords[id] || id == "input" || id == "query" || id == "options" {
		id += "_"
	}
	candidate := id
	for n := 2; used[candidate]; n++ {
		candidate = id + strconv.Itoa(n)
	}
	used[candidate] = true
	return candidate
}

// tsReservedWords are ECMAScript keywords plus strict-mode reserved names that
// cannot be used as parameter binding identifiers in a module.
var tsReservedWords = map[string]bool{
	"await": true, "break": true, "case": true, "catch": true, "class": true,
	"const": true, "continue": true, "debugger": true, "default": true,
	"delete": true, "do": true, "else": true, "enum": true, "export": true,
	"extends": true, "false": true, "finally": true, "for": true,
	"function": true, "if": true, "import": true, "in": true,
	"instanceof": true, "new": true, "null": true, "return": true,
	"super": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true, "while": true,
	"with": true, "yield": true,
	// strict-mode reserved / restricted binding names
	"implements": true, "interface": true, "let": true, "package": true,
	"private": true, "protected": true, "public": true, "static": true,
	"arguments": true, "eval": true,
}

// tsBareKeyRe matches identifiers that are valid bare TS object keys.
var tsBareKeyRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// tsPropKey renders an object-literal property key: bare when it is a valid
// identifier, single-quoted via tsStringLit otherwise (kebab-case segments,
// codes with dots, …).
func tsPropKey(name string) string {
	if tsBareKeyRe.MatchString(name) {
		return name
	}
	return tsStringLit(name)
}

// tsStringLit returns a single-quoted TypeScript string literal, escaping
// backslash and single quotes (and newlines/carriage returns defensively).
func tsStringLit(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return "'" + s + "'"
}

// tsReservedTopLevel reports whether the top-level namespace segment is
// reserved. Case-insensitive for the iOS SDK set (auth/analytics/flags/realtime)
// + case-sensitive for the web-only set (call, upload, then) and all
// Object.prototype members.
func tsReservedTopLevel(seg string) bool {
	lower := strings.ToLower(seg)
	// iOS SDK reserved (case-insensitive).
	switch lower {
	case "auth", "analytics", "flags", "realtime":
		return true
	}
	// Web SDK reserved + Object.prototype members (case-sensitive).
	return tsReservedWebOnly(seg)
}

// tsReservedNested reports whether a non-first segment is reserved for
// nested positions. This is the Object.prototype members + `then`, but
// NOT `call` or `upload` (those are only reserved at the top level).
// Applied to every non-first segment including the final method segment —
// see filterTSOps for why.
func tsReservedNested(seg string) bool {
	switch seg {
	case "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsReservedWebOnly contains the web-only reserved set (call/upload/then)
// plus Object.prototype members. Case-sensitive.
func tsReservedWebOnly(seg string) bool {
	switch seg {
	case "call", "upload", "then":
		return true
	}
	return tsObjectPrototypeMember(seg)
}

// tsObjectPrototypeMember reports whether seg is an Object.prototype member.
func tsObjectPrototypeMember(seg string) bool {
	switch seg {
	case "constructor", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable",
		"toLocaleString", "toString", "valueOf",
		"__proto__", "__defineGetter__", "__defineSetter__",
		"__lookupGetter__", "__lookupSetter__":
		return true
	}
	return false
}
