// AUTO-GENERATED by `palbase types --lang ts` — DO NOT EDIT.
// Regenerate: palbase types   (or automatically via the predev/prebuild script)
import type { BackendError, CallOptions } from 'palbe';
import { __configure, __registerNamespaces } from 'palbe/internal';

__configure({
  url: 'https://abc12345m.dev.palbase.studio',
  apiKey: 'pb_abc12345m_cXXXX',
  branch: 'main',
  oauth: {
    google: { enabled: true, clientId: 'g-123' },
  },
});

// ── Types ──────────────────────────────────────────────────────────

export interface GetHelloResponse {
  ok: boolean;
}

export interface RoomsCreateRequest {
  capacity?: number;
  kind: 'public' | 'private';
  name: string;
}

export interface RoomsCreateResponse {
  id: string;
  score: number | null;
  tags: string[];
}

/** room_locked (409): Room is locked */
export interface RoomsCreateRoomLockedData {
  locked_until: string;
}

export interface TodosGetResponse {
  id: string;
  title: string;
}

export interface TodosListQuery {
  done?: boolean;
  limit: number;
}

export interface TodosListResponseItem {
  id: string;
}

export type TodosListResponse = TodosListResponseItem[];

// ── Typed errors ───────────────────────────────────────────────────

export class RoomsCreateRoomFullError extends Error {
  readonly name = 'RoomsCreateRoomFullError';
  readonly code = 'room_full';
  readonly status = 423;
  readonly cause: BackendError;
  constructor(cause: BackendError) {
    super(cause.message);
    this.cause = cause;
  }
}

export class RoomsCreateRoomLockedError extends Error {
  readonly name = 'RoomsCreateRoomLockedError';
  readonly code = 'room_locked';
  readonly status = 409;
  readonly data: RoomsCreateRoomLockedData;
  readonly cause: BackendError;
  constructor(cause: BackendError) {
    super(cause.message);
    this.cause = cause;
    this.data = cause.data as RoomsCreateRoomLockedData;
  }
}

// ── Namespaces ─────────────────────────────────────────────────────

// codegen: skipped reserved namespace "auth"
// codegen: skipped reserved namespace "toString"
__registerNamespaces({
  getHello: { method: 'GET', path: '/hello', input: 'none' },
  rooms: {
    create: {
      method: 'POST',
      path: '/rooms/create',
      errors: { room_full: (e) => new RoomsCreateRoomFullError(e), room_locked: (e) => new RoomsCreateRoomLockedError(e) },
    },
  },
  todos: {
    get: { method: 'GET', path: '/todos/{id}', pathParams: ['id'], input: 'none' },
    list: { method: 'GET', path: '/todos', input: 'query' },
  },
});

declare module 'palbe' {
  interface PB {
    getHello(options?: CallOptions): Promise<GetHelloResponse>;
    rooms: {
      create(input: RoomsCreateRequest, options?: CallOptions): Promise<RoomsCreateResponse>;
    };
    todos: {
      get(id: string, options?: CallOptions): Promise<TodosGetResponse>;
      list(query: TodosListQuery, options?: CallOptions): Promise<TodosListResponse>;
    };
  }
}
